program Faturamento;

uses
  VarSYS,
  Forms,
  Windows,
  SysUtils,
  Variants,
  Dialogs,
  DataModuloTemplate in '..\..\Template\DataModuloTemplate.pas' {DMTemplate: TDataModule},
  CadastroTEMPLATE in '..\..\Template\CadastroTEMPLATE.pas' {FormCadastroTemplate},
  PrincipalTemplate in '..\..\Template\PrincipalTemplate.pas' {FormPrincipalTemplate},
  FormResources in '..\..\Template\FormResources.pas',
  TelaGeralTEMPLATE in '..\..\Template\TelaGeralTEMPLATE.pas' {FormTelaGeralTEMPLATE},
  DataModulo in 'DataModulo.pas' {DM: TDataModule},
  Principal in 'Principal.pas' {FormPrincipal},
  TELALOGIN in 'TelaLogin.pas' {FormTelaLogin},
  ComCtrls in 'ComCtrls.pas',
  UnitLibrary in '..\ArquivosComuns\UnitLibrary.pas',
  CadastroTipoCliente in '..\ArquivosComuns\CadastroTipoCliente.pas' {FormCadastroTipoCliente},
  CadastroCliente in '..\ArquivosComuns\CadastroCliente.pas' {FormCadastroCliente},
  RelatorioTemplate in '..\..\Template\RelatorioTemplate.pas' {FormRelatorioTEMPLATE},
  CadastroBanco in '..\ArquivosComuns\CadastroBanco.pas' {FormCadastroBanco},
  CadastroTipoDocumento in 'CadastroTipoDocumento.pas' {FormCadastroTipoDocumento},
  CadastroPortador in 'CadastroPortador.pas' {FormCadastroPortador},
  CadastroPlanodeContas in 'CadastroPlanodeContas.pas' {FormCadastroPlanodeContas},
  CadastroProfissional in '..\SISCON\CadastroProfissional.pas' {FormCadastroProfissional},
  CadastroClienteDependente in '..\ArquivosComuns\CadastroClienteDependente.pas' {FormCadastroClienteDependente},
  CadastroClienteReferencia in '..\ArquivosComuns\CadastroClienteReferencia.pas' {FormCadastroClienteReferencia},
  CadastroMotivoBloqueio in '..\ArquivosComuns\CadastroMotivoBloqueio.pas' {FormCadastroMotivoBloqueio},
  CadastroProfissao in '..\ArquivosComuns\CadastroProfissao.pas' {FormCadastroProfissao},
  CadastroClienteContato in '..\ArquivosComuns\CadastroClienteContato.pas' {FormCadastroClienteContato},
  CadastroClasse in '..\ArquivosComuns\CadastroClasse.pas' {FormCadastroClasse},
  CadastroClasseUsuario in '..\ArquivosComuns\CadastroClasseUsuario.pas' {FormCadastroClasseUsuario},
  CadastroUsuario in '..\ArquivosComuns\CadastroUsuario.pas' {FormCadastroUsuario},
  CadastroPedidoVenda in 'CadastroPedidoVenda.pas' {FormCadastroPedidoVenda},
  CadastroPedidoVendaItem in 'CadastroPedidoVendaItem.pas' {FormCadastroPedidoVendaItem},
  CadastroTransportadora in '..\ArquivosComuns\CadastroTransportadora.pas' {FormCadastroTransportadora},
  TelaEmissaoEtiquetasCodigoBarras in '..\ArquivosComuns\TelaEmissaoEtiquetasCodigoBarras.pas' {FormTelaEmissaoEtiquetasCodigoBarras},
  TelaEmissaoEtiquetaGrade in '..\UnitLoja\TelaEmissaoEtiquetaGrade.pas' {FormTelaEmissaoEtiquetaGrade},
  CadastroClassificacaoFiscal in '..\ArquivosComuns\CadastroClassificacaoFiscal.pas' {FormCadastroClassificacaoFiscal},
  CadastroFornecedor in '..\ArquivosComuns\CadastroFornecedor.pas' {FormCadastroFornecedor},
  CadastroNotaFiscal in 'CadastroNotaFiscal.pas' {FormCadastroNotaFiscal},
  TelaConsultaTemplate in '..\..\Template\TelaConsultaTemplate.pas' {FormTelaConsultaTemplate},
  TelaConsultaProduto in '..\ArquivosComuns\TelaConsultaProduto.pas' {FormTelaConsultaProduto},
  TelaConsultaNotaCompra in '..\ArquivosComuns\TelaConsultaNotaCompra.pas' {FormTelaConsultaNotaCompra},
  TelaConsultaPedidoCompra in '..\ArquivosComuns\TelaConsultaPedidoCompra.pas' {FormTelaConsultaPedidoCompra},
  TelaConsultaPedidoVenda in '..\ArquivosComuns\TelaConsultaPedidoVenda.pas' {FormTelaConsultaPedidoVenda},
  TelaConsultaNotaFiscal in '..\ArquivosComuns\TelaConsultaNotaFiscal.pas' {FormTelaConsultaNotaFiscal},
  CadastroTipoFornecedor in '..\ArquivosComuns\CadastroTipoFornecedor.pas' {FormCadastroTipoFornecedor},
  CadastroTipoCusto in '..\ArquivosComuns\CadastroTipoCusto.pas' {FormCadastroTipoCusto},
  CadastroNotaFiscalItem in 'CadastroNotaFiscalItem.pas' {FormCadastroNotaFiscalItem},
  CadastroNotaFiscalFinanceiro in 'CadastroNotaFiscalFinanceiro.pas' {FormCadastroNotaFiscalFinanceiro},
  TelaImportacaoPedidoVenda in 'TelaImportacaoPedidoVenda.pas' {FormTelaImportacaoPedidoVenda},
  CadastroOperacoesEstoque in 'CadastroOperacoesEstoque.pas' {FormCadastroOperacoesEstoque},
  TelaLancamentoGradeNotaFiscal in 'TelaLancamentoGradeNotaFiscal.pas' {FormTelaLancamentoGradeNotaFiscal},
  TelaConsultaNumerario in '..\ArquivosComuns\TelaConsultaNumerario.pas' {FormTelaConsultaNumerario},
  TelaConsultaPortador in '..\ArquivosComuns\TelaConsultaPortador.pas' {FormTelaConsultaPortador},
  CadastroPedidoVendaFinanceiro in 'CadastroPedidoVendaFinanceiro.pas' {FormCadastroPedidoVendaFinanceiro},
  TelaConsultaTabelaPreco in '..\ArquivosComuns\TelaConsultaTabelaPreco.pas' {FormTelaConsultaTabelaPreco},
  CadastroSerie in '..\Config\CadastroSerie.pas' {FormCadastroSerie},
  RelatorioNotaFiscalEmitida in 'RelatorioNotaFiscalEmitida.pas' {FormRelatorioNotaFiscalEmitida},
  RelatorioItensPedidoVenda in 'RelatorioItensPedidoVenda.pas' {FormRelatorioItensPedidoVenda},
  RelatorioPedidoVenda in 'RelatorioPedidoVenda.pas' {FormRelatorioPedidoVenda},
  TelaConsultaTipoDocumento in '..\ArquivosComuns\TelaConsultaTipoDocumento.pas' {FormTelaConsultaTipoDocumento},
  CadastroConsulta in '..\ArquivosComuns\CadastroConsulta.pas' {FormCadastroConsulta},
  TelaEnvioEmailGeral in '..\ArquivosComuns\TelaEnvioEmailGeral.pas' {FormTelaEnvioEmailGeral},
  CadastroCep in '..\ArquivosComuns\CadastroCep.pas' {FormCadastroCep},
  TelaImpressaoDuplicatas in '..\UnitFinanceiro\TelaImpressaoDuplicatas.pas' {FormTelaImpressaoDuplicata},
  TelaImpressaoBloquetos in 'TelaImpressaoBloquetos.pas' {FormTelaImpressaoBloquetos},
  ExtensoLib in '..\ArquivosComuns\ExtensoLib.pas',
  TelaImpressaoTermicaCodBar in '..\ArquivosComuns\TelaImpressaoTermicaCodBar.pas' {FormTelaImpressaoTermicaCodBar},
  TelaConsultaCupom in 'TelaConsultaCupom.pas' {FormTelaConsultaCupom},
  WindowsLibrary in '..\ArquivosComuns\WindowsLibrary.pas',
  TelaSaldoPorLote in 'TelaSaldoPorLote.pas' {FormTelaSaldoPorLote},
  TelaItensVendaConsignacao in 'TelaItensVendaConsignacao.pas' {FormTelaItensVendaConsignacao},
  TelaImportaItens in '..\ArquivosComuns\TelaImportaItens.pas' {FormTelaImportaItens},
  TelaGeracaoPedido in 'TelaGeracaoPedido.pas' {FormTelaGeracaoPedido},
  TelaConsultaPlanoRecebimento in '..\ArquivosComuns\TelaConsultaPlanoRecebimento.pas' {FormTelaConsultaPlanoRecebimento},
  WaitWindow in '..\ArquivosComuns\WaitWindow.pas',
  TelaConsultaEmpresa in '..\ArquivosComuns\TelaConsultaEmpresa.pas' {FormTelaConsultaEmpresa},
  CadastroCodigoFiscalOperacao in '..\Config\CadastroCodigoFiscalOperacao.pas' {FormCadastroCodigoFiscalOperacao},
  DataModuloImpNotaFiscal in 'DataModuloImpNotaFiscal.pas' {DMImpNotaFiscal: TDataModule},
  SearchLibrary in '..\ArquivosComuns\SearchLibrary.pas',
  TelaConsultaPlanoContas in '..\ArquivosComuns\TelaConsultaPlanoContas.pas' {FormTelaConsultaPlanoContas},
  CadastroClienteHistorico in '..\UnitLoja\CadastroClienteHistorico.pas' {FormCadastroClienteHistorico},
  TelaClienteHistorico in '..\ArquivosComuns\TelaClienteHistorico.pas' {FormTelaClienteHistorico},
  TelaDadosCheque in 'TelaDadosCheque.pas' {FormTelaDadosCheque},
  CadastroHistoricoPadrao in '..\ArquivosComuns\CadastroHistoricoPadrao.pas' {FormCadastroHistoricoPadrao},
  TelaDadosTeleEntrega in '..\UnitCheckout\TelaDadosTeleEntrega.pas' {FormTelaDadosTeleEntrega},
  TelaRetornoPesquisaProduto in '..\ArquivosComuns\TelaRetornoPesquisaProduto.pas' {FormTelaRetornoPesquisaProduto},
  CadastroFrete in '..\UnitTransportadora\CadastroFrete.pas' {FormCadastroFrete},
  CadastroFreteItem in '..\UnitTransportadora\CadastroFreteItem.pas' {FormCadastroFreteItem},
  CadastroFuncionario in '..\ArquivosComuns\CadastroFuncionario.pas' {FormCadastroFuncionario},
  CadastroUnidade in '..\ArquivosComuns\CadastroUnidade.pas' {FormCadastroUnidade},
  CadastroFuncionarioContaCorrente in '..\ArquivosComuns\CadastroFuncionarioContaCorrente.pas' {FormCadastroFuncionarioContaCorrente},
  CadastroOperacaoFuncionario in '..\ArquivosComuns\CadastroOperacaoFuncionario.pas' {FormCadastroOperacaoFuncionario},
  CadastroVeiculo in '..\ArquivosComuns\CadastroVeiculo.pas' {FormCadastroVeiculo},
  RelatorioListagemFrete in '..\UnitTransportadora\RelatorioListagemFrete.pas' {FormRelatorioListagemFrete},
  TelaConhecimento in '..\UnitTransportadora\TelaConhecimento.pas' {FormTelaConhecimento},
  TelaConsultaCliente in '..\ArquivosComuns\TelaConsultaCliente.pas' {FormTelaConsultaCliente},
  TelaConsultaGeral in '..\UnitTransportadora\TelaConsultaGeral.pas' {FormTelaConsultaGeral},
  CadastroVariacao in '..\ArquivosComuns\CadastroVariacao.pas' {FormCadastroVariacao},
  CadastroProdutoComposicao in '..\ArquivosComuns\CadastroProdutoComposicao.pas' {FormCadastroProdutoComposicao},
  CadastroProdutoFornecedor in '..\ArquivosComuns\CadastroProdutoFornecedor.pas' {FormCadastroProdutoFornecedor},
  CadastroProdutos in '..\ArquivosComuns\CadastroProdutos.pas' {FormCadastroProduto},
  CadastroProdutoTabelaPreco in '..\ArquivosComuns\CadastroProdutoTabelaPreco.pas' {FormCadastroProdutoTabelaPreco},
  CadastroSubgrupo in '..\ArquivosComuns\CadastroSubgrupo.pas' {FormCadastroSubgrupo},
  CadastroTamanho in '..\ArquivosComuns\CadastroTamanho.pas' {FormCadastroTamanho},
  CadastroMarca in '..\ArquivosComuns\CadastroMarca.pas' {FormCadastroMarca},
  CadastroGrupo in '..\ArquivosComuns\CadastroGrupo.pas' {FormCadastroGrupo},
  CadastroGrade in '..\ArquivosComuns\CadastroGrade.pas' {FormCadastroGrade},
  CadastroCor in '..\ArquivosComuns\CadastroCor.pas' {FormCadastroCor},
  CadastroICMS in '..\ArquivosComuns\CadastroICMS.pas' {FormCadastroICMS},
  TelaCriacaoGrade in '..\ArquivosComuns\TelaCriacaoGrade.pas' {FormTelaCriacaoGrade},
  TelaNegociacaoDivida in '..\ArquivosComuns\TelaNegociacaoDivida.pas' {FormTelaNegociacaoDivida},
  TelaDadosOSPedidoVenda in 'TelaDadosOSPedidoVenda.pas' {FormTelaDadosOSPedidoVenda},
  TelaProdVendItemComp in 'TelaProdVendItemComp.pas' {FormTelaProdVendItemComp},
  CadastroFreteSimples in '..\UnitTransportadora\CadastroFreteSimples.pas' {FormCadastroFreteSimples},
  CadastroAvalista in '..\ArquivosComuns\CadastroAvalista.pas' {FormCadastroAvalista},
  CadastroIcmsUf in '..\ArquivosComuns\CadastroIcmsUf.pas' {FormCadastroIcmsUF},
  TelaLancamentoGradePedido in 'TelaLancamentoGradePedido.pas' {FormTelaLancamentoGradePedido},
  TelaConfigControleConfigImpressaoNF in 'TelaConfigControleConfigImpressaoNF.pas' {FormTelaConfigControleConfigImpressaoNF},
  CadastroCidade in '..\ArquivosComuns\CadastroCidade.pas' {FormCadastroCidade},
  CadastroTabelaFreteFaixaPeso in '..\UnitTransportadora\CadastroTabelaFreteFaixaPeso.pas' {FormCadastroTabelaFreteFaixaPeso},
  CadastroTabelaFreteCidade in '..\UnitTransportadora\CadastroTabelaFreteCidade.pas' {FormCadastroTabelaFreteCidade},
  TelaSelecaoCidadeUFFrete in '..\UnitTransportadora\TelaSelecaoCidadeUFFrete.pas' {FormTelaSelecaoCidadeUFFrete},
  CadastroTabelaFrete in '..\UnitTransportadora\CadastroTabelaFrete.pas' {FormCadastroTabelaFrete},
  RelatorioNotaFiscalEmitidaPorCFOP in 'RelatorioNotaFiscalEmitidaPorCFOP.pas' {FormRelatorioNotaFiscalEmitidaPorCFOP},
  TelaGeralModalTemplate in '..\..\Template\TelaGeralModalTemplate.pas' {FormTelaGeralModalTemplate},
  TelaConsultaOperacaoTesouraria in 'TelaConsultaOperacaoTesouraria.pas' {FormTelaConsultaOperacaoTesouraria},
  CadastroContratoFinanceiro in 'CadastroContratoFinanceiro.pas' {FormCadastroContratoFinanceiro},
  CadastroContrato in 'CadastroContrato.pas' {FormCadastroContrato},
  CadastroFreteFinanceiro in '..\UnitTransportadora\CadastroFreteFinanceiro.pas' {FormCadastroFreteFinanceiro},
  TelaConfigControle in '..\ArquivosComuns\TelaConfigControle.pas' {FormTelaConfigControle},
  TelaProdutoNumeroSerie in '..\ArquivosComuns\TelaProdutoNumeroSerie.pas' {FormTelaGeralModalCadastroProdutoNumeroSerie},
  CadastroRota in '..\ArquivosComuns\CadastroRota.pas' {FormCadastroRota},
  RelatorioMixCarga in 'RelatorioMixCarga.pas' {FormRelatorioMixCarga},
  TelaConfigPedidos in 'TelaConfigPedidos.pas' {FormTelaConfigPedidos},
  RelatorioPedidoVendaEntrega in 'RelatorioPedidoVendaEntrega.pas' {FormRelatorioPedidoVendaEntrega},
  TelaGeracaoNotaFiscal in 'TelaGeracaoNotaFiscal.pas' {FormTelaGeracaoNotasFiscais},
  CadastroVisita in 'CadastroVisita.pas' {FormCadastroVisita},
  CadastroRoteiro in 'CadastroRoteiro.pas' {FormCadastroRoteiro},
  TelaGeracaoRoteiroPalm in 'TelaGeracaoRoteiroPalm.pas' {FormTelaGeracaoRoteiro},
  CadastroObsNotaFiscal in 'CadastroObsNotaFiscal.pas' {FormCadastroObsNotaFiscal},
  CadastroDecreto in '..\Config\CadastroDecreto.pas' {FormCadastroDecreto},
  CadastroProdutoSerie in '..\UnitLoja\CadastroProdutoSerie.pas' {FormCadastroProdutoSerie},
  TelaConfiguracaoLayOutNF in 'TelaConfiguracaoLayOutNF.pas' {FormTelaConfiguracaoLayOutNF},
  RelatorioItensNotaFiscal in 'RelatorioItensNotaFiscal.pas' {FormRelatorioItensNotaFiscal},
  RelatorioNotaFiscalItensCobrancaFrete in 'RelatorioNotaFiscalItensCobrancaFrete.pas' {FormRelatorioNotaFiscalItensCobrancaFrete},
  TelaGeracaoMalaDireta in '..\ArquivosComuns\TelaGeracaoMalaDireta.pas' {FormTelaGeracaoMalaDireta},
  TelaAssistenteLancamentoContasReceber in '..\ArquivosComuns\TelaAssistenteLancamentoContasReceber.pas' {FormTelaAssistenteLancamentoContasReceber},
  TelaGeracaoPedidoParcial in 'TelaGeracaoPedidoParcial.pas' {FormTelaPedidoParcial},
  CadastroPedidoVendaComGrade in 'CadastroPedidoVendaComGrade.pas' {FormCadastroPedidoVendaComGrade},
  TelaFotoExpandida in '..\UnitCheckout\TelaFotoExpandida.pas' {FormTelaFotoExpandida},
  TelaNotaFiscalItemFiltro in 'TelaNotaFiscalItemFiltro.pas' {FormTelaNotaFiscalitemFiltro},
  RelatorioExtratoCliente in '..\ArquivosComuns\RelatorioExtratoCliente.pas' {FormRelatorioExtratoCliente},
  CadastroAgendaTelefonica in '..\ArquivosComuns\CadastroAgendaTelefonica.pas' {FormCadastroAgendaTelefonica},
  TelaAutenticaUsuario in '..\UnitCheckout\TelaAutenticaUsuario.pas' {FormTelaAutenticaUsuario},
  CadastroRepresentante in '..\ArquivosComuns\CadastroRepresentante.pas' {FormCadastroRepresentante},
  CadastroMecVeiculosdoCliente in '..\UnitMecanica\CadastroMecVeiculosdoCliente.pas' {FormCadastroMecVeiculosdoCliente},
  CadastroMecanicos in '..\UnitMecanica\CadastroMecanicos.pas' {FormCadastroMecanicos},
  CadastroMecExecutaEm in '..\UnitMecanica\CadastroMecExecutaEm.pas' {FormCadastroMecExecutaEm},
  CadastroMecGruposServicos in '..\UnitMecanica\CadastroMecGruposServicos.pas' {FormCadastroMecGrupoServicos},
  CadastroMecOrdem in '..\UnitMecanica\CadastroMecOrdem.pas' {FormCadastroMecOrdem},
  CadastroMecOrdemItens in '..\UnitMecanica\CadastroMecOrdemItens.pas' {FormCadastroMecOrdemItem},
  CadastroMecTipoServico in '..\UnitMecanica\CadastroMecTipoServico.pas' {FormCadastroMecTipoServico},
  TelaLembreteTarefa in '..\UnitTarefa\TelaLembreteTarefa.pas' {FormTelaLembreteTarefa},
  ConfigPopUp in '..\UnitTarefa\ConfigPopUp.pas' {FormConfigPopUp},
  TelaCadastroTarefa in '..\UnitTarefa\TelaCadastroTarefa.pas' {FormTelaCadastroTarefa},
  TelaConsultaTarefa in '..\UnitTarefa\TelaConsultaTarefa.pas' {FormTelaConsultaTarefa},
  TelaLembreteTarefa2 in '..\UnitTarefa\TelaLembreteTarefa2.pas' {FormTelaLembreteTarefa2},
  ProcessandoNFe in 'ProcessandoNFe.pas' {FormProcessandoNFE},
  CadastroClienteProduto in '..\ArquivosComuns\CadastroClienteProduto.pas' {FormCadastroClienteProduto},
  RelatorioNotaFiscalEmitidaPorICMS in 'RelatorioNotaFiscalEmitidaPorICMS.pas' {FormRelatorioNotaEmitidaPorICMS},
  CadastroClienteVeiculos in '..\ArquivosComuns\CadastroClienteVeiculos.pas' {FormCadastroClienteVeiculos},
  TelaSaidaRapidaEstoque in '..\ArquivosComuns\TelaSaidaRapidaEstoque.pas' {FormTelaSaidaRapidaEstoque},
  TelaInformaNumeroSerieProduto in '..\UnitCheckout\TelaInformaNumeroSerieProduto.pas' {FormTelaInformaNumeroSerieProduto},
  CadastroGraficaOrdem in '..\UnitGrafica\CadastroGraficaOrdem.pas' {FormCadastroGraficaOrdem},
  CadastroGraficaOrdemItens in '..\UnitGrafica\CadastroGraficaOrdemItens.pas' {FormCadastroGraficaOrdemItem},
  ListagemOrdensGraficas in '..\UnitGrafica\ListagemOrdensGraficas.pas' {FormListagemOrdemGrafica},
  RelatorioOrdemGrafica in '..\UnitGrafica\RelatorioOrdemGrafica.pas' {FormRelatorioOrdemGrafica},
  TelaParcelasVariaveis in '..\UnitGrafica\TelaParcelasVariaveis.pas' {TelaGraficaVariavel},
  RelatorioOrdemToazza in '..\UnitGrafica\RelatorioOrdemToazza.pas' {FormRelatorioOrdensToazza},
  RelatorioOrdemToazzaCaderno in '..\UnitGrafica\RelatorioOrdemToazzaCaderno.pas' {FormRelatorioOrdemGraficaToazzaCaderno},
  RelatorioOrdensListadas in '..\UnitMecanica\RelatorioOrdensListadas.pas' {FormListagemOrdemMecanica},
  RelatorioOrdensPorMecanico in '..\UnitMecanica\RelatorioOrdensPorMecanico.pas' {RelatorioOrdPorMecanico},
  RelatorioOrdensPorExecucao in '..\UnitMecanica\RelatorioOrdensPorExecucao.pas' {RelatorioOrdPorExecucao},
  RelatorioOrdensPecas in '..\UnitMecanica\RelatorioOrdensPecas.pas' {FormRelatorioOrdPecas},
  RelatorioOrdensListagemPecas in '..\UnitMecanica\RelatorioOrdensListagemPecas.pas' {FormListagemOrdemMec_Itens},
  RelatorioServicosPorMecanico in '..\UnitMecanica\RelatorioServicosPorMecanico.pas' {FormRelatorioServicosPorMecanico},
  RelatorioOrdensExecucao in '..\UnitMecanica\RelatorioOrdensExecucao.pas' {FormRelatoriOrdensPorExecucao},
  FormRelatorioServicosPorTipo in '..\UnitMecanica\FormRelatorioServicosPorTipo.pas' {FormRelatorioOrdPorTipoServico},
  RelatorioOrdensServicosPorTipo in '..\UnitMecanica\RelatorioOrdensServicosPorTipo.pas' {RelatorioOrdensServicoPorTipo},
  CadastroFreteSeguro in '..\UnitTransportadora\CadastroFreteSeguro.pas',
  CadastroNotaFiscalReferenciada in 'CadastroNotaFiscalReferenciada.pas' {FormCadastroNotaFiscalReferenciada},
  CadastroOperacoesEstoqueConversor in 'CadastroOperacoesEstoqueConversor.pas' {CadastroOperacoesEstoqueConverte},
  CadastroNotaFiscalCartaCorrecao in 'CadastroNotaFiscalCartaCorrecao.pas' {FormCadastroNotaFiscalCartaCorrecao},
  CadastroCSTConverte in 'CadastroCSTConverte.pas' {CadastroCSTConverter},
  CadastroCSTPisCofinsConverter in 'CadastroCSTPisCofinsConverter.pas' {CadastroCSTPisCofinsConverte},
  CadastroConhecimento in 'CadastroConhecimento.pas' {CadastroConhecimentos},
  CadastroCSTConverteIPI in 'CadastroCSTConverteIPI.pas' {CadastroCSTConverterIPI},
  TelaInutilizacaoNFe in 'TelaInutilizacaoNFe.pas' {FormInutilizacaoNFe},
  CadastroOperacoesEstoqueCFOP in 'CadastroOperacoesEstoqueCFOP.pas' {CadastroOperacaoEstoqueCFOP},
  CadastroFreteCTE in '..\UnitTransportadora\CadastroFreteCTE.pas' {FormCadastroFreteCTE},
  CadastroFreteItemCTE in '..\UnitTransportadora\CadastroFreteItemCTE.pas' {FormCadastroFreteItemCTE},
  TelaAvisoDebito in '..\UnitCheckout\TelaAvisoDebito.pas' {FormTelaAvisoDebito},
  StatusNFe in 'StatusNFe.pas' {frmStatusNFe},
  email in '..\ArquivosComuns\email.pas',
  TelaAtivacao in '..\Ativador\TelaAtivacao.pas' {FormTelaAtivacao},
  CadastroMixVenda in 'CadastroMixVenda.pas' {FormCadastroMixVenda},
  CadastroVendedor in '..\ArquivosComuns\CadastroVendedor.pas' {FormCadastroVendedor},
  TelaSplash in '..\ArquivosComuns\TelaSplash.pas' {FormSplash},
  TelaCapitacaoPedidoSeller in 'TelaCapitacaoPedidoSeller.pas' {FormTelaCapitacaoPedidosSeller},
  TelaConsultaPrevendaTablets in '..\ArquivosComuns\TelaConsultaPrevendaTablets.pas' {FormConsultaPrevendaTablets},
  CadastroEmpresa in '..\Config\CadastroEmpresa.pas' {FormCadastroEmpresa},
  RelatorioMovimentoCaixaFaturamento in 'RelatorioMovimentoCaixaFaturamento.pas' {FormRelatorioMovimentoCaixaFaturamento};

{$R *.RES}

var
  hMapping : hwnd ;
begin
  //Este código foi testado no arquivo dpr do projeto
  hMapping := CreateFileMapping(HWND($FFFFFFFF),
                                nil,
                                PAGE_READONLY,
                                0,
                                32,
                                PChar(ExtractFileName(Application.ExeName))) ;

  if (hMapping <> Null)  and (GetLastError <> 0) then
  begin
    //if not Pergunta('NAO', 'O Unit Checkout já está sendo executado, deseja abrir outra cópia ?') then
    //Informa('Gestão Empresarial - Módulo Faturamento já está sendo executado neste computador!') ;
    //Halt ;
  end ;

  Application.Initialize ;
  VersaoSistema := '3.2' ;
  Retaguarda := true;
  Application.Title := 'Gestão Empresarial - Módulo Faturamento';

  Application.CreateForm(TDM, DM);
  if dm.SQLConfigGeralCFGECBLOQ.AsString = 'S' then
    begin
      ShowMessage('Sistema Bloqueado!!! Ligue para a Suporte');
      DM.DB.Close;
      DM.zdb.Connected := False;
      application.terminate;
    end
  else
    begin
      FormTelaLogin := TFormTelaLogin.Create(Application);
      FormTelaLogin.Caption := 'Bem Vindo ao Gestão Empresarial - Módulo Faturamento' ;

      if FormTelaLogin.ShowModal <> idOk then
        begin
          dm.Zdb.Connected := False;
          application.terminate;
        end;

      Application.CreateForm(TFormPrincipal, FormPrincipal);
      FormPrincipal.RodapePrincipal.Panels[0].Text := 'Empresa: ' +DM.SQLConfigGeralEmpresaPadraoCalcField.Value;
      FormPrincipal.RodapePrincipal.Panels[1].Text := 'Terminal: '+Dm.SQLTerminalAtivoTERMA60DESCR.AsString;
      FormPrincipal.RodapePrincipal.Panels[2].Text := 'Usuário: ' +DM.SQLUsuarioUSUAA60LOGIN.Value;
      FormPrincipal.RodapePrincipal.Panels[4].Text := 'Validade da Licença: ' +DM.SQLConfigGeralCFGEDBLOQ.AsString;
      Application.Run ;
    end;  
end.
