unit DataModulo;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, DataModuloTemplate, DB, DBTables, DBLists, RxQuery,VarSys;

type
  TDM = class(TDMTemplate)
    SQLUsuario: TRxQuery;
    SQLUsuarioUSUAICOD: TIntegerField;
    SQLUsuarioUSUAA60LOGIN: TStringField;
    SQLUsuarioUSUAA5SENHA: TStringField;
    SQLUsuarioPENDENTE: TStringField;
    SQLUsuarioREGISTRO: TDateTimeField;
    SQLConfigGeral: TRxQuery;
    SQLConfigGeralCFGECATIVAEXPORT: TStringField;
    SQLConfigGeralCFGECATUSALDODIA: TStringField;
    SQLConfigGeralCFGEITIPMOVCONTENT: TIntegerField;
    SQLConfigGeralCFGEITIPMOVCONTSAI: TIntegerField;
    SQLConfigGeralCFGEA255PATHBLOQ: TStringField;
    SQLConfigGeralCFGECSETAREMPADREL: TStringField;
    SQLConfigGeralCFGECTROCAEMPLOGON: TStringField;
    SQLConfigGeralCFGEA255PATHFOTOCLI: TStringField;
    SQLConfigGeralCFGE1255PATHMALDIR: TStringField;
    SQLConfigGeralCFGECDELARQTEMPREL: TStringField;
    SQLConfigGeralCFGEA255PATHLOGOEMP: TStringField;
    SQLConfigGeralCFGECATUALSALDOMES: TStringField;
    SQLConfigGeralCFGECVALCODBARPROD: TStringField;
    SQLConfigGeralCFGECVALCODANTPRO: TStringField;
    SQLConfigGeralCFGECVALREFPROD: TStringField;
    SQLConfigGeralCFGECBASEPRCVENDA: TStringField;
    SQLConfigGeralCFGEIEMPPADRAO: TIntegerField;
    SQLConfigGeralEmpresaPadraoCalcField: TStringField;
    SQLConfigGeralCFGEA60HOSTSMTP: TStringField;
    SQLConfigGeralCFGEA60ENDRETSMTP: TStringField;
    SQLConfigGeralCFGEA60ENDHOSTPOP: TStringField;
    SQLConfigGeralCFGEA60NOMEUSERPOP: TStringField;
    SQLConfigGeralCFGEA60SENHAPOP: TStringField;
    SQLConfigGeralCGGEA30VERSAO: TStringField;
    SQLConfigGeralCFGEA255PATHVERSAO: TStringField;
    SQLConfigGeralCFGEA255PATHETIBAR: TStringField;
    SQLConfigGeralEmpresaMatrizFilialLookUp: TStringField;
    SQLConfigGeralCFGEA255PATHREPORT: TStringField;
    SQLConfigGeralCFGECTESTEANPROD: TStringField;
    SQLConfigGeralCFGECTESTREFPROD: TStringField;
    SQLEmpresa: TRxQuery;
    SQLConfigVenda: TRxQuery;
    SQLConfigVendaCFVEN3MAXLIMCRED: TBCDField;
    SQLConfigVendaCFVEN2PERCLIMCRED: TBCDField;
    SQLConfigVendaCFVECTIPOLIMCRED: TStringField;
    SQLConfigVendaCFVECRENDCONJNOLIM: TStringField;
    SQLConfigVendaCFVECARREDPARCELA: TStringField;
    SQLConfigVendaOPESICODCUPOM: TIntegerField;
    SQLConfigVendaOPESICODCANCCUPOM: TIntegerField;
    SQLConfigVendaOPESICODNF: TIntegerField;
    SQLConfigVendaOPESICODCANCNF: TIntegerField;
    SQLConfigVendaOPESICODRETORNO: TIntegerField;
    SQLConfigVendaOPESICODCANCTROCA: TIntegerField;
    SQLConfigVendaOPESICODTROCA: TIntegerField;
    SQLConfigVendaCFVECPARC0ENTRBAIX: TStringField;
    SQLConfigVendaTPRCICOD: TIntegerField;
    SQLConfigVendaCFVECFAZVENDCONSIG: TStringField;
    SQLConfigVendaOPESICODDEVOL: TIntegerField;
    SQLConfigVendaCFVECQUITARPARCCART: TStringField;
    SQLConfigVendaCFVECINFNUMERFECHCAIX: TStringField;
    SQLConfigCompra: TRxQuery;
    SQLConfigCompraCFCOITIPMOVCANCNFE: TIntegerField;
    SQLConfigCompraCFCOCALTPRCPRODENT: TStringField;
    SQLConfigCompraCFCOCTESTAITENSNFE: TStringField;
    SQLConfigCompraCFCOCTOTPRCVENPROD: TStringField;
    SQLConfigCompraCFCOCNUMSERPRODENT: TStringField;
    SQLConfigCompraCFCOCIMPLEGORDCOMP: TStringField;
    SQLConfigCompraCFCOITIPMOVNFE: TIntegerField;
    SQLConfigCrediario: TRxQuery;
    SQLProdutoOrdemPesquisa: TRxQuery;
    SQLProdutoOrdemPesquisaPDOPIORDEM: TIntegerField;
    SQLProdutoOrdemPesquisaPDOPA30CAMPO: TStringField;
    SQLProduto: TRxQuery;
    DSSQLProduto: TDataSource;
    SQLPreco: TRxQuery;
    SQLTerminalAtivo: TRxQuery;
    SQLTerminalAtivoTERMICOD: TIntegerField;
    SQLTerminalAtivoTERMA60DESCR: TStringField;
    SQLTerminalAtivoTERMCINFDADOSCLICP: TStringField;
    SQLTerminalAtivoTERMA60IMPAUTORIZCOM: TStringField;
    SQLTerminalAtivoTERMA60IMPFICHACLI: TStringField;
    SQLCliente: TRxQuery;
    SQLClienteCLIEA13ID: TStringField;
    SQLClienteTPCLICOD: TIntegerField;
    SQLClienteTPCTICOD: TIntegerField;
    SQLClienteVENDICOD: TIntegerField;
    SQLNovoContato: TRxQuery;
    SQLNovoContatoCONTDCONTATO: TDateTimeField;
    SQLNovoContatoCONTICOD: TIntegerField;
    SQLNovoContatoVENDICOD: TIntegerField;
    SQLNovoContatoCLIEA13ID: TStringField;
    SQLNovoContatoTPCLICOD: TIntegerField;
    SQLNovoContatoTPCTICOD: TIntegerField;
    SQLNovoContatoTPRTICOD: TIntegerField;
    SQLNovoContatoTPCTICODPROX: TIntegerField;
    SQLNovoContatoCONTDPROXCONT: TDateTimeField;
    SQLNovoContatoCONTDREAL: TDateTimeField;
    SQLNovoContatoCONTA255OBS: TStringField;
    SQLNovoContatoPENDENTE: TStringField;
    SQLNovoContatoREGISTRO: TDateTimeField;
    DSNovoContato: TDataSource;
    SQLClienteTCTCIINTERVALO: TIntegerField;
    SQLNovoContatoEMPRICOD: TIntegerField;
    SQLExcluirContatos: TRxQuery;
    StringField1: TStringField;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    SQLUsuarioEmpresa: TRxQuery;
    SQLUsuarioEmpresaUSUAICOD: TIntegerField;
    SQLUsuarioEmpresaEMPRICOD: TIntegerField;
    SQLConfigCrediarioCFCRINRODIASATRBLQVD: TIntegerField;
    SQLConfigCrediarioCFCRN2PERCMULATRAS: TBCDField;
    SQLConfigCrediarioCFCRN2PERCJURATRAS: TBCDField;
    SQLConfigCrediarioCFCRINRODIASTOLJUR: TIntegerField;
    SQLConfigCrediarioCFCRINRODIASTOLMUL: TIntegerField;
    SQLConfigCrediarioCFCRN2PERCTAXACOBR: TBCDField;
    SQLConfigCrediarioCFCRN2PERCADIANT: TBCDField;
    SQLConfigCrediarioCFCRINRODIASADIANT: TIntegerField;
    SQLConfigCrediarioCFCRINRODIACARTA1A: TIntegerField;
    SQLConfigCrediarioCFCRINRODIACARTA2A: TIntegerField;
    SQLConfigCrediarioCFCRINRODIACARTA3A: TIntegerField;
    SQLConfigCrediarioCFCRINRODIACARTA4A: TIntegerField;
    SQLConfigCrediarioCFCRA255PATHCART1A: TStringField;
    SQLConfigCrediarioCFCRA255PATHCART2A: TStringField;
    SQLConfigCrediarioCFCRA255PATHCART3A: TStringField;
    SQLConfigCrediarioCFCRCCONSMOTBLOQ: TStringField;
    SQLConfigCrediarioCFCRCCONSCARTAVISO: TStringField;
    SQLConfigCrediarioCFCRA255PATHRELSPC: TStringField;
    SQLConfigCrediarioCFCRA255PATHAUTDEP: TStringField;
    SQLConfigCrediarioCFCRCBLOQVENDCLI1AV: TStringField;
    SQLConfigCrediarioCFCRCBLOQVENDCLI2AV: TStringField;
    SQLConfigCrediarioCFCRCBLOQVENDCLI3AV: TStringField;
    SQLConfigCrediarioMTBLICODAVISO1: TIntegerField;
    SQLConfigCrediarioMTBLICODAVISO2: TIntegerField;
    SQLConfigCrediarioMTBLICODAVISOSPC: TIntegerField;
    SQLConfigCrediarioMTBLICODAVISOCOBR: TIntegerField;
    SQLConfigCrediarioCFCRCNAOTIRAAVISOANT: TStringField;
    SQLConfigCrediarioMTBLICODAVISOPEND: TIntegerField;
    SQLConfigCrediarioCFCRCPRIORBLOQATUAL: TStringField;
    SQLConfigVendaCFVECIMPENTRCARNE: TStringField;
    SQLTerminalAtivoTERMA60IMPPEDIDO: TStringField;
    SQLNovoContatoUSUAICOD: TIntegerField;
    SQLConfigVendaCFVEINRODIASAVIANIV: TIntegerField;
    SQLConfigGeralCFGEA60FORMATODATA: TStringField;
    SQLConfigGeralCFGEA60FORMATODH: TStringField;
    SQLConfigVendaOPESICODCANCRET: TIntegerField;
    SQLConfigGeralCFGEIORDDADCOMPR: TIntegerField;
    SQLConfigVendaCFVECNOMECADRAPCLI: TStringField;
    SQLConfigVendaCFVECDTNASCCADRAPCLI: TStringField;
    SQLConfigVendaCFVECCPFCADRAPCLI: TStringField;
    SQLConfigVendaCFVECRGCADRAPCLI: TStringField;
    SQLConfigVendaCFVECENDCADRAPCLI: TStringField;
    SQLConfigVendaCFVECCEPCADRAPCLI: TStringField;
    SQLConfigVendaCFVECBAICADRAPCLI: TStringField;
    SQLConfigVendaCFVECCIDACADRAPCLI: TStringField;
    SQLConfigVendaCFVECUFCADRAPCLI: TStringField;
    SQLConfigVendaCFVECFONECADRAPCLI: TStringField;
    SQLConfigVendaCFVECEMAILCADRAPCLI: TStringField;
    SQLConfigVendaCFVECPAICADRAPCLI: TStringField;
    SQLConfigVendaCFVECMAECADRAPCLI: TStringField;
    SQLConfigVendaCFVECNATURCADRAPCLI: TStringField;
    SQLConfigVendaCFVEINROMESESDADCOMPR: TIntegerField;
    SQLConfigGeralCFGECGRAVALOGUSER: TStringField;
    SQLConfigVendaCFVECTRANSFSANGRTESO: TStringField;
    SQLConfigVendaCFVECCALCVOLUMENF: TStringField;
    SQLTerminalAtivoTERMCMOVESTOQUE: TStringField;
    SQLProdutoFilho: TRxQuery;
    SQLProdutoSaldo: TRxQuery;
    SQLConfigCrediarioCFCRA254PATHMALADIRETA: TStringField;
    SQLTeleEntrega: TRxQuery;
    SQLTeleEntregaTELEA13ID: TStringField;
    SQLTeleEntregaEMPRICOD: TIntegerField;
    SQLTeleEntregaTERMICOD: TIntegerField;
    SQLTeleEntregaTELEICOD: TIntegerField;
    SQLTeleEntregaCUPOA13ID: TStringField;
    SQLTeleEntregaNOFIA13ID: TStringField;
    SQLTeleEntregaPDVDA13ID: TStringField;
    SQLTeleEntregaTELEDENTRPREV: TDateTimeField;
    SQLTeleEntregaTELEDENTRPREV1: TDateTimeField;
    SQLTeleEntregaTELEDENTRPREV2: TDateTimeField;
    SQLTeleEntregaTELEDENTRREAL: TDateTimeField;
    SQLTeleEntregaTELEA60SOLICITANTE: TStringField;
    SQLTeleEntregaTELEA60ENTRPARANOME: TStringField;
    SQLTeleEntregaTELEA60ENTRPARAEND: TStringField;
    SQLTeleEntregaTELEA60ENTRPARABAI: TStringField;
    SQLTeleEntregaTELEA60ENTRPARACID: TStringField;
    SQLTeleEntregaTELEA2ENTRPARAUF: TStringField;
    SQLTeleEntregaTELEA15ENTRPARAFONE: TStringField;
    SQLTeleEntregaTELEA60RECPORNOME: TStringField;
    SQLTeleEntregaTELEADREC: TDateTimeField;
    SQLTeleEntregaTELEA1016MENSG: TMemoField;
    SQLTeleEntregaPENDENTE: TStringField;
    SQLTeleEntregaREGISTRO: TDateTimeField;
    SQLTeleEntregaTPVDICOD: TIntegerField;
    SQLTeleEntregaFUNCA13ID: TStringField;
    SQLTeleEntregaTELEA30OCASIAO: TStringField;
    TblTicketPreVendaCab: TTable;
    TblTicketPreVendaCabTicketNumero: TStringField;
    TblTicketPreVendaCabVendedor: TStringField;
    TblTicketPreVendaCabPlano: TStringField;
    TblTicketPreVendaCabCliente: TStringField;
    TblTicketPreVendaCabFoneCliente: TStringField;
    TblTicketPreVendaCabTotalNominal: TFloatField;
    TblTicketPreVendaCabTaxaCrediario: TFloatField;
    TblTicketPreVendaCabAcrescimo: TFloatField;
    TblTicketPreVendaCabDesconto: TFloatField;
    TblTicketPreVendaCabTotalGeral: TFloatField;
    TblTicketPreVendaCabNomeEmpresa: TStringField;
    TblTicketPreVendaCabFoneEmpresa: TStringField;
    TblTicketPreVendaCabNroCreditCard: TStringField;
    TblTicketPreVendaCabNumerarioPagto: TStringField;
    TblTicketPreVendaCabMensagem: TStringField;
    TblTicketPreVendaCabDataEntrega: TStringField;
    TblTicketPreVendaCabTipoVenda: TStringField;
    TblTicketPreVendaCabPessoaRecebeNome: TStringField;
    TblTicketPreVendaCabPessoaRecebeEnder: TStringField;
    TblTicketPreVendaCabPessoaRecebeBai: TStringField;
    TblTicketPreVendaCabPessoaRecebeCid: TStringField;
    TblTicketPreVendaCabPessoaRecebeUF: TStringField;
    TblTicketPreVendaCabPessoaRecebeFone: TStringField;
    TblTicketPreVendaCabMensagem2: TMemoField;
    TblTicketPreVendaCabVlrEntrada: TFloatField;
    TblTicketPreVendaCabNomeClienteVenda: TStringField;
    TblTicketPreVendaCabDocumentoClienteVenda: TStringField;
    TblTicketPreVendaCabEnderecoClienteVenda: TStringField;
    TblTicketPreVendaCabCidadeClienteVenda: TStringField;
    TblTicketPreVendaCabOBSImpressaoCupom: TStringField;
    TblTicketPreVendaCabTERMICOD: TIntegerField;
    TblTicketPreVendaCabPRVDICOD: TIntegerField;
    TblTicketPreVendaCabDataEmissao: TDateTimeField;
    TblTicketPreVendaCabFoneClienteVenda: TStringField;
    TblTicketPreVendaCabUsuarioVendaSTR: TStringField;
    TblTicketPreVendaCabClienteDependente: TIntegerField;
    TblTicketPreVendaCabPlacaVeiculo: TStringField;
    TblTicketPreVendaCabTroco: TFloatField;
    TblTicketPreVendaItem: TTable;
    TblTicketPreVendaItemCodigo: TIntegerField;
    TblTicketPreVendaItemDescricao: TStringField;
    TblTicketPreVendaItemQuantidade: TFloatField;
    TblTicketPreVendaItemValorUnitario: TFloatField;
    TblTicketPreVendaItemValorTotal: TFloatField;
    TblTicketPreVendaItemDesconto: TFloatField;
    TblTicketPreVendaItemMarca: TStringField;
    TblTicketPreVendaItemReferencia: TStringField;
    TblTicketPreVendaItemTroca: TStringField;
    SQLConfigVendaCFVECINFDADOVENDA: TStringField;
    SQLConfigCrediarioCFCRA255PATHCARTPE: TStringField;
    SQLTerminalAtivoEMPRICOD: TIntegerField;
    SQLUsuarioUSUACVRESFINFORN: TStringField;
    SQLEmpresaEMPRICOD: TIntegerField;
    SQLEmpresaEMPRA60RAZAOSOC: TStringField;
    SQLEmpresaEMPRA60NOMEFANT: TStringField;
    SQLEmpresaEMPRCMATRIZFILIAL: TStringField;
    SQLTerminalAtivoTERMINRODECQUANT: TIntegerField;
    SQLConfigVendaCFVECTIPOIMPPED: TStringField;
    SQLConfigVendaCFVECDADOSCHQPDV: TStringField;
    SQLConfigVendaCFVECUSADEBCREDCLI: TStringField;
    SQLConfigVendaCGVECTESTAITENSNF: TStringField;
    SQLConfigVendaCFVEN3ALIQISSQN: TBCDField;
    SQLConfigVendaCFVECIMPLEGPEDVENF: TStringField;
    SQLConfigVendaCFVEN3PERCICMFRETE: TBCDField;
    SQLConfigVendaCFVEA255OBSPADNF: TStringField;
    SQLConfigVendaCFVEITEMPOCONSPROD: TIntegerField;
    SQLConfigVendaCFVECQUITARPARCHQ: TStringField;
    SQLConfigVendaCFVEA255OBSPADRPED: TStringField;
    SQLConfigVendaCFVEIQTDPADRPDV: TIntegerField;
    SQLConfigVendaCFVEA250MSGBLOQ: TStringField;
    SQLConfigVendaCFVEICMSFRETECOD: TIntegerField;
    SQLConfigVendaCFVECMOVESTOQUENF: TStringField;
    SQLConfigVendaCFVECMOVESTOQUEPED: TStringField;
    SQLConfigVendaOPESICODCANCPED: TIntegerField;
    SQLConfigVendaOPESICODPED: TIntegerField;
    SQLConfigVendaMTBLICODVENDCONSIG: TIntegerField;
    SQLConfigVendaCFVECFINVENDADPREVD: TStringField;
    SQLConfigVendaCFVECIMPPREVDCOD: TStringField;
    SQLConfigVendaCFVECFINDPRODPORDESCR: TStringField;
    SQLConfigVendaPORTICOD: TIntegerField;
    SQLConfigVendaTPDCICOD: TIntegerField;
    SQLConfigVendaCFVECEXCLUIPEDFAT: TStringField;
    SQLConfigVendaCFVEINROITENSNF: TIntegerField;
    SQLConfigVendaCFVECALTPEDIMPORT: TStringField;
    SQLConfigVendaCFVECPEDEVLRPRODUTO: TStringField;
    SQLConfigVendaCFVECSUBDEBNOLIMITE: TStringField;
    SQLConfigVendaCFVECTESTALIMTCRED: TStringField;
    SQLConfigVendaCFVEINROCASASDEC: TIntegerField;
    SQLConfigVendaCFVETOBSPADRAONF: TStringField;
    SQLConfigVendaCFVETOBSPADRAOPED: TStringField;
    SQLConfigVendaOPESICODIMPCUPOM: TIntegerField;
    SQLConfigVendaOPESICODVENDCONSIG: TIntegerField;
    SQLConfigVendaCFVECQUITAPARCONV: TStringField;
    SQLConfigVendaCFVEN2PERCCOFINS: TBCDField;
    SQLConfigVendaCFVEN2PERCENCARG: TBCDField;
    SQLConfigVendaCFVEN2PERCPIS: TBCDField;
    SQLConfigVendaCFVECFARREDVLRVEND: TStringField;
    SQLConfigVendaCFVECUSALIBERCRED: TStringField;
    SQLConfigVendaCFVECIMPDESCRPRINF: TStringField;
    SQLConfigVendaCFVECCONTPEDVDAUSU: TStringField;
    SQLConfigVendaCFVECCONTRUSUVLR: TStringField;
    SQLConfigVendaCFVECSOLSENHAALTVLR: TStringField;
    SQLConfigVendaCFVEN2PERCICMS: TBCDField;
    SQLConfigVendaCFVEIOPTESVENDANF: TIntegerField;
    SQLConfigVendaCFVECINFPRODSUBTRI: TStringField;
    SQLConfigVendaCFVECNAOIMPCLFISNF: TStringField;
    SQLConfigVendaCFVECQUITAPARCRT: TStringField;
    SQLConfigVendaCFVEIOPTESVENDNFNA: TIntegerField;
    SQLConfigVendaCFVECFRETEPADRAO: TStringField;
    SQLConfigVendaCFVECINFVLRDEVCVEN: TStringField;
    SQLConfigVendaCFVEA200FVCUSTO: TStringField;
    SQLConfigVendaCFVEA200FVVENDA: TStringField;
    SQLConfigVendaCFVECCALCVOLUME: TStringField;
    SQLConfigVendaCFVEA20ORDIMPVEND: TStringField;
    SQLConfigGeralCFGEA255EXEDUPLICATA: TStringField;
    SQLConfigGeralCFGECESTOQUEPORLOTE: TStringField;
    SQLConfigGeralCFGECALCPRECOAUTOM: TStringField;
    SQLConfigGeralCFGECTIPOMARGLUCRO: TStringField;
    SQLConfigGeralCFGECUSAMARGLIQ: TStringField;
    SQLConfigGeralCFGECUSASALDODIARIO: TStringField;
    SQLConfigGeralOPESICODTRANSFENTR: TIntegerField;
    SQLConfigGeralOPESICODTRANSFSAID: TIntegerField;
    SQLConfigGeralCFGECBLOQ: TStringField;
    SQLConfigGeralCFGEDBLOQ: TDateTimeField;
    SQLConfigGeralCFGEIULTBONUS: TIntegerField;
    SQLConfigGeralCFGECRESUMOFIN: TStringField;
    SQLConfigGeralCFGEN3QUOTA: TBCDField;
    SQLConfigInventario: TQuery;
    SQLConfigInventarioOPESICODENTRADA: TIntegerField;
    SQLConfigInventarioOPESICODSAIDA: TIntegerField;
    SQLTerminalAtivoCLIEA13ID: TStringField;
    SQLTerminalAtivoVENDICOD: TIntegerField;
    SQLTerminalAtivoPLRCICOD: TIntegerField;
    SQLTerminalAtivoTERMCTIPO: TStringField;
    SQLTerminalAtivoTERMCSTATUSCAIXA: TStringField;
    SQLTerminalAtivoTERMDSTATUSCAIXA: TDateTimeField;
    SQLTerminalAtivoUSUAICODATIVO: TIntegerField;
    SQLTerminalAtivoTERMCUSAVENDEDOR: TStringField;
    SQLTerminalAtivoTERMCUSALIMITECRED: TStringField;
    SQLTerminalAtivoTERMA60IMPCARNE: TStringField;
    SQLTerminalAtivoTERMA60IMPORCAMEN: TStringField;
    SQLTerminalAtivoTERMA60IMPCHEQUE: TStringField;
    SQLTerminalAtivoTERMA60IMPTCKAFCX: TStringField;
    SQLTerminalAtivoTERMCUSAMOEDA: TStringField;
    SQLTerminalAtivoTERMCIMPRIMECHEQUE: TStringField;
    SQLTerminalAtivoTERMCCONFIMPCARNE: TStringField;
    SQLTerminalAtivoTERMCIMPCONFDIVIDA: TStringField;
    SQLTerminalAtivoTERMCIMPIDCUPOM: TStringField;
    SQLTerminalAtivoTERMA255MSGCARNE: TStringField;
    SQLTerminalAtivoTERMCIMPBARRASPED: TStringField;
    SQLTerminalAtivoTERMCINFDADOCLIPAD: TStringField;
    SQLTerminalAtivoTERMINUMEVISTA: TIntegerField;
    SQLTerminalAtivoTERMINUMEPRAZO: TIntegerField;
    SQLTerminalAtivoTERMCATIVO: TStringField;
    SQLTerminalAtivoECFA13ID: TStringField;
    SQLTerminalAtivoTERMA5ECFPORTACOM: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCLIE: TStringField;
    SQLTerminalAtivoTERMCECFIMPRVEND: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIV: TStringField;
    SQLTerminalAtivoTERMCIMPPREVENDA: TStringField;
    SQLTerminalAtivoPENDENTE: TStringField;
    SQLTerminalAtivoREGISTRO: TDateTimeField;
    SQLTerminalAtivoTERMIPROXCODCTRC: TIntegerField;
    SQLTerminalAtivoTERMA60NOMECOMPUT: TStringField;
    SQLTerminalAtivoTERMCAUTENTRFIMCUP: TStringField;
    SQLTerminalAtivoTERMA254PATHTERM: TStringField;
    SQLTerminalAtivoTERMCCONFFECHCUPOM: TStringField;
    SQLTerminalAtivoTERMCHIDECLIVENDPL: TStringField;
    SQLTerminalAtivoTERMCIMPRDADINTCUP: TStringField;
    SQLTerminalAtivoTERMCMOSTRAIDCUPOM: TStringField;
    SQLTerminalAtivoTERMIINTERVALOSERV: TIntegerField;
    SQLTerminalAtivoTERMITMPLIMITESERV: TIntegerField;
    SQLTerminalAtivoTERMCSQLORDENADO: TStringField;
    SQLTerminalAtivoTERMINROVIASTEF: TIntegerField;
    SQLTerminalAtivoCFGIICOD: TIntegerField;
    SQLTerminalAtivoTERMTPATHNF: TStringField;
    SQLTerminalAtivoTERMCAUTENTIMPMATRI: TStringField;
    SQLTerminalAtivoTERMA30MODIMPNFISC: TStringField;
    SQLTerminalAtivoTERMA5LEITPORTACOM: TStringField;
    SQLTerminalAtivoTERMA60MODLEITOR: TStringField;
    SQLTerminalAtivoTERMACTIPOIMPPEDORC: TStringField;
    SQLTerminalAtivoTERMCDISPOENTRADA: TStringField;
    SQLTerminalAtivoTERMCIMPCOMPTOTREC: TStringField;
    SQLTerminalAtivoTERMCIMPENTCARNE: TStringField;
    SQLTerminalAtivoTERMTPATHPEDORC: TStringField;
    SQLTerminalAtivoTPDCICOD: TIntegerField;
    SQLTerminalAtivoTERMCNAOAUTRCTOCRD: TStringField;
    SQLTerminalAtivoTERMA60MENSAGEMPDV: TStringField;
    SQLTerminalAtivoTERMCINFDADOCARTAO: TStringField;
    SQLTerminalAtivoTERMA30MODIMPCHQ: TStringField;
    SQLTerminalAtivoTERMA5IMPCHQPORTA: TStringField;
    SQLTerminalAtivoTERMA60IMPNF: TStringField;
    SQLTerminalAtivoTERMCMOSTRATROCOCUP: TStringField;
    SQLTerminalAtivoTERMCIMPNFPRT: TStringField;
    SQLTerminalAtivoTERMCIMPPEDPRT: TStringField;
    SQLTerminalAtivoTERMCSOLCODVEND: TStringField;
    SQLTerminalAtivoTERMCIMPPREVENDASIM: TStringField;
    SQLTerminalAtivoTERMCBXESTFECHCX: TStringField;
    SQLTerminalAtivoTERMCTECLREDUZ: TStringField;
    SQLTerminalAtivoTERMIQTDEPADRAO: TIntegerField;
    SQLTerminalAtivoTERMCMPATACADO: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIVIMPFAT: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIVIMPITENS: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIVPERGUNTA: TStringField;
    SQLTerminalAtivoTERMINUMERECCRED: TIntegerField;
    procedure DataModuleCreate(Sender: TObject);
    procedure SQLNovoContatoBeforePost(DataSet: TDataSet);
    procedure SQLNovoContatoPostError(DataSet: TDataSet; E: EDatabaseError;
      var Action: TDataAction);
  private
    { Private declarations }
  public
    { Public declarations }
    ClienteContatoImediato,ClienteQuestionario:String;
    CodigoQuestioario:Integer;
    ContatoImediato:Boolean;
    EmpresaContatoGerado, CodigoContatoGerado: Integer;
    DataContatoGerado : TDateTime;
  end;

var
  DM: TDM;

implementation

{$R *.dfm}

procedure TDM.DataModuleCreate(Sender: TObject);
begin
  inherited;
  SQLUsuario.Open ;
  SQLConfigGeral.Open ;
  SQLConfigVenda.Open ;
  SQLConfigCrediario.Open ;
  SQLConfigCompra.Open ;
  SQLEmpresa.Open ;

  if SQLEmpresa.Locate('EMPRICOD', DM.SQLConfigGeralCFGEIEMPPADRAO.Value, []) then
    MatrizFilial := SQLEmpresa.FieldByName('EMPRCMATRIZFILIAL').AsString ;
  //FormatoDataUnit     := SQLConfigGeralCFGEA60FORMATODATA.asString;
  //FormatoDataHoraUnit := SQLConfigGeralCFGEA60FORMATODH.asString;

  EmpresaCorrente := DM.SQLConfigGeralCFGEIEMPPADRAO.Value ;
end;

procedure TDM.SQLNovoContatoBeforePost(DataSet: TDataSet);
begin
  inherited;
  If DataSet.FindField('REGISTRO') <> Nil Then
    DataSet.FindField('REGISTRO').AsDateTime := Now ;
  If DataSet.FindField('PENDENTE')<> Nil Then
    DataSet.FindField('PENDENTE').AsString := 'S' ;
  Case DataSet.State Of
    DsInsert: begin
                if (DataSet.Tag in [1,2,3]) Then
                  CodigoAutomatico('CONTATO', DSNovoContato, DataSet, 2, 0);
              End;
  end;
end;

procedure TDM.SQLNovoContatoPostError(DataSet: TDataSet; E: EDatabaseError;
  var Action: TDataAction);
begin
  inherited;
  Case DataSet.State Of
    DsInsert:
      Begin
        Case DataSet.Tag Of
        1,2:DM.CodigoAutomatico('CONTATO', DSNovoContato, DataSet, 2, 0);
         End;
        Action:=DaRetry;
      End;
  end;
end;

end.
