
CREATE TABLE OS (
       OSA13ID              CHAR(13) NOT NULL,
       TERMICOD             INTEGER,
       EMPRICOD             INTEGER,
       OSICOD               INTEGER,
       OSDEMISSAO           DATE,
       CLIEA13ID            CHAR(13),
       OSDPREVENTREGA       DATE,
       OSCSTATUS            CHAR(1),
       OSN2VLRSERVICO       NUMERIC(15,2) DEFAULT 0,
       OSN2VLRDESC          NUMERIC(15,2) DEFAULT 0,
       OSN2PERCDESC         NUMERIC(15,2) DEFAULT 0,
       OSN2VLRPRODUTOS      NUMERIC(15,2) DEFAULT 0,
       OSN2VLRTOTAL         NUMERIC(15,2) DEFAULT 0,
       OSN2VLRFRETE         NUMERIC(15,2) DEFAULT 0,
       OSN2BASEISSQN        NUMERIC(15,2) DEFAULT 0,
       OSN2VLRISSQN         NUMERIC(15,2) DEFAULT 0,
       OSOBS                VARCHAR(500),
       TRANICOD             INTEGER,
       OSDCONCLUSAO         DATE,
       USUA60RESPCONC       CHAR(60),
       OSDENTREGA           DATE,
       OSA60PESSOAENT       CHAR(60),
       OSA30DOCPESENT       CHAR(30),
       USUA60RESPENT        VARCHAR(60),
       USUA60LOGIN          CHAR(60),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       OSA60ENDENTR         CHAR(60),
       OSA60BAIRROENT       CHAR(60),
       OSAUFENTR            CHAR(2),
       OSA15FONEENTR        CHAR(15),
       OSA60CIDENTR         CHAR(60),
       PRIMARY KEY (OSA13ID)
);

CREATE UNIQUE INDEX XPKOS ON OS
(
       OSA13ID
);

CREATE INDEX XIF248OS ON OS
(
       TERMICOD
);

CREATE INDEX XIF249OS ON OS
(
       EMPRICOD
);

CREATE INDEX XIF250OS ON OS
(
       CLIEA13ID
);

CREATE INDEX XIF255OS ON OS
(
       TRANICOD
);


CREATE TABLE OSITEM (
       OSA13ID              CHAR(13) NOT NULL,
       OSITICOD             INTEGER NOT NULL,
       OSITTSTATUS          CHAR(1),
       PRODICOD             INTEGER,
       OSITA30NRONF         CHAR(30),
       OSITCORIGNF          CHAR(1),
       OSITA60EMPRESANF     CHAR(60),
       OSITA60SERIEEQUIP    CHAR(60),
       OSITTDESCREQUIP      VARCHAR(5000),
       OSITTPROBLEMA        VARCHAR(5000),
       OSITTSOLUCAO         VARCHAR(5000),
       OSITTSOFTDRIVEUTIL   VARCHAR(500),
       OSITTOBS             VARCHAR(500),
       OSITN2VLRITEM        NUMERIC(15,2) DEFAULT 0,
       OSITN2VLRDESC        NUMERIC(15,2) DEFAULT 0,
       OSITN2PERCDESC       NUMERIC(15,2),
       OSITN2VLRTOTITEM     NUMERIC(15,2),
       OSITDCONCLUSAO       DATE,
       USUA60RESPCONC       CHAR(60),
       USUA60LOGIN          CHAR(60),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       OSITN2QTDE           NUMERIC(15,2),
       FUNCA13ID            CHAR(13),
       OSITDCANC            DATE,
       PRIMARY KEY (OSA13ID, OSITICOD)
);

CREATE UNIQUE INDEX XPKOSITEM ON OSITEM
(
       OSA13ID,
       OSITICOD
);

CREATE INDEX XIF251OSITEM ON OSITEM
(
       OSA13ID
);

CREATE INDEX XIF252OSITEM ON OSITEM
(
       PRODICOD
);


CREATE TABLE OSITEMPRODUTO (
       OSA13ID              CHAR(13) NOT NULL,
       OSITICOD             INTEGER NOT NULL,
       OSIPICOD             INTEGER NOT NULL,
       PRODICOD             INTEGER,
       OSIPN3QTDE           NUMERIC(15,3) DEFAULT 0,
       OSIPN2VLRCUSTO       NUMERIC(15,2) DEFAULT 0,
       OSIPN2VLRTOTPROD     NUMERIC(15,2) DEFAULT 0,
       USUA60LOGIN          CHAR(60),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (OSA13ID, OSITICOD, OSIPICOD)
);

CREATE UNIQUE INDEX XPKOSITEMPRODUTO ON OSITEMPRODUTO
(
       OSA13ID,
       OSITICOD,
       OSIPICOD
);

CREATE INDEX XIF253OSITEMPRODUTO ON OSITEMPRODUTO
(
       OSA13ID,
       OSITICOD
);

CREATE INDEX XIF254OSITEMPRODUTO ON OSITEMPRODUTO
(
       PRODICOD
);

