ALTER TABLE FORNECEDOR ALTER FORNTOBS TO FORNTOBS2;
commit work;
ALTER TABLE FORNECEDOR ADD FORNTOBS VARCHAR(254);
cOMMIT WORK;
update FORNECEDOR SET FORNTOBS = FORNTOBS2;
COMMIT WORK;
ALTER TABLE FORNECEDOR DROP FORNTOBS2;
COMMIT WORK;

