ALTER TABLE NOTACOMPRA ALTER NOCPA254OBS TO NOCPA254OBS2;
commit work;
ALTER TABLE NOTACOMPRA ADD NOCPA254OBS VARCHAR(4000);
cOMMIT WORK;
update NOTACOMPRA SET NOCPA254OBS = NOCPA254OBS2;
COMMIT WORK;
ALTER TABLE NOTACOMPRA DROP NOCPA254OBS2;
COMMIT WORK;

