ALTER TABLE CUPOMITEM ALTER PVITTOBS TO PVITTOBS2;
commit work;
ALTER TABLE CUPOMITEM ADD PVITTOBS VARCHAR(2000);
cOMMIT WORK;
update CUPOMITEM SET PVITTOBS = PVITTOBS2;
COMMIT WORK;
ALTER TABLE CUPOMITEM DROP PVITTOBS2;
COMMIT WORK;

ALTER TABLE PREVENDAITEM ALTER PVITTOBS TO PVITTOBS2;
commit work;
ALTER TABLE PREVENDAITEM ADD PVITTOBS VARCHAR(2000);
cOMMIT WORK;
update PREVENDAITEM SET PVITTOBS = PVITTOBS2;
COMMIT WORK;
ALTER TABLE PREVENDAITEM DROP PVITTOBS2;
COMMIT WORK;
