ALTER TABLE LMCCAB ADD LMCAN2TQSBR1 NUMERIC(15,2);
ALTER TABLE LMCCAB ADD LMCAN2TQSBR2 NUMERIC(15,2);
ALTER TABLE LMCCAB ADD LMCAN2TQSBR3 NUMERIC(15,2);
ALTER TABLE LMCCAB ADD LMCAN2TQSBR4 NUMERIC(15,2);
ALTER TABLE LMCCAB ADD LMCAN2TQSBR5 NUMERIC(15,2);
ALTER TABLE LMCCAB ADD LMCAN2TQSBR6 NUMERIC(15,2);
