ALTER TABLE CLIENTERECEITUARIO ADD SERIE      CHAR(15);
ALTER TABLE CLIENTERECEITUARIO ADD ARTIGO     CHAR(10);
ALTER TABLE CLIENTERECEITUARIO ADD RECEITA    INTEGER;
ALTER TABLE CLIENTERECEITUARIO ADD PRODICOD   INTEGER;
ALTER TABLE CLIENTERECEITUARIO ADD NOFIA13ID  CHAR(13);
ALTER TABLE CLIENTERECEITUARIO ADD QUANTIDADE NUMERIC(15,3);

