ALTER TABLE PREVENDAITEM ADD BORDA01 VARCHAR(60);
ALTER TABLE PREVENDAITEM ADD BORDA02 VARCHAR(60);
ALTER TABLE PREVENDAITEM ADD BORDA03 VARCHAR(60);

ALTER TABLE PREVENDAITEM ADD SABOR01 VARCHAR(60);
ALTER TABLE PREVENDAITEM ADD SABOR02 VARCHAR(60);
ALTER TABLE PREVENDAITEM ADD SABOR03 VARCHAR(60);
ALTER TABLE PREVENDAITEM ADD SABOR04 VARCHAR(60);
ALTER TABLE PREVENDAITEM ADD SABOR05 VARCHAR(60);
ALTER TABLE PREVENDAITEM ADD SABOR06 VARCHAR(60);
