ALTER TABLE NOTAFISCAL ADD PLCTA15COD           CHAR(15);


ALTER TABLE NOTAFISCAL ADD PDVDA13ID            CHAR(13);


ALTER TABLE NOTAFISCAL ADD VENDICOD             INTEGER;


ALTER TABLE NOTAFISCAL ADD NOFIA30COMPRADOR     CHAR(30);


ALTER TABLE NOTAFISCAL ADD NOFIA30NROPEDCOMP    CHAR(30);


ALTER TABLE NOTAFISCAL ADD NOFIN2VLRICMSFRETE   NUMERIC(15,3);

ALTER TABLE NOTAFISCAL ADD PDVDA60OBS           CHAR(60);
