ALTER TABLE CUPOMITEM      ADD vTribFederal NUMERIC(15,2);
ALTER TABLE CUPOMITEM      ADD vTribEstadual NUMERIC(15,2);
ALTER TABLE CUPOMITEM      ADD CPITN2IMPOSTOMED NUMERIC(15,2);
ALTER TABLE NOTAFISCALITEM ADD NFITN2IMPOSTOMED NUMERIC(15,2);