ALTER TABLE CLIENTE ADD CLIEA60ENDCOB	CHAR(60);
ALTER TABLE CLIENTE ADD CLIEA60BAICOB	CHAR(60);
ALTER TABLE CLIENTE ADD CLIEA60CIDCOB	CHAR(60);
ALTER TABLE CLIENTE ADD CLIEA2UFCOB	CHAR(2);
ALTER TABLE CLIENTE ADD CLIEA8CEPCOB	CHAR(8);