ALTER TABLE CUPOM ADD CLIENTENOME   CHAR(60);
ALTER TABLE CUPOM ADD CLIENTECNPJ   CHAR(20);
ALTER TABLE CUPOM ADD CLIENTEENDE   CHAR(60);
ALTER TABLE CUPOM ADD CLIENTECIDA   CHAR(30);
ALTER TABLE CUPOM ADD CLIENTEBAIRRO CHAR(30);
