ALTER TABLE notacompraitem ADD  NOCA1CSTORIGEM    CHAR(1);
ALTER TABLE notacompraitem ADD  NOCIN2PMVAST      NUMERIC(15,2);
ALTER TABLE notacompraitem ADD  NOCIN2VLRSEGURO   NUMERIC(15,2);
ALTER TABLE notacompraitem ADD  NOCIN2VLRDESPESAS NUMERIC(15,2);





