ALTER TABLE CUPOMITEM ADD BORDA01 VARCHAR(60);
ALTER TABLE CUPOMITEM ADD BORDA02 VARCHAR(60);
ALTER TABLE CUPOMITEM ADD BORDA03 VARCHAR(60);

ALTER TABLE CUPOMITEM ADD SABOR01 VARCHAR(60);
ALTER TABLE CUPOMITEM ADD SABOR02 VARCHAR(60);
ALTER TABLE CUPOMITEM ADD SABOR03 VARCHAR(60);
ALTER TABLE CUPOMITEM ADD SABOR04 VARCHAR(60);
ALTER TABLE CUPOMITEM ADD SABOR05 VARCHAR(60);
ALTER TABLE CUPOMITEM ADD SABOR06 VARCHAR(60);
