ALTER TABLE CLIENTE ADD TPDCICOD   INTEGER;
ALTER TABLE CLIENTE ADD PORTICOD   INTEGER;
ALTER TABLE CLIENTE ADD DIAVENCTO  CHAR(02);
ALTER TABLE CLIENTE ADD CTRCN2VLR  NUMERIC(15,3);
ALTER TABLE CLIENTE ADD PLCTA15COD CHAR(15);