ALTER TABLE REDUCAOZDIA ADD REDUN3ALIQ7 numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3BASE7 numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3IMPO7 numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3ALIQ8 numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3BASE8 numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3IMPO8 numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3ALIQF numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3BASEF numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3IMPOF numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3ALIQI numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3BASEI numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3IMPOI numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3ALIQN numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3BASEN numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3IMPON numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3ALIQS numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3BASES numeric(15,3);
ALTER TABLE REDUCAOZDIA ADD REDUN3IMPOS numeric(15,3);


