ALTER TABLE CONFIGCREDIARIO ADD CFCRCBLOQVENDCLI1AV       CHAR(1);

ALTER TABLE CONFIGCREDIARIO ADD CFCRCBLOQVENDCLI2AV       CHAR(1);

ALTER TABLE CONFIGCREDIARIO ADD CFCRCBLOQVENDCLI3AV       CHAR(1);

