ALTER TABLE CUPOM ADD 	CUPOA30DATACARTAO CHAR(30);
ALTER TABLE CUPOM ADD 	CUPOA30HORACARTAO CHAR(30);
ALTER TABLE CUPOM ADD 	CUPOA30NSUPROVEDOR CHAR(30);
ALTER TABLE CUPOM ADD 	CUPOA30NSUINSTITUICAO CHAR(30);