ALTER TABLE PAGAMENTO ADD PLCTA15CREDITO CHAR(15);
ALTER TABLE PAGAMENTO ADD PLCTA15CODJUROCRED CHAR(15);
ALTER TABLE PAGAMENTO ADD PLCTA15CODMULTCRED CHAR(15);
ALTER TABLE PAGAMENTO ADD PLCTA15CODDESCCRED CHAR(15);
ALTER TABLE PAGAMENTO ADD PLCTA15DEBITO CHAR(15);
ALTER TABLE PAGAMENTO ADD PLCTA15CODJURODEB  CHAR(15);
ALTER TABLE PAGAMENTO ADD PLCTA15CODMULTDEB  CHAR(15);
ALTER TABLE PAGAMENTO ADD PLCTA15CODDESCDEB  CHAR(15);