ALTER TABLE EMPRESA
ADD EMPRA75EMAILUSUARIO VARCHAR(75);
commit work;
ALTER TABLE EMPRESA
ADD EMPRISEQUENCIACOMPRA INTEGER;
commit work;
ALTER TABLE EMPRESA
ADD EMPRA100CERTIFSERIE VARCHAR(100);
commit work;
ALTER TABLE EMPRESA
ADD EMPRA35CERTIFSENHA VARCHAR(35);
commit work;
ALTER TABLE EMPRESA
ADD EMPRIFORMAEMISDANFE INTEGER;
commit work;
ALTER TABLE EMPRESA
ADD EMPRIFORMAEMISNFE INTEGER;
commit work;
ALTER TABLE EMPRESA
ADD EMPRA100CAMINHOLOGO VARCHAR(100);
commit work;
ALTER TABLE EMPRESA
ADD EMPRA100CAMINHOXML VARCHAR(100);
commit work;
ALTER TABLE EMPRESA
ADD EMPRA100CAMINHODANFES VARCHAR(100);
commit work;
ALTER TABLE EMPRESA
ADD EMPRA2WSUF VARCHAR(2);
commit work;
ALTER TABLE EMPRESA
ADD EMPRIWSAMBIENTE INTEGER;
commit work;
ALTER TABLE EMPRESA
ADD EMPRA1VISUALIZAMSG CHAR(1);
commit work;
ALTER TABLE EMPRESA
ADD EMPRA100PROXYHOST VARCHAR(100);
commit work;
ALTER TABLE EMPRESA
ADD EMPRIPROXYPORTA INTEGER;
commit work;
ALTER TABLE EMPRESA
ADD EMPRA50PROXYUSUARIO VARCHAR(50);
commit work;
ALTER TABLE EMPRESA
ADD EMPRA50PROXYSENHA VARCHAR(50);
commit work;
ALTER TABLE EMPRESA
ADD EMPRA50EMAILHOST VARCHAR(50);
commit work;
ALTER TABLE EMPRESA
ADD EMPRIEMAILPORTA INTEGER;
commit work;
ALTER TABLE EMPRESA
ADD EMPRA50EMAILSENHA VARCHAR(50);


