ALTER TABLE CONTASRECEBER ADD BANCA5CODCHQ         CHAR(5);


ALTER TABLE CONTASRECEBER ADD CTRCA10AGENCIACHQ    CHAR(10);


ALTER TABLE CONTASRECEBER ADD CTRCA15CONTACHQ      CHAR(15);


ALTER TABLE CONTASRECEBER ADD CTRCA15NROCHQ        CHAR(15);


ALTER TABLE CONTASRECEBER ADD CTRCA60TITULARCHQ    CHAR(60);


ALTER TABLE CONTASRECEBER ADD CTRCA20CGCCPFCHQ     CHAR(20);


ALTER TABLE CONTASRECEBER ADD CTRCDDEPOSCHQ        DATE;


ALTER TABLE CONTASRECEBER ADD ALINICOD             INTEGER;

