ALTER TABLE RECEBIMENTO ADD PLCTA15CREDITO CHAR(15);
ALTER TABLE RECEBIMENTO ADD PLCTA15CODJUROCRED CHAR(15);
ALTER TABLE RECEBIMENTO ADD PLCTA15CODMULTCRED CHAR(15);
ALTER TABLE RECEBIMENTO ADD PLCTA15CODDESCCRED CHAR(15);
ALTER TABLE RECEBIMENTO ADD PLCTA15DEBITO CHAR(15);
ALTER TABLE RECEBIMENTO ADD PLCTA15CODJURODEB  CHAR(15);
ALTER TABLE RECEBIMENTO ADD PLCTA15CODMULTDEB  CHAR(15);
ALTER TABLE RECEBIMENTO ADD PLCTA15CODDESCDEB  CHAR(15);