ALTER TABLE PREVENDA ADD CLIENTENOME CHAR(60);
ALTER TABLE PREVENDA ADD CLIENTECNPJ CHAR(20);
ALTER TABLE PREVENDA ADD CLIENTEENDE CHAR(60);
ALTER TABLE PREVENDA ADD CLIENTECIDA CHAR(30);
ALTER TABLE PREVENDA ADD CLIENTEOBS  CHAR(60);