UPDATE CONTASPAGAR SET CTPGDRECBTO =  
(SELECT NOCPDRECEBIMENTO FROM NOTACOMPRA WHERE CONTASPAGAR.NOCPA13ID = NOTACOMPRA.NOCPA13ID)
WHERE CTPGDRECBTO IS NULL;

UPDATE CONTASPAGAR SET CTPGDRECBTO = CTPGDTEMIS WHERE CTPGDRECBTO IS NULL;

