UPDATE NOTACOMPRA SET CFOPA5COD = 
(SELECT CFOPA5CODFORAUF FROM OPERACAOESTOQUE WHERE OPERACAOESTOQUE.OPESICOD = NOTACOMPRA.OPESICOD)
WHERE
(SELECT FORNA2UF FROM FORNECEDOR WHERE FORNECEDOR.FORNICOD = NOTACOMPRA.FORNICOD) <>
(SELECT EMPRA2UF FROM EMPRESA WHERE EMPRESA.EMPRICOD = NOTACOMPRA.EMPRICOD)
AND NOTACOMPRA.FORNICOD IS NOT NULL ;

UPDATE NOTACOMPRA SET CFOPA5COD = 
(SELECT CFOPA5CODFORAUF FROM OPERACAOESTOQUE WHERE OPERACAOESTOQUE.OPESICOD = NOTACOMPRA.OPESICOD)
WHERE
(SELECT EMPRA2UF FROM EMPRESA WHERE EMPRESA.EMPRICOD = NOTACOMPRA.EMPRICOD) <> 
(SELECT EMPRA2UF FROM EMPRESA WHERE EMPRESA.EMPRICOD = NOTACOMPRA.EMPRICODDEST)
AND NOTACOMPRA.EMPRICODDEST IS NOT NULL;

UPDATE NOTACOMPRA SET CFOPA5COD = 
(SELECT CFOPA5CODFORAUF FROM OPERACAOESTOQUE WHERE OPERACAOESTOQUE.OPESICOD = NOTACOMPRA.OPESICOD)
WHERE
(SELECT CLIEA2UFRES FROM CLIENTE WHERE NOTACOMPRA.CLIEA13ID = CLIENTE.CLIEA13ID) <> 
(SELECT EMPRA2UF FROM EMPRESA WHERE EMPRESA.EMPRICOD = NOTACOMPRA.EMPRICOD) AND
NOTACOMPRA.CLIEA13ID IS NOT NULL;
