UPDATE USUARIO SET USUACPERMITECASH = 'S'   WHERE USUACPERMITECASH   IS NULL;
UPDATE USUARIO SET USUACPERMITEFAT  = 'S'   WHERE USUACPERMITEFAT    IS NULL;
UPDATE USUARIO SET USUACPERMITEADM  = 'S'   WHERE USUACPERMITEADM    IS NULL;
UPDATE USUARIO SET USUACPERMITEFIN  = 'S'   WHERE USUACPERMITEFIN    IS NULL;
UPDATE USUARIO SET USUACPERMINTEG   = 'S'   WHERE USUACPERMINTEG     IS NULL;
UPDATE USUARIO SET USUACPERMITECONFIG = 'S' WHERE USUACPERMITECONFIG IS NULL;