INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '01',  '50');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '02',  '50');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '03',  '50');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '04',  '73');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '06',  '73');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '07',  '71');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '08',  '74');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '09',  '72');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '49',  '98');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('P',   '99',  '98');

INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '01',  '50');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '02',  '50');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '03',  '50');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '04',  '73');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '06',  '73');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '07',  '71');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '08',  '74');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '09',  '72');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '49',  '98');
INSERT INTO CONVERTECSTPISCOFINS VALUES ('C',   '99',  '98');

