CREATE VIEW VIEW_GRADEPRODUTOCOMPRAS AS
Select
NOTACOMPRA.NOCPA30NRO,
NOTACOMPRAITEM.PRODICOD,
NOTACOMPRAITEM.NOCIN3QTDEMBAL,
PRODUTO.PRODIAGRUPGRADE,
PRODUTO.GRADICOD,
PRODUTO.GRTMICOD,
PRODUTO.CORICOD,
COR.CORA30DESCR
FROM
NOTACOMPRAITEM
inner join NOTACOMPRA on NOTACOMPRAITEM.NOCPA13ID = NOTACOMPRA.NOCPA13ID
left outer join PRODUTO ON NOTACOMPRAITEM.PRODICOD = PRODUTO.PRODICOD
left outer join COR ON PRODUTO.CORICOD = COR.CORICOD
where
(NotaCompra.NOCPCSTATUS <> 'C' or NotaCompra.NOCPCSTATUS is null)
