CREATE TABLE COTACAOCOMPRAITEMFORN (
  CTCPA13ID CHAR(13) NOT NULL,
  CTITIPOS INTEGER NOT NULL,
  PRODICOD INTEGER,
  FORNICOD INTEGER,
  CTITN3CAPEMBAL NUMERIC(15, 3),
  CTITN3QTDEMBAL NUMERIC(15, 3),
  CTITN3VLREMBAL NUMERIC(15, 3),
  CTITN3VLRUNIT  NUMERIC(15, 3),
  CTITCEMPATE    CHAR(01),
  CTITCVENCEDOR  CHAR(01),
  REGISTRO TIMESTAMP,
  PENDENTE CHAR(1)
);


CREATE INDEX XPENDENTE_CTIT ON COTACAOCOMPRAITEM
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CTIT ON COTACAOCOMPRAITEM
(
       REGISTRO
);
