CREATE TABLE PROSPECTCLIENTE 
(
  PRCLA13ID                  CHAR(13) NOT NULL,
  EMPRICOD                   INTEGER NOT NULL,
  PRCLICOD                   INTEGER,
  PRCLA60RAZAOSOC            CHAR(60),
  PRCLA60ENDCOM              CHAR(60),
  PRCLA60CIDCOM              CHAR(60),
  PRCLA60BAICOM              CHAR(60),
  PRCLA2UFCOM                CHAR(2),
  PRCLA8CEPCOM               CHAR(8),
  PRCLA15FONE1               CHAR(15),
  PRCLA15FONE2               CHAR(15),
  PRCLA15FAX                 CHAR(15),
  PRCLA254EMAIL              VARCHAR(254),
  PRCLA60URL                 CHAR(60),
  PRCLA14CNPJ                CHAR(14),
  PRCLA11CPF                 CHAR(11),
  PRCLA30RG                  CHAR(60),
  PRCLA30IE                  CHAR(30),
  PRCLCFISJUR                CHAR(1),
  PRCLDULTCONT               TIMESTAMP,
  PRCLDPROXCONT              TIMESTAMP,
  PRCLDDTCADASTRO            TIMESTAMP,
  PRCLCSTATUS                CHAR(1),
  PRCLCTURNO                 CHAR(1),
  PRCLA60USUACAD             CHAR(60),
  PRCLA254OBS                VARCHAR(254),
  REGISTRO                   TIMESTAMP,
  PENDENTE                   CHAR(1),
 PRIMARY KEY (PRCLA13ID)
);
