CREATE TABLE COTACAOCOMPRA (
  CTCPA13ID CHAR(13) NOT NULL,
  EMPRICOD INTEGER,
  CTCPICOD INTEGER,
  CTCPDEMIS TIMESTAMP,
  CTCPCSTATUS CHAR(1),
  CTCPN2TOTITENS NUMERIC(15, 3),
  CTCPN3TOTDESC NUMERIC(15, 3),
  REGISTRO TIMESTAMP,
  PENDENTE CHAR(1),
  PRIMARY KEY (CTCPA13ID)
);

CREATE UNIQUE INDEX XPKCOTACAOCOMPRA ON COTACAOCOMPRA
(
       CTCPA13ID
);

CREATE INDEX XPENDENTE_CTCP ON COTACAOCOMPRA
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CTCP ON COTACAOCOMPRA
(
       REGISTRO
);


