CREATE VIEW VIEW_GRADEPRODUTO (
  EMPRICOD, 
  EMPRA60RAZAOSOC, 
  PRODICOD, 
  PRODIAGRUPGRADE, 
  PRODA60CODBAR, 
  PRODA15CODANT, 
  PRODA60REFER, 
  PRODDCAD, 
  PRODDULTALTER, 
  PRODCATIVO, 
  PRODN3PERCIPI, 
  PRODA60DESCR, 
  PRODN3VLRVENDA, 
  PRODN3VLRCOMPRA, 
  PRODN3VLRCOMPRAMED, 
  PRODN3VLRCUSTO, 
  PRODN3VLRCUSTOMED, 
  MARCICOD, 
  MARCA60DESCR, 
  GRUPICOD, 
  GRUPA60DESCR, 
  SUBGICOD, 
  SUBGA60DESCR, 
  VARIICOD, 
  VARIA60DESCR, 
  GRADICOD, 
  GRADA30DESCR, 
  GRTMICOD, 
  GRTMA5DESCR, 
  CORICOD, 
  CORA30DESCR, 
  PSLDN3QTDE, 
  UNIDICOD, 
  UNIDA5DESCR, 
  ICMSICOD
) AS



Select
PRODUTOSALDO.EMPRICOD,
EMPRA60RAZAOSOC,
PRODUTO.PRODICOD,
PRODUTO.PRODIAGRUPGRADE,
PRODUTO.PRODA60CODBAR,
PRODUTO.PRODA15CODANT,
PRODUTO.PRODA60REFER,
PRODUTO.PRODDCAD,
PRODUTO.PRODDULTALTER,
PRODUTO.PRODCATIVO,
PRODUTO.PRODN3PERCIPI,
PRODUTO.PRODA60DESCR,
PRODUTO.PRODN3VLRVENDA,
PRODUTO.PRODN3VLRCOMPRA,
PRODUTO.PRODN3VLRCOMPRAMED,
PRODUTO.PRODN3VLRCUSTO,
PRODUTO.PRODN3VLRCUSTOMED,
PRODUTO.MARCICOD,
MARCA.MARCA60DESCR,
PRODUTO.GRUPICOD,
GRUPO.GRUPA60DESCR,
PRODUTO.SUBGICOD,
SUBGRUPO.SUBGA60DESCR,
PRODUTO.VARIICOD,
VARIACAO.VARIA60DESCR,
PRODUTO.GRADICOD,
GRADE.GRADA30DESCR,
PRODUTO.GRTMICOD,
GRADETAMANHO.GRTMA5DESCR,
PRODUTO.CORICOD,
COR.CORA30DESCR,
PRODUTOSALDO.PSLDN3QTDE,
PRODUTO.UNIDICOD,
UNIDADE.UNIDA5DESCR,
PRODUTO.ICMSICOD
From
PRODUTO
inner join PRODUTOSALDO on PRODUTO.PRODICOD=PRODUTOSALDO.PRODICOD
inner join EMPRESA on PRODUTOSALDO.EMPRICOD=EMPRESA.EMPRICOD
left outer join MARCA on PRODUTO.MARCICOD = MARCA.MARCICOD
left outer join GRUPO on PRODUTO.PRODICOD = GRUPO.GRUPICOD
left join SUBGRUPO on (PRODUTO.PRODICOD = GRUPO.GRUPICOD and PRODUTO.SUBGICOD = SUBGRUPO.SUBGICOD)
left join VARIACAO on (PRODUTO.PRODICOD = GRUPO.GRUPICOD and PRODUTO.SUBGICOD = SUBGRUPO.SUBGICOD and PRODUTO.VARIICOD = VARIACAO.VARIICOD)
left outer join GRADE on PRODUTO.GRADICOD = GRADE.GRADICOD
left outer join GRADETAMANHO on (PRODUTO.GRADICOD = GRADETAMANHO.GRADICOD and PRODUTO.GRTMICOD = GRADETAMANHO.GRTMICOD)
left outer join COR on PRODUTO.CORICOD=COR.CORICOD
left outer join UNIDADE on PRODUTO.UNIDICOD =  UNIDADE.UNIDICOD
;