CREATE TABLE TEF (

TERMICOD	INTEGER NOT NULL,
NUMEICOD	INTEGER NOT NULL,
REDE		VARCHAR(30),
NSU		VARCHAR(60),
VALOR		NUMERIC(15,3),
TEXTO		VARCHAR(1014),
FINALIZACAO	VARCHAR(60),
PRIMARY KEY(TERMICOD,NUMEICOD ));	