CREATE TABLE USUARIOPERMISSOES (
  USPEICOD INTEGER NOT NULL,
  CLASSICOD INTEGER,
  USUAICOD integer,
  USPEA60NOMETELA CHAR(60),
  USPECACESSOTOTAL CHAR(1),
  USPECINCLUSAO CHAR(1),
  USPECALTERACAO CHAR(1),
  USPECEXCLUSAO CHAR(1),
  USPECLEITURA CHAR(1),
  USPEITIPO INTEGER,
  PENDENTE CHAR(1),
  REGISTRO TIMESTAMP,
  PRIMARY KEY (USPEICOD)
);
 CREATE INDEX CLASSICOD ON USUARIOPERMISSOES(CLASSICOD);
 CREATE INDEX USUAICOD ON USUARIOPERMISSOES(USUAICOD);
 CREATE INDEX USPEA60NOMETELA ON USUARIOPERMISSOES(USPEA60NOMETELA);

