CREATE TABLE PRODUTODESCRICAO 
(
  PRODICOD	 INTEGER NOT NULL,
  PRDCIPOSICAO	 INTEGER NOT NULL,
  PRDCA13DOC	 CHAR(13) NOT NULL,
  PRDCA2TIPODOC	 CHAR(2) NOT NULL,
  PRDCA60DESCR	 CHAR(60),
  PENDENTE	 CHAR(1),
  REGISTRO	 TIMESTAMP,
 PRIMARY KEY (PRODICOD, PRDCIPOSICAO, PRDCA13DOC, PRDCA2TIPODOC)
);

CREATE INDEX PENDENTE ON PRODUTODESCRICAO(PENDENTE);
CREATE INDEX REGISTRO ON PRODUTODESCRICAO(REGISTRO);