CREATE TABLE COONS_TABPRECOCOMBUSTIVEL (
    PRODICOD INTEGER NOT NULL,
    PLRCICOD INTEGER NOT NULL,
    VALOR NUMERIC(15,3) NOT NULL,
    REGISTRO DATE,
    PENDENTE CHAR(1),
    PRIMARY KEY(PRODICOD,PLRCICOD))
;


