
CREATE TABLE CHEQUERECEBIDOALTERACAO (
       CTRCA13ID            CHAR(13) NOT NULL,
       CHRAICOD             INTEGER NOT NULL,
       CHRADVENCANT         DATE,
       CHRADVENCNOVO        DATE,
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (CHRAICOD, CTRCA13ID)
);

CREATE UNIQUE INDEX XPKCHEQUERECEBIDOALTERACAO ON CHEQUERECEBIDOALTERACAO
(
       CTRCA13ID,
       CHRAICOD
);

CREATE INDEX XPENDENTE_CHQRECALT ON CHEQUERECEBIDOALTERACAO
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CHQRECALT ON CHEQUERECEBIDOALTERACAO
(
       REGISTRO
);



