
CREATE TABLE CCE (
    NOFIA13ID       VARCHAR(13) NOT NULL,
    CCEINSEQEVENTO  INTEGER NOT NULL,
    CCETXCORRECAO   BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    CCEA1CENVIADO   CHAR(1),
    PRIMARY KEY( NOFIA13ID, CCEINSEQEVENTO )

);
