CREATE TABLE CLIENTERECEITUARIO(
       CLRCICOD	      INTEGER NOT NULL,
       CLIEA13ID	      CHAR(13),
       CLRCDCAD	      TIMESTAMP,
       CLRCDENTREGA	TIMESTAMP,
       CLRCCTIPOOS      CHAR(1),
       CLRCA7LONGODESF	CHAR(7),
       CLRCA7LONGOEESF	CHAR(7),
       CLRCA7LONGODCIL	CHAR(7),
       CLRCA7LONGOECIL	CHAR(7),
       CLRCA7LONGODEIX	CHAR(7),
       CLRCA7LONGOEEIX	CHAR(7),
       CLRCA7LONGODDNP	CHAR(7),
       CLRCA7LONGOEDNP	CHAR(7),
       CLRCA7PERTODESF	CHAR(7),
       CLRCA7PERTOEESF	CHAR(7),
       CLRCA7PERTODCIL	CHAR(7),
       CLRCA7PERTOECIL	CHAR(7),
       CLRCA7PERTODEIX	CHAR(7),
       CLRCA7PERTOEEIX	CHAR(7),
       CLRCA7PERTODDNP	CHAR(7),
       CLRCA7PERTOEDNP	CHAR(7),
       CLRCA7PERTODADI	CHAR(7),
       CLRCA7PERTOEADI	CHAR(7),
       VENDICOD	      INTEGER,
       CLRCA30LENTES	CHAR(30),
       CLRCA30ARMACAO   CHAR(30),
       CLRCA30COR	      CHAR(30),
       CLRCA30ALTURA	CHAR(30),
       CLRCA254SOLICIT	CHAR(254),
       CLRCA254REALIZA	CHAR(254),
       CLRCA15MARCA     CHAR(15),
       CLRCA15CAIXA     CHAR(15),
       CLRCA15PULSEIRA  CHAR(15),
       CLRCA15MOSTRADOR CHAR(15),
       CLRCN3VLRTOTAL	NUMERIC(15,3),
       CLRCN3VLRSINAL   NUMERIC(15,3),
       CLRCN3VLRSALDO   NUMERIC(15,3),
       PENDENTE         CHAR(1),
       REGISTRO         TIMESTAMP,
       PRIMARY KEY (CLRCICOD));

CREATE INDEX XCLIDATA_CLRC ON CLIENTERECEITUARIO
( CLIEA13ID, CLRCDCAD );

CREATE INDEX XPENDENTE_CLRC ON CLIENTERECEITUARIO
( PENDENTE );

CREATE INDEX XREGISTRO_CLRC ON CLIENTERECEITUARIO
( REGISTRO );