CREATE TABLE CONTATO 
(
  EMPRICOD	 INTEGER NOT NULL,
  CONTDCONTATO	 TIMESTAMP NOT NULL,
  CONTICOD	 INTEGER NOT NULL,
  VENDICOD	 INTEGER,
  CLIEA13ID	 CHAR(13),
  TPCLICOD	 INTEGER,
  TPCTICOD	 INTEGER,
  TPRTICOD	 INTEGER,
  TPCTICODPROX	 INTEGER,
  CONTDPROXCONT	 TIMESTAMP,
  CONTDREAL	 TIMESTAMP,
  CONTA255OBS	 CHAR(255),
  CONTA60CONTATO	 CHAR(60),
  USUAICOD	 INTEGER,
  PENDENTE	 CHAR(1),
  REGISTRO	 TIMESTAMP,
 PRIMARY KEY (EMPRICOD, CONTDCONTATO, CONTICOD)
);

/*  Index definitions for CONTATO */

CREATE INDEX XCLIEA13ID_CONT ON CONTATO(CLIEA13ID);
CREATE INDEX XCONTDREAL_CONT ON CONTATO(CONTDREAL);
CREATE INDEX XPENDENTE_CONT ON CONTATO(PENDENTE);
CREATE INDEX XREGISTRO_CONT ON CONTATO(REGISTRO);
CREATE INDEX XTPCLICOD_CONT ON CONTATO(TPCLICOD);
CREATE INDEX XTPCTICOD_CONT ON CONTATO(TPCTICOD);
CREATE INDEX XTPRTICOD_CONT ON CONTATO(TPRTICOD);
CREATE INDEX XVENDICOD_CONT ON CONTATO(VENDICOD);