
CREATE TABLE PERTOCHEK (
  PERA13ID CHAR(13) NOT NULL,
  EMPRICOD INTEGER,
  PERICOD INTEGER,
  PERA30DESCR CHAR(30),
  PERA30MODELO CHAR(30),
  PERA5PORTA   CHAR(05),
  PERA5VELOC   CHAR(05),
  PENDENTE CHAR(1),
  REGISTRO TIMESTAMP
)
