CREATE TABLE LEITURAPISTA 
(
  ABASTECIDA	 INTEGER NOT NULL,
  DATA	 TIMESTAMP NOT NULL,
  CANAL	 CHAR(2) NOT NULL,
  LITROS	 DECIMAL(15,3) NOT NULL,
  VALORTOTAL	 DECIMAL(15,2) NOT NULL,
  VALORUNITARIO	 DECIMAL(15,3) NOT NULL,
  REGISTRO	 INTEGER NOT NULL,
  MARCADO	 CHAR(1),
CONSTRAINT PK_LEITURAPISTA PRIMARY KEY (ABASTECIDA)
);
SET TERM ^ ;


/* Triggers only will work for SQL triggers */

CREATE TRIGGER ABASTECE FOR LEITURAPISTA 
ACTIVE AFTER INSERT POSITION 0
AS
begin
  /* Trigger text */
  post_event 'AUTOMACAO';
end
 ^

COMMIT WORK ^
SET TERM ;^