CREATE TABLE TRANSFERENCIAITEM 
(
  TRITICOD	INTEGER NOT NULL,
  TRFEA13ID	CHAR(13) NOT NULL,
  PRODICOD	INTEGER,
  TRITN3QTDEENVIADA	NUMERIC(15, 3),
  TRITN3QTDERECEBIDA	NUMERIC(15, 3),
  TRITA254DIVERGENCIA	CHAR(254),
  REGISTRO	TIMESTAMP,
  PENDENTE	CHAR(1),
 PRIMARY KEY (TRFEA13ID, TRITICOD)
);