CREATE TABLE FUNCIONARIO (
	FUNCA13ID CHAR(13) NOT NULL,
	EMPRICOD INTEGER,
	TERMICOD INTEGER,
	FUNCICOD INTEGER,
	FUNCA60NOME CHAR(60),
	FUNCCAUTONOMO CHAR(1),
        PENDENTE CHAR(1),
        REGISTRO TIMESTAMP,
	PRIMARY KEY(FUNCA13ID)	
);
	