
CREATE TABLE CHEQUERECEBIDOHISTORICO (
       CTRCA13ID            CHAR(13) NOT NULL,
       CHRHICOD             INTEGER NOT NULL,
       CHRHDDIGITACAO       DATE,
       CHRHA255OBS          CHAR(255),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (CHRHICOD, CTRCA13ID)
);

CREATE UNIQUE INDEX XPKCHEQUERECEBIDOHISTORICO ON CHEQUERECEBIDOHISTORICO
(
       CTRCA13ID,
       CHRHICOD
);

CREATE INDEX XPENDENTE_CHQRECHIS ON CHEQUERECEBIDOHISTORICO
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CHQRECHIS ON CHEQUERECEBIDOHISTORICO
(
       REGISTRO
);



