CREATE TABLE CONFIGFINANCEIRO (
       OPTEICODPAGAR	    INTEGER,
       OPBCICODPAGAR        INTEGER,
       NUMEICODPAGAR        INTEGER,
       CTCRICODPAGAR        INTEGER,
       ALINICODPAGAR        INTEGER,		
       CGFIA254HISTPAGAR    VARCHAR(255),
       OPTEICODRECEBER	    INTEGER,
       OPBCICODRECEBER      INTEGER,
       NUMEICODRECEBER      INTEGER,
       CGFIA254HISTRECEBE   VARCHAR(255),
       ALINICODRECEBER      INTEGER,
       PORTICODRECEBER      INTEGER,
       CGFIUSATESOURARIA    CHAR(1)
);
