/* Table: TIPOTAREFA, Owner: SYSDBA */

CREATE TABLE TIPOTAREFAPROSPECT
(
  TPTAICOD	INTEGER NOT NULL,
  TPTAA30DESCRICAO	          CHAR(30),
  TPTAA13PRAZOMAX                 CHAR(13),
  TIPOTAREFA add TPTAA30DESCRICAO CHAR(30),
  TPTAA1000CHECKLIST              VARCHAR(1000),
  TPTACCHECKLIST                  CHAR(1),
  TPTACINTEXT                     CHAR(1)
 PRIMARY KEY (TPTAICOD)
);
