CREATE TABLE PRODUTOSALDOMES 
(
  EMPRICOD	INTEGER NOT NULL,
  PRODICOD	INTEGER NOT NULL,
  PSMEA2MES	CHAR(2) NOT NULL,
  PSMEA4ANO	CHAR(4) NOT NULL,
  PSMEN3QTDE	NUMERIC(15, 3),
  PSMEN2CUSTO	NUMERIC(15, 2),
  PSMEN2CUSTOMED	NUMERIC(15, 2),
  PSMEN2CUSTOTOT	NUMERIC(15, 2),
  PSMEN2CUSTOMEDTOT	NUMERIC(15, 2),
  PSMEN2COMPRA    NUMERIC(15, 2),
  PSMEN2COMPRATOT NUMERIC(15, 2),
  PSMEN2COMPRAMED NUMERIC(15, 2),
  PSMEN2COMPRAMEDTOT NUMERIC(15, 2),
  PENDENTE	CHAR(1),
  REGISTRO	TIMESTAMP,
 PRIMARY KEY (EMPRICOD, PRODICOD, PSMEA2MES, PSMEA4ANO)
);
