CREATE TABLE FORNECEDORCONTATO (
  FORNICOD INTEGER NOT NULL,
  FOCOICOD INTEGER NOT NULL,
  FOCOA60NOME CHAR(60),
  FOCOA15FONE CHAR(15),
  FOCOA15CELULAR CHAR(30),
  FOCOA60EMAIL CHAR(30),
  PENDENTE CHAR(1),
  REGISTRO TIMESTAMP,
  FOCOCENVIAMALA CHAR(1),
  FOCOA254OBS CHAR(254),
  FOCOA60DEPTO CHAR(60),
  FOCOA60SETOR CHAR(60)
)	