CREATE TABLE TABELAFRETEFAIXAVLR 
(
  TBFTICOD                   INTEGER NOT NULL,
  TBFCICOD                   INTEGER NOT NULL,
  TFFVICOD                   INTEGER NOT NULL,
  TFFVN2PESOMIN              NUMERIC(15, 2),
  TFFVN2PESOMAX              NUMERIC(15, 2),
  TFFVN2PESOVLR              NUMERIC(15, 2),
 PRIMARY KEY (TBFTICOD, TBFCICOD, TFFVICOD)
);
