CREATE TABLE INVENTARIOESTOQUE (
       EMPRICOD             INTEGER NOT NULL,
       TERMICOD             INTEGER NOT NULL,
       PRODICOD             INTEGER NOT NULL,
       INVDDATA             DATE NOT NULL,
       INVIPRODPOS          INTEGER NOT NULL,
       INVICONTAGEM1        NUMERIC(15,3),
       INVICONTAGEM2        NUMERIC(15,3),
       INVICONTAGEM3        NUMERIC(15,3),
       PENDENTE             CHAR(1),
       REGISTRO             TIMESTAMP,
       PRIMARY KEY (EMPRICOD, TERMICOD, PRODICOD, INVDDATA,INVIPRODPOS)
);
