CREATE TABLE LMCENTRADA
(
EMPRICOD        INTEGER NOT NULL,
LILMICOD        INTEGER NOT NULL,
LMENIPAGATUAL   INTEGER NOT NULL,
LMENA15NRONF    CHAR(15) NOT NULL,
LMENDDTMOV      DATE,
PRODICOD        INTEGER,
LMENDDTNF       DATE,
TANQICOD        INTEGER,
LMENN2QTE       NUMERIC(15,2),
PENDENTE        CHAR(01),
REGISTRO        DATE,  
PRIMARY KEY(EMPRICOD, LILMICOD, LMENIPAGATUAL, LMENA15NRONF));