CREATE TABLE PRODUTOSERIE
(
PRODICOD		INTEGER NOT NULL,
PRSEA60NROSERIE		CHAR(60) NOT NULL,
PRSECSTATUS		CHAR(1),
EMPRICOD		INTEGER,
EMPRICODDEST		INTEGER,
FORNICOD		INTEGER,
CLIEA13ID		CHAR(13),
NOCPA13ID		CHAR(13),
NOFIA13ID		CHAR(13),
CUPOA13ID		CHAR(13),
PDVDA13ID		CHAR(13),
OSA13ID			CHAR(13),
MOVDA13ID		CHAR(13),
PENDENTE		CHAR(1),
REGISTRO		DATE,
PRIMARY KEY(PRODICOD, PRSEA60NROSERIE)
);