CREATE TABLE FRETESEGURO (
    FRETA13ID         CHAR(13) NOT NULL,
    FRETICOD          INTEGER NOT NULL,
    FRSGA1RESPONSAVEL CHAR(1) NOT NULL,
    FRSGA60SEGURADORA VARCHAR(60),
    FRSGA20APOLICE    VARCHAR(20),
    FRSGA20AVERBACAO  VARCHAR(20),
    FRSGN2VALORAVERBA NUMERIC(15,2),
    PRIMARY KEY (FRETA13ID, FRETICOD)	
);
