CREATE TABLE COONS_CLIQUOTAS (
    CLIEA13ID CHAR(13) NOT NULL,
    QUOTAS INTEGER NOT NULL,
    VALORUTILIZADO NUMERIC(15,2),
    REGISTRO DATE,
    PENDENTE CHAR(1),
    PRIMARY KEY (CLIEA13ID)
    
);
