CREATE TABLE RAMO
(
RAMOICOD        INTEGER NOT NULL,
RAMOA30DESCR    CHAR(30),
PENDENTE        CHAR(01),
REGISTRO        TIMESTAMP);

CREATE TABLE SUBRAMO
(
  RAMOICOD INTEGER NOT NULL,
  SRAMICOD INTEGER NOT NULL,
  SRAMA30DESCR CHAR(30),
  PENDENTE CHAR(01),
  REGISTRO TIMESTAMP
);

ALTER TABLE CLIENTE ADD RAMOICOD INTEGER;
ALTER TABLE CLIENTE ADD SRAMICOD INTEGER;

ALTER TABLE FORNECEDOR ADD RAMOICOD INTEGER;
ALTER TABLE FORNECEDOR ADD SRAMICOD INTEGER;