CREATE TABLE REMESSABANCOCONTASRECEBER (
       RMBCICOD             INTEGER NOT NULL,
       CTRCA13ID            CHAR(13) NOT NULL,
       REGISTRO             DATE,
       PENDENTE             CHAR(1),
       PRIMARY KEY (RMBCICOD,CTRCA13ID)
);
