CREATE TABLE CONFIGREMESSABANCO(
 	CFRBA13ID 		CHAR(13) NOT NULL,
	EMPRICOD		INTEGER,
	CFRBICOD		INTEGER NOT NULL,
	CFRBA60DESCR		CHAR(60),
	CFRBA20CODEMPRESA	CHAR(20),
	CFRBA30NOMEMPRESA	CHAR(30),
	CFRBA2CODCARTEIRA 	CHAR(2),
	CFRBA4CODAGENCIA	CHAR(4),
	CFRBA6CONTACORRE	CHAR(6),
	CFRBA1DIGCONTA		CHAR(1),
	CFRBA1RATEIOCRED	CHAR(1),
	BANCA5COD 		CHAR(5),  	
	CFRBTPATH		VARCHAR(500),
	PENDENTE		CHAR(1),
	REGISTRO		DATE,
	PRIMARY KEY (CFRBA13ID,CFRBICOD)
);
