CREATE TABLE PROFISSIONAL (
	PROFA13ID CHAR(13) NOT NULL,
	EMPRICOD INTEGER,
	PROFICOD INTEGER NOT NULL,
	PROFA60NOME CHAR(60),
	PROFA15FONE1 CHAR(15),
	PROFA15FONE2 CHAR(15),
      	PROFA60CATEG CHAR(60),
	PROFA200OBS CHAR(200),
        PENDENTE CHAR(1),
        REGISTRO TIMESTAMP,
	PRIMARY KEY(PROFA13ID)	
);
	