
CREATE TABLE VEICULOSCLIENTE (
    VICLICODVEICULO       INTEGER     NOT NULL,
    VICLA15PLACA          VARCHAR(15) NOT NULL,
    CLIEA13ID             CHAR(13)    NOT NULL,
    VICLA40MODELO         VARCHAR(40),
    VOCLA20ESPECIE        VARCHAR(20),
    VICLA1ATIVO           VARCHAR(1),
    VICLDDATAINC          DATE,
    VICLA10FROTA          VARCHAR(10),
    VICLA15COR            VARCHAR(15),
    VICLA1COMBUSTIVEL     VARCHAR(1),
    VICLA25MARCA          VARCHAR(25),
    VICLIPLRCPREFERENCIAL INTEGER,
    VICLN2KMATUAL         NUMERIC(15,2),
    VICLA9ANOMODELO       VARCHAR(9),
    REGISTRO              DATE,
    PENDENTE              CHAR(1),
    VEICA60PLRCOPCIONAIS VARCHAR(60),
    PRIMARY KEY ( VICLICODVEICULO )       
);


