CREATE TABLE VEICULO (
	VEICA13ID CHAR(13) NOT NULL,
	EMPRICOD INTEGER,
	TERMICOD INTEGER,
	VEICICOD INTEGER,
	VEICA7PLACA CHAR(7),
	VEICA2UFPLACA CHAR(2),
	VEICA60DESCR CHAR(60),
	VEICA3OMARCA CHAR(30),
	VEICA3OMOTORISTA CHAR(30),
	VEICA3OMOTOCPF CHAR(14),
	VEICN3PESOSUPORTA NUMERIC(15,3),
      TRANICOD INTEGER,
      PENDENTE CHAR(1),
      REGISTRO TIMESTAMP,
	PRIMARY KEY(VEICA13ID)	
);
	