
CREATE TABLE REDUCAOZDIAFORMA (
       REDUA13ID            CHAR(13) NOT NULL, 
       NUMEICOD             INTEGER NOT NULL,
       REFON3VLR            NUMERIC(15,3),
       PRIMARY KEY (REDUA13ID,NUMEICOD)
);

