
CREATE TABLE MOVIMENTOBANCO (
       MVBCA13ID            CHAR(13) NOT NULL,
       EMPRICOD             INTEGER NOT NULL,
       MVBCICOD             INTEGER NOT NULL,
       MVBCDLANC            DATE,
       BANCA5COD            CHAR(5),
       CTCRICOD             INTEGER,
       MVBCA6NROCHQ         CHAR(6),
       MVBCN2VLRDEB         NUMERIC(15,3),
       MVBCN2VLRCRED        NUMERIC(15,3),
       MVBCDCHQBOMPARA      DATE,
       MVBCDCHQBAIXA        DATE,
       MVBCA254HIST         CHAR(254),
       MVBCA60FAVORECIDO    CHAR(60),
       OPBCICOD             INTEGER,
       MVBCCALTSALD         CHAR(1),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (MVBCA13ID)
);

CREATE UNIQUE INDEX XPKMOVIMENTOBANCO ON MOVIMENTOBANCO
(MVBCA13ID);

CREATE INDEX XPENDENTE_MOVBCO ON MOVIMENTOBANCO
(PENDENTE);

CREATE INDEX XREGISTRO_MOVBCO ON MOVIMENTOBANCO
(REGISTRO);



