CREATE TABLE TABELAPRECOPRODUTO (
       TPRCICOD             INTEGER NOT NULL,
       PRODICOD             INTEGER NOT NULL,
       TPCPN3VLRVENDA       NUMERIC(15,3),
       TPCPN3MARGLUCR       NUMERIC(15,3),
       TPCPN3VLRVENDAPROM   NUMERIC(15,3),
       TPCPDINIPROMO        DATE,
       TPCPDFIMPROMO        DATE,
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (TPRCICOD,PRODICOD)
);

CREATE UNIQUE INDEX XPKTABELAPRECOPRODUTO ON TABELAPRECOPRODUTO
(
       TPRCICOD,
       PRODICOD
);	