
CREATE TABLE TESOURARIA (
	TESOA13ID 		CHAR(13) NOT NULL,
	EMPRICOD		INTEGER NOT NULL,
	TERMICOD 		INTEGER NOT NULL,
	TESOICOD		INTEGER NOT NULL,
	TESODMOV		DATE,
	TESON2VLRDEBITO 	NUMERIC(15,3),
	TESON2VLRCREDITO	NUMERIC(15,3),
	NUMEICOD		INTEGER,
	OPTEICOD		INTEGER,
	TESOA255HIST		VARCHAR(255),
	CTRCA13ID		CHAR(13),
	CTPGA13ID		CHAR(13),
	CQEMA13ID		CHAR(13),
	FECXA13ID		CHAR(13),
	USUAICOD		INTEGER,
	PENDENTE		CHAR(1),
	REGISTRO		DATE,
       PRIMARY KEY (TESOA13ID,EMPRICOD,TERMICOD,TESOICOD)
);

