CREATE TABLE COTACAOMOEDA (
CTMOICOD     INTEGER NOT NULL,
CTMODDIA     DATE,
CTMOA5MOEDA  CHAR(5),
CTMON3VLRDIA NUMERIC(15,3),
CTMOA60FONTE CHAR(60),
PENDENTE     CHAR(1),
REGISTRO     DATE,	
PRIMARY KEY(CTMOICOD));