
/* Table: TIPORETORNO, Owner: SYSDBA */

CREATE TABLE TIPORETCALLCENTER
(
  TPRTICOD	 INTEGER NOT NULL,
  TPRTA60DESCR	 CHAR(60),
  TPCTICOD	 INTEGER,
  PENDENTE	 CHAR(1),
  REGISTRO	 TIMESTAMP,
  TPRTA254OBSPADRAO	 CHAR(254),
 PRIMARY KEY (TPRTICOD)
);