CREATE TABLE CLIENTEHISTORICO (
CLIEA13ID		CHAR(13) NOT NULL,
CLHTICOD		INTEGER NOT NULL,
CLHTDEMIS		DATE,
CLHTTHISTORICO		VARCHAR(500),
CUPOA13ID		CHAR(13),
CTRCA13ID		CHAR(13),
CTRCINROPARC		INTEGER,
CLHTDPROXCONTATO	DATE,
PENDENTE		CHAR(1),
REGISTRO		DATE,
PRIMARY KEY(CLIEA13ID, CLHTICOD)); 