CREATE TABLE KMDIA (
  KMDIA13ID CHAR(13) NOT NULL,
  EMPRICOD INTEGER NOT NULL,
  KMDIICOD INTEGER NOT NULL,
  KMDIDDATA TIMESTAMP,
  KMDICSTATUS CHAR(1),
  FUNCA13ID CHAR(13),
  KMDIIINICIAL INTEGER,
  KMDIIFINAL INTEGER,
  REGISTRO TIMESTAMP,
  PENDENTE CHAR(1)
)