CREATE TABLE CONVERTECSTIPI (CSTSAIDA VARCHAR(3) NOT NULL,CSTENTRADA VARCHAR(3) NOT NULL,PRIMARY KEY(CSTSAIDA));
insert into CONVERTECSTIPI(CSTENTRADA,CSTSAIDA) VALUES('00','50');
insert into CONVERTECSTIPI(CSTENTRADA,CSTSAIDA) VALUES('01','51');
insert into CONVERTECSTIPI(CSTENTRADA,CSTSAIDA) VALUES('02','52');
insert into CONVERTECSTIPI(CSTENTRADA,CSTSAIDA) VALUES('03','53');
insert into CONVERTECSTIPI(CSTENTRADA,CSTSAIDA) VALUES('04','54');
insert into CONVERTECSTIPI(CSTENTRADA,CSTSAIDA) VALUES('05','55');
insert into CONVERTECSTIPI(CSTENTRADA,CSTSAIDA) VALUES('49','99');