
CREATE TABLE PRODUTOORDEMPESQUISA (
       PDOPIORDEM           INTEGER NOT NULL,
       PDOPA30CAMPO         CHAR(30),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (PDOPIORDEM)
);

CREATE UNIQUE INDEX XPKPRODUTOORDEMPESQUISA ON PRODUTOORDEMPESQUISA
(
       PDOPIORDEM
);