CREATE TABLE FUNCIONARIOCONTACORRENTE (
	FUNCA13ID CHAR(13) NOT NULL,
	FUCCICOD INTEGER NOT NULL,
	FUCCN2VLRDEBITO NUMERIC(15,3),
        FUCCN2VLRCREDITO NUMERIC(15,3),
	OPFUICOD INTEGER,
        PENDENTE CHAR(1),
        REGISTRO TIMESTAMP,
	PRIMARY KEY(FUNCA13ID,FUCCICOD)	
);
	