CREATE TABLE PROVEDORCARTAO (
	PRCAA13ID	CHAR(13) NOT NULL,
	EMPRICOD	INTEGER,         
	PRCAICOD	INTEGER NOT NULL,
	PRCAA60DESCR	CHAR(60),
	PRCATPATHENVIA	VARCHAR(500),
	PRCATPATHRECEBE	VARCHAR(500),
	PRCAA60CARTAO	CHAR(60),
	PENDENTE	CHAR(1),
        REGISTRO	DATE,
	PRIMARY KEY(PRCAA13ID,PRCAICOD)
);
