
CREATE TABLE CONFIGBALANCA (
       CFBLICOD             INTEGER NOT NULL,
       CFBLA60DESCR         CHAR(60),
       CFBLIDECIMAIS        INTEGER,
       CFBLCUSASEPAR        CHAR(1),
       CFBLA1TIPOSEPAR      CHAR(1),
       CFBLA254NOMEARQTXT   CHAR(254),
       CFBLA10BALID         CHAR(10),
       CFBLIBALIDPOS        INTEGER,
       CFBLIBALIDTAM        INTEGER,
       CFBLIBALCODPOS       INTEGER,
       CFBLIBALCODTAM       INTEGER,
       CFBLIVLRPOS          INTEGER,
       CFBLIVLRTAM          INTEGER,
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (CFBLICOD)
);

CREATE UNIQUE INDEX XPKCONFIGBALANCA ON CONFIGBALANCA
(
       CFBLICOD
);



