CREATE TABLE ENCERRANTEDIARIO 
(
  ENDIA13ID     CHAR(13) NOT NULL,
  EMPRICOD      INTEGER,
  ENDIICOD      INTEGER NOT NULL,
  ENDIDDATA     TIMESTAMP,
  USUAICOD      INTEGER,
  BOMBICOD      INTEGER,
  PRODICOD      INTEGER,
  ENDIN2ENCERINI NUMERIC (15, 2),
  ENDIN2ENCERFIM NUMERIC (15, 2),
  ENDIN2AFERICAO NUMERIC (8, 2),
  REGISTRO      TIMESTAMP,
  PENDENTE      CHAR(01)
);