CREATE TABLE TANQUE
(
EMPRICOD        INTEGER NOT NULL,
TANQICOD        INTEGER NOT NULL,
TANQA30DESCR    CHAR(30),
PRODICOD        INTEGER, 
TANQN2CAPACID   NUMERIC(15,2), 
TANQN2SALDO     NUMERIC(15,2), 
TANQN2ESTMIN    NUMERIC(15,2), 
PENDENTE        CHAR(01),
REGISTRO        DATE,  
PRIMARY KEY(EMPRICOD, TANQICOD));