CREATE TABLE EMPRESACUSTO
(
EMPRICOD 	INTEGER NOT NULL,
EMCTICOD	INTEGER NOT NULL,
EMCTA2MES	CHAR(2),
EMCTA4ANO	CHAR(4),
EMCTA60DESCR	CHAR(60),
EMCTCFIXOVARIA  CHAR(1),
EMCTN2VALOR	NUMERIC(15,2),
EMCTN2PERC	NUMERIC(15,2),
PRIMARY KEY (EMPRICOD,EMCTICOD)
); 