CREATE TABLE EMAIL (
  MAILICOD INTEGER NOT NULL,
  MAILTREMETENTE CHAR(255),
  MAILTDESTINO CHAR(255),
  MAILTASSUNTO CHAR(255),
  MAILTMENSAGEM VARCHAR(10000),
  MAILDDATA TIMESTAMP,
  MAILTPATHANEXO CHAR(255),
  MAILCSTATUS CHAR(1)
)