CREATE TABLE CLASSE (
       CLASSICOD            INTEGER NOT NULL,
       CLASSA60DESCRICAO    CHAR(60),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (CLASSICOD)
);

CREATE INDEX XPENDENTE_CLASSE ON CLASSE
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CLASSE ON CLASSE
(
       REGISTRO
);


CREATE TABLE CLASSEMODULO (
       CLASSICOD            INTEGER NOT NULL,
       CLMDA60NOME          CHAR(60) NOT NULL,
       CLMDITIPO            INTEGER,
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (CLASSICOD, CLMDA60NOME)
);

CREATE UNIQUE INDEX XPKCLASSEMODULO ON CLASSEMODULO
(
       CLASSICOD,
       CLMDA60NOME
);

CREATE INDEX XPENDENTE_CLASMOD ON CLASSEMODULO
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CLASMOD ON CLASSEMODULO
(
       REGISTRO
);


CREATE TABLE CLASSETABELA (
       CLASSICOD            INTEGER NOT NULL,
       CLASSA18TABELA       CHAR(18) NOT NULL,
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (CLASSICOD, CLASSA18TABELA)
);

CREATE UNIQUE INDEX XCLASSETABELA ON CLASSETABELA
(
       CLASSICOD,
       CLASSA18TABELA
);

CREATE INDEX XPENDENTE_CLASTAB ON CLASSETABELA
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CLASTAB ON CLASSETABELA
(
       REGISTRO
);


CREATE TABLE CLASSEUSUARIO (
       CLASSICOD            INTEGER NOT NULL,
       USUAICOD             INTEGER NOT NULL,
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (CLASSICOD, USUAICOD)
);

CREATE UNIQUE INDEX XPKCLASSEUSUARIO ON CLASSEUSUARIO
(
       CLASSICOD,
       USUAICOD
);

CREATE INDEX XPENDENTE_CLASUSU ON CLASSEUSUARIO
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CLASUSU ON CLASSEUSUARIO
(
       REGISTRO
);



