create table PEDVENDITEMCOMP
(
PDVDA13ID 	CHAR(13) NOT NULL,
PVITIITEM 	INTEGER  NOT NULL,
PVCOICOD	INTEGER  NOT NULL,
PRODICOD 	INTEGER,
PRODICODFILHO 	INTEGER,
PVCON3QUANT 	NUMERIC(15,3),
PVCON2VLRUNIT 	NUMERIC(15,2),
PVCON2PERCDESC 	NUMERIC(15,2),
PVCON2VLRDESC 	NUMERIC(15,2),
PVCOA254OBS 	CHAR(254),
REGISTRO 	TIMESTAMP,
PENDENTE 	CHAR(1),
PRIMARY KEY (PDVDA13ID,PVITIITEM, PVCOICOD));