CREATE TABLE TIPOCONTATO 
(
  TPCTICOD	 INTEGER NOT NULL,
  TPCTA60DESCR	 CHAR(60),
  QUESICOD	 INTEGER,
  TPRTICOD	 INTEGER,
  TPCTA254OBSPADRAO	 CHAR(254),
  PENDENTE	 CHAR(1),
  REGISTRO	 TIMESTAMP,
 PRIMARY KEY (TPCTICOD)
);

/*  Index definitions for TIPOCONTATO */

CREATE INDEX XPENDENTE_TPCT ON TIPOCONTATO(PENDENTE);
CREATE INDEX XREGISTRO_TPCT ON TIPOCONTATO(REGISTRO);