CREATE TABLE COTACAOCOMPRAITEM (
  CTCPA13ID CHAR(13) NOT NULL,
  CTITIPOS INTEGER NOT NULL,
  PRODICOD INTEGER,
  CTITN3CAPEMBAL NUMERIC(15, 3),
  CTITN3QTDEMBAL NUMERIC(15, 3),
  CTITN3VLREMBAL NUMERIC(15, 3),
  CTITN3VLRUNIT  NUMERIC(15, 3),
  REGISTRO TIMESTAMP,
  PENDENTE CHAR(1)
);


CREATE INDEX XPENDENTE_CTIT ON COTACAOCOMPRAITEM
(
       PENDENTE
);

CREATE INDEX XREGISTRO_CTIT ON COTACAOCOMPRAITEM
(
       REGISTRO
);
