CREATE TABLE CONTATODETALHE 
(
  EMPRICOD	 INTEGER NOT NULL,
  CONTDCONTATO	 TIMESTAMP NOT NULL,
  CONTICOD	 INTEGER NOT NULL,
  CNTDICOD	 INTEGER NOT NULL,
  CNTDA254DETALHE	 CHAR(254),
  PENDENTE	 CHAR(1),
  REGISTRO	 TIMESTAMP,
 PRIMARY KEY (EMPRICOD, CONTDCONTATO, CONTICOD, CNTDICOD)
);

/*  Index definitions for CONTATODETALHE */

CREATE INDEX XPENDENTE_CONTDET ON CONTATODETALHE(PENDENTE);
CREATE INDEX XREGISTRO_CONTDET ON CONTATODETALHE(REGISTRO);