CREATE TABLE TELEENTREGA (
       TELEA13ID	    CHAR(13) NOT NULL,
       EMPRICOD		    INTEGER NOT NULL,	
       TERMICOD		    INTEGER NOT NULL,	
       TELEICOD		    INTEGER NOT NULL,
       CUPOA13ID            CHAR(13),
       NOFIA13ID	    CHAR(13),		
       PDVDA13ID	    CHAR(13),
       TELEDENTRPREV        DATE,
       TELEDENTRPREV1       DATE,
       TELEDENTRPREV2       DATE,
       TELEDENTRREAL        DATE,
       TELEA60SOLICITANTE   CHAR(60),
       TELEA60ENTRPARANOME  CHAR(60),
       TELEA60ENTRPARAEND   CHAR(60),
       TELEA60ENTRPARABAI   CHAR(60),
       TELEA60ENTRPARACID   CHAR(60),
       TELEA2ENTRPARAUF     CHAR(2),
       TELEA15ENTRPARAFONE  CHAR(15),
       TELEA60RECPORNOME    CHAR(60),
       TELEADREC            DATE,
       TELEA1016MENSG       CHAR(1016),
       TPVDICOD             INTEGER,
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (TELEA13ID)
);

CREATE INDEX XPENDENTE_TELEENTREGA ON TELEENTREGA
(
       PENDENTE
);

CREATE INDEX XREGISTRO_TELEENTREGA ON TELEENTREGA
(
       REGISTRO
);