CREATE TABLE CONFIGIMPRESSAOPAPEL (
  CFIMIID INTEGER NOT NULL,
  CFIPILININICAB INTEGER,

  CFIPILININIFINAN INTEGER,
  CFIPILINFINFINAN INTEGER,
  CFIPICOLINIFINAN INTEGER,
  CFIPICOLFINFINAN INTEGER,

  CFIPILININIITENS INTEGER,
  CFIPILINFINITENS INTEGER,
  CFIPICOLINIITENS INTEGER,
  CFIPICOLFINITENS INTEGER,

  CFIPILININISERV INTEGER,
  CFIPILINFINSERV INTEGER, 
  CFIPICOLINISERV INTEGER,
  CFIPICOLFINSERV INTEGER, 

  CFIPICOLINIRODAPE INTEGER,
  CFIPILININIRODAPE INTEGER,

  CFIPCDIRECAO CHAR(1),
  CFIPA13COMPRESSAO CHAR(13),
  CFIPITOTALLINHAS INTEGER,
  CFIPITOTALCOLUNAS INTEGER
)