
CREATE TABLE PEDIDOVENDAITEM (
       PDVDA13ID            CHAR(13) NOT NULL,
       PVITIITEM            INTEGER NOT NULL,
       PRODICOD             INTEGER NOT NULL,
       PVITN3QUANT          NUMERIC(15,3),
       PVITN2VLRUNIT        NUMERIC(15,3),
       PVITN2PERCDESC       NUMERIC(15,3),
       PVITN2VLRDESC        NUMERIC(15,3),
       REGISTRO             DATE,
       PENDENTE             CHAR(1),
       PRIMARY KEY (PDVDA13ID, PVITIITEM)
);

CREATE UNIQUE INDEX XPKPEDIDOVENDAITEM ON PEDIDOVENDAITEM
(
       PDVDA13ID,
       PVITIITEM
);

CREATE INDEX XPENDENTE_PDVDIT ON PEDIDOVENDAITEM
(
       PENDENTE
);

CREATE INDEX XREGISTRO_PDVDIT ON PEDIDOVENDAITEM
(
       REGISTRO
);



