CREATE TABLE REMESSABANCO (  
  RMBCA13ID CHAR(13) NOT NULL,
  EMPRICOD INTEGER,
  BANCA5COD CHAR(5) NOT NULL,
  RMBCICOD INTEGER NOT NULL,    
  RMBCDEMIS TIMESTAMP,
  CFRBA13ID CHAR(13),
  RMBCA2IDOCORRENCIA CHAR(2),
  RMBCA12PRIMSG CHAR(12),
  RMBCA60SEGMSG CHAR(60),
  RMBCA2PRIINSTRUCAO CHAR(2),
  RMBCA2SEGINSTRUCAO CHAR(2),
  RMBCN2VLRDIAATRASO NUMERIC(15, 2),
  RMBCDLIMDESCONTO TIMESTAMP,
  RMBCN2VLRDESCONTO NUMERIC(15, 2),  
  REGISTRO TIMESTAMP,
  PENDENTE CHAR(1),
  PRIMARY KEY(RMBCA13ID,RMBCICOD,BANCA5COD)
);