CREATE TABLE PRODUTOSALDODIA (
       EMPRICOD             INTEGER NOT NULL,
       PRODICOD             INTEGER NOT NULL,
       PSDIDDATA            DATE NOT NULL,
       PSDIN3QTDE           NUMERIC(15,3),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (EMPRICOD, PRODICOD, PSDIDDATA)
);

CREATE INDEX XPENDENTE_PRODSLDIA ON PRODUTOSALDODIA(PENDENTE);
CREATE INDEX XREGISTRO_PRODSLDIA ON PRODUTOSALDODIA(REGISTRO);