
CREATE TABLE OPERACAOBANCO (
       OPBCICOD             INTEGER NOT NULL,
       MVBCDLANC            DATE,
       OPBCA60DESCR         CHAR(60),
       OPBCCTIPO            CHAR(1),
       OPBCCALTSALDO        CHAR(1),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (OPBCICOD)
);

CREATE UNIQUE INDEX XPKOPERACAOBANCO ON OPERACAOBANCO
(MVBCA13ID);

CREATE INDEX XPENDENTE_OPBCO ON OPERACAOBANCO
(PENDENTE);

CREATE INDEX XREGISTRO_OPBCO ON OPERACAOBANCO
(REGISTRO);



