CREATE TABLE ICMSUF (
    ICMUA2UF               CHAR(2) NOT NULL,
    TIPOPESSOA             CHAR(1) NOT NULL,
    ENQUADRAMENTO          CHAR(1) NOT NULL,
    PRODICOD               INTEGER NOT NULL,
    NCMA30CODIGO           VARCHAR(30) NOT NULL,
    ICMUN2ALIQUOTA         NUMERIC(15,3),
    ICMSN2PERCSUBSTSAI     NUMERIC(15,3),
    PENDENTE               CHAR(1),
    REGISTRO               DATE,
    ICMUA30NOMEESTADO      CHAR(30),
    ICMUA60DESCR           CHAR(60),
    ICMUICOD               INTEGER,
    ICMUISITTRIB           INTEGER,
    ICMUN3MVA              NUMERIC(15,3),
    ICMUN3REDBASECALC      NUMERIC(15,3),
    ICMUISITTRIBJURIDICA   INTEGER,
    ICMUN2ALIQUOTAINTERNA  NUMERIC(15,2),
    PRIMARY KEY (ICMUA2UF, TIPOPESSOA, ENQUADRAMENTO, PRODICOD, NCMA30CODIGO));


