CREATE TABLE ACUMULADOR
(
ACUMICOD        INTEGER NOT NULL,
ACUMA60DESCR    CHAR(60),
ACUMICODASSOC   INTEGER,
ACUMCICMS	CHAR(1),
ACUMCIPI	CHAR(1),
ACUMCISSQN	CHAR(1),
PRIMARY KEY(ACUMICOD) );

CREATE INDEX ACUMICODASSOC ON ACUMULADOR(ACUMICODASSOC);