CREATE TABLE CONFIGCOLETOR (
	CFCOA13ID CHAR(13) NOT NULL,
	CFCOICOD INTEGER NOT NULL,
	EMPRICOD INTEGER,
	TERMICOD INTEGER,
	CFCOA60DESCR CHAR(60),
	CFCOTPATHFILE VARCHAR(255),
	CFCOIPOSPRODICOD INTEGER,
	CFCOITAMPRODICOD INTEGER,
        CFCOIPOSPRODN3QTDE INTEGER,
	CFCOITAMPRODN3QTDE INTEGER,
        REGISTRO             DATE,
        PENDENTE             CHAR(1),
	PRIMARY KEY (CFCOA13ID,CFCOICOD)
);
