alter table CLIENTE DROP CLIEA30TEMPOMORADIA;
alter table CLIENTE DROP CLIECCASAPROPRIA;
alter table CLIENTE DROP CLIEA60IMOB;
alter table CLIENTE DROP CLIEN2VLRALUGUEL;
alter table CLIENTE DROP CLIEA30MODVEICULO;
alter table CLIENTE DROP CLIEA8PLACAVEICULO;
alter table CLIENTE DROP CLIEA4ANOVEICULO;
alter table CLIENTE DROP CLIEA30LOCALIMOV1;
alter table CLIENTE DROP CLIEA30LOCALIMOV2;
alter table CLIENTE DROP CLIEA30TIPOIMOV1;
alter table CLIENTE DROP CLIEA30TIPOIMOV2;
alter table CLIENTE DROP CLIECSTATUSIMOV1;
alter table CLIENTE DROP CLIECSTATUSIMOV2;


