ALTER TABLE PRODUTO DROP PRODN2PERCDESC1;
ALTER TABLE PRODUTO DROP PRODN2PERCDESC2;
ALTER TABLE PRODUTO DROP PRODN2PERCDESC3;
ALTER TABLE PRODUTO DROP PRODN2PERCDESC4;
ALTER TABLE PRODUTO DROP PRODN2PERCDESC5;
ALTER TABLE PRODUTO DROP PRODN2PERCAUME1;
ALTER TABLE PRODUTO DROP PRODN2PERCAUME2;
ALTER TABLE PRODUTO DROP PRODN2PERCAUME3;
ALTER TABLE PRODUTO DROP PRODN2PERCAUME4;
ALTER TABLE PRODUTO DROP PRODN2PERCAUME5;


