ALTER TABLE PEDIDOVENDA DROP PDVDDVALIDADE ;
ALTER TABLE PEDIDOVENDA DROP PDVDCTIPOENVIO ;
ALTER TABLE PEDIDOVENDA DROP CLCOICOD  ;
ALTER TABLE PEDIDOVENDA DROP PDVDDRECBTO ;
ALTER TABLE PEDIDOVENDA DROP PDVDDACEITE ;
ALTER TABLE PEDIDOVENDA DROP MTCAICOD ;
