unit DataModulo;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  BDE, VarSYS, DataModuloTemplate, Db, DBTables, RxQuery, MemTable, DBLists,
  UCrpe32, ppComm, ppRelatv, ppDB, ppDBPipe, ppDBBDE, ppProd, ppClass, UnitLibrary,
  ppReport, ppBands, ppCache, ppPrnabl, ppCtrls, ppStrtch, ppMemo, Serial,
  ExtCtrls, IBDatabase, IBCustomDataSet, IBQuery, IBUpdateSQL,  Inifiles,
  IBEvents, IBSQL, IdComponent, IdTCPConnection, IdTCPClient,
  IdMessageClient, IdSMTP, IdBaseComponent, IdMessage, DBXpress, SqlExpr,
  ZConnection, ZAbstractRODataset, ZAbstractDataset, ZDataset, ACBrBase,
  ACBrBAL;

type
  TDM = class(TDMTemplate)
    SQLUsuario: TRxQuery;
    SQLUsuarioUSUAICOD: TIntegerField;
    SQLUsuarioUSUAA60LOGIN: TStringField;
    SQLUsuarioUSUAA5SENHA: TStringField;
    SQLTerminalAtivo: TRxQuery;
    SQLTerminalAtivoTERMICOD: TIntegerField;
    SQLTerminalAtivoTERMCTIPO: TStringField;
    SQLTerminalAtivoTERMCSTATUSCAIXA: TStringField;
    SQLTerminalAtivoTERMDSTATUSCAIXA: TDateTimeField;
    SQLTerminalAtivoTERMA60DESCR: TStringField;
    SQLExtratoProduto: TRxQuery;
    SQLTerminalAtivoCLIEA13ID: TStringField;
    SQLTerminalAtivoVENDICOD: TIntegerField;
    SQLTerminalAtivoPLRCICOD: TIntegerField;
    SQLTerminalAtivoTERMCMOVESTOQUE: TStringField;
    SQLTerminalAtivoTERMCUSAVENDEDOR: TStringField;
    SQLTerminalAtivoTERMCUSALIMITECRED: TStringField;
    SQLTerminalAtivoTERMA60IMPCARNE: TStringField;
    SQLTerminalAtivoTERMA60IMPPEDIDO: TStringField;
    SQLTerminalAtivoTERMA60IMPORCAMEN: TStringField;
    SQLTerminalAtivoTERMA60IMPCHEQUE: TStringField;
    SQLTerminalAtivoTERMA60IMPTCKAFCX: TStringField;
    SQLTerminalAtivoTERMCUSAMOEDA: TStringField;
    SQLTerminalAtivoTERMCIMPRIMECHEQUE: TStringField;
    SQLTerminalAtivoTERMCCONFIMPCARNE: TStringField;
    SQLTerminalAtivoTERMCIMPCONFDIVIDA: TStringField;
    SQLTerminalAtivoTERMCINFDADOSCLICP: TStringField;
    SQLTerminalAtivoTERMCIMPIDCUPOM: TStringField;
    SQLTerminalAtivoTERMA255MSGCARNE: TStringField;
    SQLTerminalAtivoTERMCIMPBARRASPED: TStringField;
    SQLTerminalAtivoTERMCINFDADOCLIPAD: TStringField;
    SQLTerminalAtivoTERMINRODECQUANT: TIntegerField;
    SQLTerminalAtivoTERMINUMEVISTA: TIntegerField;
    SQLTerminalAtivoTERMINUMEPRAZO: TIntegerField;
    SQLConfigCrediario: TRxQuery;
    SQLConfigCrediarioCFCRN2PERCJURATRAS: TBCDField;
    SQLConfigCrediarioCFCRN2PERCMULATRAS: TBCDField;
    SQLConfigCrediarioCFCRN2PERCADIANT: TBCDField;
    SQLConfigCrediarioCFCRINRODIASADIANT: TIntegerField;
    SQLConfigCrediarioCFCRCCONSMOTBLOQ: TStringField;
    SQLConfigCrediarioCFCRCCONSCARTAVISO: TStringField;
    SQLConfigCrediarioCFCRA255PATHRELSPC: TStringField;
    SQLConfigCrediarioCFCRA255PATHAUTDEP: TStringField;
    SQLConfigCrediarioCFCRINRODIASTOLJUR: TIntegerField;
    SQLConfigCrediarioCFCRINRODIASTOLMUL: TIntegerField;
    SQLClienteDadChq: TRxQuery;
    SQLTotalizadorCaixa: TRxQuery;
    SQLTotalizar: TRxQuery;
    SQLTotalizadorCaixaTOTAICOD: TIntegerField;
    SQLTotalizadorCaixaTOTAA60DESCR: TStringField;
    SQLTotalizadorCaixaTOTACTRANSFSALDO: TStringField;
    SQLTotalizadorCaixaTOTACDEBITOCREDITO: TStringField;
    SQLTotalizadorCaixaTOTAIORDLIST: TIntegerField;
    SQLOperacaoCaixa: TRxQuery;
    SQLOperacaoCaixaOPCXICOD: TIntegerField;
    SQLOperacaoCaixaOPCXCDEBITOCREDITO: TStringField;
    SQLOperacaoCaixaOPCXA5SIGLA: TStringField;
    SQLOperacaoCaixaOPCXA60DESCR: TStringField;
    SQLConfigGeral: TRxQuery;
    SQLConfigGeralCFGECATIVAEXPORT: TStringField;
    SQLConfigGeralCFGECATUSALDODIA: TStringField;
    SQLConfigGeralCFGEITIPMOVCONTENT: TIntegerField;
    SQLConfigGeralCFGEITIPMOVCONTSAI: TIntegerField;
    SQLConfigGeralCFGEA255PATHBLOQ: TStringField;
    SQLConfigGeralCFGECSETAREMPADREL: TStringField;
    SQLConfigGeralCFGECTROCAEMPLOGON: TStringField;
    SQLConfigGeralCFGEA255PATHFOTOCLI: TStringField;
    SQLConfigGeralCFGE1255PATHMALDIR: TStringField;
    SQLConfigGeralCFGECDELARQTEMPREL: TStringField;
    SQLConfigGeralCFGEA255PATHLOGOEMP: TStringField;
    SQLConfigGeralCFGECATUALSALDOMES: TStringField;
    SQLConfigGeralCFGECVALCODBARPROD: TStringField;
    SQLConfigGeralCFGECVALCODANTPRO: TStringField;
    SQLConfigGeralCFGECVALREFPROD: TStringField;
    SQLConfigGeralCFGECBASEPRCVENDA: TStringField;
    SQLConfigGeralCFGEIEMPPADRAO: TIntegerField;
    SQLConfigGeralCFGEA60HOSTSMTP: TStringField;
    SQLConfigGeralCFGEA60ENDRETSMTP: TStringField;
    SQLConfigGeralCFGEA60ENDHOSTPOP: TStringField;
    SQLConfigGeralCFGEA60NOMEUSERPOP: TStringField;
    SQLConfigGeralCFGEA60SENHAPOP: TStringField;
    SQLConfigGeralCGGEA30VERSAO: TStringField;
    SQLConfigGeralCFGEA255PATHVERSAO: TStringField;
    SQLConfigGeralCFGEA255PATHETIBAR: TStringField;
    SQLTerminalAtivoTERMCATIVO: TStringField;
    SQLTerminalAtivoUSUAICODATIVO: TIntegerField;
    MemCtRecParc: TTable;
    MemCtRecParcCUPOA13ID: TStringField;
    MemCtRecParcCTRCA13ID: TStringField;
    MemCtRecParcCTRCINROPARC: TIntegerField;
    MemCtRecParcCTRCDVENC: TDateTimeField;
    MemCtRecParcCTRCN2VLR: TBCDField;
    DSSQLCupomCons: TDataSource;
    DSMemCtRecParc: TDataSource;
    SQLTerminalAtivoECFA13ID: TStringField;
    SQLConfigVenda: TRxQuery;
    SQLConfigVendaCFVEN2PERCLIMCRED: TBCDField;
    SQLConfigVendaCFVEN3MAXLIMCRED: TBCDField;
    SQLConfigVendaCFVECTIPOLIMCRED: TStringField;
    SQLConfigVendaCFVECARREDPARCELA: TStringField;
    SQLConfigVendaCFVECTIPOIMPPED: TStringField;
    SQLConfigVendaCFVECDADOSCHQPDV: TStringField;
    SQLConfigVendaCFVECUSADEBCREDCLI: TStringField;
    SQLConfigVendaCGVECTESTAITENSNF: TStringField;
    SQLConfigVendaCFVEN3ALIQISSQN: TBCDField;
    SQLConfigVendaCFVECIMPLEGPEDVENF: TStringField;
    SQLConfigVendaCFVEN3PERCICMFRETE: TBCDField;
    SQLConfigVendaCFVEA255OBSPADNF: TStringField;
    SQLConfigVendaCFVEITEMPOCONSPROD: TIntegerField;
    SQLConfigVendaCFVECQUITARPARCHQ: TStringField;
    SQLConfigVendaCFVEA255OBSPADRPED: TStringField;
    SQLConfigVendaOPESICODCUPOM: TIntegerField;
    SQLConfigVendaOPESICODCANCCUPOM: TIntegerField;
    SQLConfigVendaOPESICODNF: TIntegerField;
    SQLConfigVendaOPESICODCANCNF: TIntegerField;
    SQLConfigVendaCFVECRENDCONJNOLIM: TStringField;
    SQLTerminalAtivoTERMA5ECFPORTACOM: TStringField;
    SQLConfigVendaOPESICODRETORNO: TIntegerField;
    DatabaseTerm: TDatabase;
    SQLCupom: TRxQuery;
    SQLCupomCUPOA13ID: TStringField;
    SQLCupomEMPRICOD: TIntegerField;
    SQLCupomTERMICOD: TIntegerField;
    SQLCupomCUPOICOD: TIntegerField;
    SQLCupomCUPODEMIS: TDateTimeField;
    SQLCupomCLIEA13ID: TStringField;
    SQLCupomPLRCICOD: TIntegerField;
    SQLCupomVENDICOD: TIntegerField;
    SQLCupomCONVICOD: TIntegerField;
    SQLCupomCUPOCSTATUS: TStringField;
    SQLCupomCUPON2TOTITENS: TBCDField;
    SQLCupomCUPON2DESC: TBCDField;
    SQLCupomCUPON2ACRESC: TBCDField;
    SQLCupomCUPON2TOTITENSRET: TBCDField;
    SQLCupomCUPOINRO: TIntegerField;
    SQLCupomCUPOCTIPOPADRAO: TStringField;
    SQLCupomCUPON2CONVTAXA: TBCDField;
    SQLCupomCUPOINROORDCOMPRA: TIntegerField;
    SQLCupomCUPOA13IDTROCA: TStringField;
    SQLCupomCUPON2VLRCOMISSAO: TBCDField;
    SQLCupomCUPOA20CODANT: TStringField;
    SQLCupomCUPODCANC: TDateTimeField;
    SQLCupomCUPON2JUROATRAS: TBCDField;
    SQLCupomCUPON2MULTAATRAS: TBCDField;
    SQLCupomCUPODPAGTOCONSIG: TDateTimeField;
    SQLCupomPENDENTE: TStringField;
    SQLCupomREGISTRO: TDateTimeField;
    DSSQLCupom: TDataSource;
    SQLCupomItem: TRxQuery;
    DSSQLCupomItem: TDataSource;
    SQLCupomItemCUPOA13ID: TStringField;
    SQLCupomItemCPITIPOS: TIntegerField;
    SQLCupomItemPRODICOD: TIntegerField;
    SQLCupomItemCPITCSTATUS: TStringField;
    SQLCupomItemCPITN3QTD: TBCDField;
    SQLCupomItemCPITN3QTDTROCA: TBCDField;
    SQLCupomItemCPITN3VLRUNIT: TBCDField;
    SQLCupomItemCPITN3VLRCUSTUNIT: TBCDField;
    SQLCupomItemCPITN2DESC: TBCDField;
    SQLCupomItemCPITN3VLRUNITLUCR: TBCDField;
    SQLCupomItemCOITN2ICMSALIQ: TBCDField;
    SQLCupomItemVENDICOD: TIntegerField;
    SQLCupomItemPENDENTE: TStringField;
    SQLCupomItemREGISTRO: TDateTimeField;
    SQLCupomNumerario: TRxQuery;
    DSSQLCupomNumerario: TDataSource;
    SQLContasReceber: TRxQuery;
    DSSQLContasReceber: TDataSource;
    SQLCupomNumerarioCUPOA13ID: TStringField;
    SQLCupomNumerarioNUMEICOD: TIntegerField;
    SQLCupomNumerarioCONMCSTATUS: TStringField;
    SQLCupomNumerarioCPNMN2VLR: TBCDField;
    SQLCupomNumerarioPENDENTE: TStringField;
    SQLCupomNumerarioREGISTRO: TDateTimeField;
    SQLCupomNumerarioCPNMCAUTENT: TStringField;
    SQLCupomNumerarioCLIEA13ID: TStringField;
    SQLProxCodCTRC: TRxQuery;
    SQLProdutoSaldo: TRxQuery;
    SQLProdutoSaldoEMPRICOD: TIntegerField;
    SQLProdutoSaldoPRODICOD: TIntegerField;
    SQLProdutoSaldoPSLDN3QTDE: TBCDField;
    SQLProdutoFilho: TRxQuery;
    DSSQLProduto: TDataSource;
    SQLProduto: TRxQuery;
    SQLTerminalAtivoTERMCIMPPREVENDA: TStringField;
    SQLConfigVendaOPESICODCANCTROCA: TIntegerField;
    SQLConfigVendaOPESICODTROCA: TIntegerField;
    SQLCupomCUPON3BONUSTROCA: TBCDField;
    SQLCupomCUPODENTREGA: TDateTimeField;
    SQLCupomTPVDICOD: TIntegerField;
    SQLConfigVendaCFVECINFDADOVENDA: TStringField;
    SQLEmpresa: TRxQuery;
    SQLConfigGeralEmpresaLookup: TStringField;
    SQLConfigCrediarioCFCRN2PERCTAXACOBR: TBCDField;
    SQLUsuarioUSUACVERDADCOMPRCLI: TStringField;
    SQLUsuarioUSUACDESBLOQCLI: TStringField;
    SQLUsuarioUSUAN2PERCDESC: TBCDField;
    SQLUsuarioUSUACVENDCLIBLOQ: TStringField;
    TblTicketPreVendaCab: TTable;
    TblTicketPreVendaCabTicketNumero: TStringField;
    TblTicketPreVendaCabVendedor: TStringField;
    TblTicketPreVendaCabPlano: TStringField;
    TblTicketPreVendaCabCliente: TStringField;
    TblTicketPreVendaCabFoneCliente: TStringField;
    TblTicketPreVendaCabTotalNominal: TFloatField;
    TblTicketPreVendaCabTaxaCrediario: TFloatField;
    TblTicketPreVendaCabAcrescimo: TFloatField;
    TblTicketPreVendaCabDesconto: TFloatField;
    TblTicketPreVendaCabTotalGeral: TFloatField;
    TblTicketPreVendaCabNroCreditCard: TStringField;
    TblTicketPreVendaCabNumerarioPagto: TStringField;
    TblTicketPreVendaCabMensagem: TStringField;
    TblTicketPreVendaCabDataEntrega: TStringField;
    TblTicketPreVendaCabTipoVenda: TStringField;
    TblTicketPreVendaCabPessoaRecebeNome: TStringField;
    TblTicketPreVendaCabPessoaRecebeEnder: TStringField;
    TblTicketPreVendaCabPessoaRecebeBai: TStringField;
    TblTicketPreVendaCabPessoaRecebeCid: TStringField;
    TblTicketPreVendaCabPessoaRecebeUF: TStringField;
    TblTicketPreVendaCabPessoaRecebeFone: TStringField;
    TblTicketPreVendaItem: TTable;
    TblTicketPreVendaItemCodigo: TIntegerField;
    TblTicketPreVendaItemDescricao: TStringField;
    TblTicketPreVendaItemQuantidade: TFloatField;
    TblTicketPreVendaItemValorUnitario: TFloatField;
    TblTicketPreVendaItemValorTotal: TFloatField;
    TblTicketPreVendaItemDesconto: TFloatField;
    TblTicketPreVendaItemMarca: TStringField;
    TblTicketPreVendaItemReferencia: TStringField;
    SQLCupomIt: TRxQuery;
    SQLCupomItCUPOA13ID: TStringField;
    SQLCupomItCPITIPOS: TIntegerField;
    SQLCupomItPRODICOD: TIntegerField;
    SQLCupomItCPITCSTATUS: TStringField;
    SQLCupomItCPITN3QTD: TBCDField;
    SQLCupomItCPITN3QTDTROCA: TBCDField;
    SQLCupomItCPITN3VLRUNIT: TBCDField;
    SQLCupomItCPITN2DESC: TBCDField;
    SQLCupomItVENDICOD: TIntegerField;
    SQLCup: TRxQuery;
    SQLCupomCUPON3CREDTAXA: TBCDField;
    SQLPreVD: TRxQuery;
    SQLPreVDIt: TRxQuery;
    SQLPreVendaItem2: TRxQuery;
    SQLPreVendaItem2TERMICOD: TIntegerField;
    SQLPreVendaItem2PRVDICOD: TIntegerField;
    SQLPreVendaItem2PVITIPOS: TIntegerField;
    SQLPreVendaItem2PRODICOD: TIntegerField;
    SQLPreVendaItem2PVITN3QTD: TBCDField;
    SQLPreVendaItem2PVITN3VLRUNIT: TBCDField;
    SQLPreVendaItem2PVITN3VLRCUSTUNIT: TBCDField;
    SQLPreVendaItem2PVITN2DESC: TBCDField;
    SQLPreVendaItem2VENDICOD: TIntegerField;
    SQLPreVendaItem2PVITN3VLRUNITLUCR: TBCDField;
    SQLPreVendaItem2PVITCSTATUS: TStringField;
    SQLPreVendaItem2PVITN2ICMSALIQ: TBCDField;
    SQLContasReceberCTRCA13ID: TStringField;
    SQLContasReceberEMPRICOD: TIntegerField;
    SQLContasReceberTERMICOD: TIntegerField;
    SQLContasReceberCTRCICOD: TIntegerField;
    SQLContasReceberCLIEA13ID: TStringField;
    SQLContasReceberCTRCCSTATUS: TStringField;
    SQLContasReceberCTRCINROPARC: TIntegerField;
    SQLContasReceberCTRCDVENC: TDateTimeField;
    SQLContasReceberCTRCN2VLR: TBCDField;
    SQLContasReceberCTRCN2DESCFIN: TBCDField;
    SQLContasReceberNUMEICOD: TIntegerField;
    SQLContasReceberPORTICOD: TIntegerField;
    SQLContasReceberCTRCN2TXJURO: TBCDField;
    SQLContasReceberCTRCN2TXMULTA: TBCDField;
    SQLContasReceberCTRCA5TIPOPADRAO: TStringField;
    SQLContasReceberCTRCDULTREC: TDateTimeField;
    SQLContasReceberCTRCN2TOTREC: TBCDField;
    SQLContasReceberCTRCN2TOTJUROREC: TBCDField;
    SQLContasReceberCTRCN2TOTMULTAREC: TBCDField;
    SQLContasReceberCTRCN2TOTDESCREC: TBCDField;
    SQLContasReceberEMPRICODULTREC: TIntegerField;
    SQLContasReceberCUPOA13ID: TStringField;
    SQLContasReceberTPDCICOD: TIntegerField;
    SQLContasReceberPLCTA15COD: TStringField;
    SQLContasReceberCTRCA30NRODUPLICBANCO: TStringField;
    SQLContasReceberNOFIA13ID: TStringField;
    SQLContasReceberCTRCDEMIS: TDateTimeField;
    SQLContasReceberPENDENTE: TStringField;
    SQLContasReceberREGISTRO: TDateTimeField;
    SQLContasReceberCTRCDREABILSPC: TDateTimeField;
    SQLContasReceberCTRCN2TOTMULTACOBR: TBCDField;
    SQLContasReceberBANCA5CODCHQ: TStringField;
    SQLContasReceberCTRCA10AGENCIACHQ: TStringField;
    SQLContasReceberCTRCA15CONTACHQ: TStringField;
    SQLContasReceberCTRCA15NROCHQ: TStringField;
    SQLContasReceberCTRCA60TITULARCHQ: TStringField;
    SQLContasReceberCTRCA20CGCCPFCHQ: TStringField;
    SQLContasReceberCTRCDDEPOSCHQ: TDateTimeField;
    SQLContasReceberALINICOD: TIntegerField;
    TblTicketPreVendaCabMensagem2: TMemoField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIV: TStringField;
    SQLTerminalAtivoTERMCAUTENTRFIMCUP: TStringField;
    SQLConfigVendaCFVECPARC0ENTRBAIX: TStringField;
    SQLConfigGeralCFGEA255PATHREPORT: TStringField;
    SQLConfigVendaCFVEA250MSGBLOQ: TStringField;
    SQLTerminalAtivoTERMCHIDECLIVENDPL: TStringField;
    SQLTerminalAtivoTERMCIMPRDADINTCUP: TStringField;
    SQLTerminalAtivoTERMCCONFFECHCUPOM: TStringField;
    SQLCliDadosCompra: TRxQuery;
    SQLCliDadosCompraCLIEA13ID: TStringField;
    SQLCliDadosCompraCLIEDPRICOMPRA: TDateTimeField;
    SQLCliDadosCompraCLIEDULTCOMPRA: TDateTimeField;
    SQLConfigCrediarioCFCRCBLOQVENDCLI1AV: TStringField;
    SQLConfigCrediarioCFCRCBLOQVENDCLI2AV: TStringField;
    SQLConfigCrediarioCFCRCBLOQVENDCLI3AV: TStringField;
    SQLPreco: TRxQuery;
    SQLConfigVendaTPRCICOD: TIntegerField;
    TblCupomCab: TTable;
    TblCupomItemVend: TTable;
    TblCupomItemRet: TTable;
    TblCupomFinan: TTable;
    SQLProdutoOrdemPesquisa: TRxQuery;
    SQLProdutoOrdemPesquisaPDOPIORDEM: TIntegerField;
    SQLProdutoOrdemPesquisaPDOPA30CAMPO: TStringField;
    SQLClienteDadChqCLIEA13ID: TStringField;
    SQLClienteDadChqCLIEA60RAZAOSOC: TStringField;
    SQLClienteDadChqBANCA5COD: TStringField;
    SQLClienteDadChqCLIEA5AGENCIA: TStringField;
    SQLClienteDadChqCLIEA10CONTA: TStringField;
    SQLClienteDadChqCLIEA60TITULAR: TStringField;
    SQLClienteDadChqCLIEDABERTCONTA: TDateTimeField;
    SQLCupomCUPOCCONSIG: TStringField;
    SQLConfigVendaCFVECFAZVENDCONSIG: TStringField;
    SQLConfigVendaOPESICODDEVOL: TIntegerField;
    SQLCliDadosCompraMTBLICOD: TIntegerField;
    SQLConfigVendaMTBLICODVENDCONSIG: TIntegerField;
    SQLConfigVendaCFVECIMPPREVDCOD: TStringField;
    SQLPreVenda: TRxQuery;
    SQLPreVendaItem1: TRxQuery;
    SQLPreVendaNumerario: TRxQuery;
    SQLPreVendaNumerarioTERMICOD: TIntegerField;
    SQLPreVendaNumerarioPRVDICOD: TIntegerField;
    SQLPreVendaNumerarioNUMEICOD: TIntegerField;
    SQLPreVendaNumerarioPVNUN2VLR: TBCDField;
    SQLPreVendaContasReceber: TRxQuery;
    SQLPreVendaContasReceberPVCRICOD: TIntegerField;
    SQLPreVendaContasReceberTERMICOD: TIntegerField;
    SQLPreVendaContasReceberPRVDICOD: TIntegerField;
    SQLPreVendaContasReceberNUMEICOD: TIntegerField;
    SQLPreVendaContasReceberPVCRINROPARC: TIntegerField;
    SQLPreVendaContasReceberPVCRDVENC: TDateTimeField;
    SQLPreVendaContasReceberPVCRN2VLR: TBCDField;
    SQLPreVendaContasReceberPVCRN2DESCFIN: TBCDField;
    SQLPreVendaItem1TERMICOD: TIntegerField;
    SQLPreVendaItem1PRVDICOD: TIntegerField;
    SQLPreVendaItem1PVITIPOS: TIntegerField;
    SQLPreVendaItem1PRODICOD: TIntegerField;
    SQLPreVendaItem1PVITN3QTD: TBCDField;
    SQLPreVendaItem1PVITN3VLRUNIT: TBCDField;
    SQLPreVendaItem1PVITN3VLRCUSTUNIT: TBCDField;
    SQLPreVendaItem1PVITN2DESC: TBCDField;
    SQLPreVendaItem1VENDICOD: TIntegerField;
    SQLPreVendaItem1PVITN3VLRUNITLUCR: TBCDField;
    SQLPreVendaItem1PVITCSTATUS: TStringField;
    SQLPreVendaItem1PVITN2ICMSALIQ: TBCDField;
    SQLConfigVendaCFVECFINVENDADPREVD: TStringField;
    TblCupomCabCUPOA13ID: TStringField;
    TblCupomCabEmpresaEmit: TStringField;
    TblCupomCabEmpresaEmit_Ender: TStringField;
    TblCupomCabEmpresaEmit_Bairro: TStringField;
    TblCupomCabEmpresaEmit_Cidade: TStringField;
    TblCupomCabEmpresaEmit_Fone: TStringField;
    TblCupomCabCliente: TStringField;
    TblCupomCabCliente_Ender: TStringField;
    TblCupomCabCliente_Bairro: TStringField;
    TblCupomCabCliente_Cidade: TStringField;
    TblCupomCabCliente_CPF: TStringField;
    TblCupomCabQtde_Devolvida: TIntegerField;
    TblCupomCabQtde_Retirada: TIntegerField;
    TblCupomCabCondPagto: TStringField;
    TblCupomCabVendedor: TStringField;
    TblCupomCabDataEmissao: TDateField;
    TblCupomCabObservacoes: TStringField;
    TblCupomCabTotalBruto: TFloatField;
    TblCupomCabEncargosFin: TFloatField;
    TblCupomCabDescRetorno: TFloatField;
    TblCupomCabSaldoAnterior: TFloatField;
    TblCupomCabTotalDescontos: TFloatField;
    TblCupomCabTotalLiquido: TFloatField;
    TblCupomCabCreditoTroco: TFloatField;
    TblCupomCabTotalPagar: TFloatField;
    TblCupomItemVendCUPOA13ID: TStringField;
    TblCupomItemVendItem: TIntegerField;
    TblCupomItemVendCodigo: TIntegerField;
    TblCupomItemVendDescricao: TStringField;
    TblCupomItemVendQuant: TFloatField;
    TblCupomItemVendValorUnitario: TFloatField;
    TblCupomItemVendCodigoAntigo: TStringField;
    TblCupomItemRetCUPOA13ID: TStringField;
    TblCupomItemRetItem: TIntegerField;
    TblCupomItemRetCodigo: TIntegerField;
    TblCupomItemRetDescricao: TStringField;
    TblCupomItemRetQuant: TFloatField;
    TblCupomItemRetValorUnitario: TFloatField;
    TblCupomItemRetCodigoAntigo: TStringField;
    TblCupomFinanCUPOA13ID: TStringField;
    TblCupomFinanDataVenc: TDateField;
    TblCupomFinanValor: TFloatField;
    Report: TCrpe;
    SQLPedidoVenda: TRxQuery;
    SQLPedidoVendaPDVDA13ID: TStringField;
    SQLPedidoVendaEMPRICOD: TIntegerField;
    SQLPedidoVendaPDVDICOD: TIntegerField;
    SQLPedidoVendaVENDICOD: TIntegerField;
    SQLPedidoVendaCLIEA13ID: TStringField;
    SQLPedidoVendaTRANICOD: TIntegerField;
    SQLPedidoVendaPLRCICOD: TIntegerField;
    SQLPedidoVendaPDVDDEMISSAO: TDateTimeField;
    SQLPedidoVendaPDVDN2VLRFRETE: TBCDField;
    SQLPedidoVendaPDVDA30NROPEDCOMP: TStringField;
    SQLPedidoVendaPDVDA30COMPRADOR: TStringField;
    SQLPedidoVendaPDVDCTIPO: TStringField;
    SQLPedidoVendaPDVDCSTATUS: TStringField;
    SQLPedidoVendaPDVDN2VLRDESC: TBCDField;
    SQLPedidoVendaPDVDN2TOTPROD: TBCDField;
    SQLPedidoVendaPDVDN2TOTPED: TBCDField;
    SQLPedidoVendaPDVDTOBS: TStringField;
    SQLPedidoVendaREGISTRO: TDateTimeField;
    SQLPedidoVendaPENDENTE: TStringField;
    SQLPedidoVendaPDVDN2VLRDESCPROM: TBCDField;
    SQLPedidoVendaPDVDCTIPOFRETE: TStringField;
    SQLPedidoVendaPDVDDENTREGA: TDateTimeField;
    SQLPedidoVendaPDVDINROTALAO: TIntegerField;
    SQLPedidoVendaItem: TRxQuery;
    SQLPedidoVendaItemPDVDA13ID: TStringField;
    SQLPedidoVendaItemPVITIITEM: TIntegerField;
    SQLPedidoVendaItemPRODICOD: TIntegerField;
    SQLPedidoVendaItemPVITN3QUANT: TBCDField;
    SQLPedidoVendaItemPVITN2VLRUNIT: TBCDField;
    SQLPedidoVendaItemPVITN2PERCDESC: TBCDField;
    SQLPedidoVendaItemPVITN2VLRDESC: TBCDField;
    SQLPedidoVendaItemREGISTRO: TDateTimeField;
    SQLPedidoVendaItemPENDENTE: TStringField;
    SQLPedidoVendaItemPDVDA60OBS: TStringField;
    SQLPedidoVendaItemPVITN2PERCCOMIS: TBCDField;
    SQLPedidoVendaItemPVITN3QUANTVEND: TBCDField;
    DBRel: TDatabase;
    DSTblPedidoItens: TDataSource;
    PipePedVd: TppBDEPipeline;
    PipePedVdIt: TppBDEPipeline;
    TblPedidoCab: TTable;
    TblPedidoItens: TTable;
    TblPedidoFinan: TTable;
    TblPedidoCabPedICod: TStringField;
    TblPedidoCabEmitente_Nome: TStringField;
    TblPedidoCabEmitente_Ender: TStringField;
    TblPedidoCabEmitente_Bairro: TStringField;
    TblPedidoCabEmitente_Cidade: TStringField;
    TblPedidoCabEmitente_UF: TStringField;
    TblPedidoCabEmitente_CGC: TStringField;
    TblPedidoCabEmitente_IE: TStringField;
    TblPedidoCabEmitente_Fone: TStringField;
    TblPedidoCabDtEmissao: TDateField;
    TblPedidoCabDestinatario_Nome: TStringField;
    TblPedidoCabDestinatario_Endereco: TStringField;
    TblPedidoCabDestinatario_Bairro: TStringField;
    TblPedidoCabDestinatario_Cep: TStringField;
    TblPedidoCabDestinatario_Cidade: TStringField;
    TblPedidoCabDestinatario_UF: TStringField;
    TblPedidoCabDestinatario_CpfCgc: TStringField;
    TblPedidoCabDestinatario_IE: TStringField;
    TblPedidoCabDestinatario_Fone: TStringField;
    TblPedidoCabDestinatario_Fax: TStringField;
    TblPedidoCabTransp: TStringField;
    TblPedidoCabDtaEntrega: TDateField;
    TblPedidoCabComprador: TStringField;
    TblPedidoCabOrdemCompra: TStringField;
    TblPedidoCabPlano: TStringField;
    TblPedidoCabTipoFrete: TStringField;
    TblPedidoCabValorFrete: TFloatField;
    TblPedidoCabTotalDesconto: TFloatField;
    TblPedidoCabTotal: TFloatField;
    TblPedidoCabObservacoes: TMemoField;
    TblPedidoCabVendedor: TStringField;
    TblPedidoCabEmail: TStringField;
    TblPedidoCabPEDIDOORCAMENTO: TStringField;
    TblPedidoItensPedICod: TStringField;
    TblPedidoItensCodigo: TIntegerField;
    TblPedidoItensDescricao: TStringField;
    TblPedidoItensUn: TStringField;
    TblPedidoItensQtd1: TFloatField;
    TblPedidoItensVlrUnitario: TFloatField;
    TblPedidoItensVlrTotal: TFloatField;
    TblPedidoItensCor: TStringField;
    TblPedidoItensTecido: TStringField;
    TblPedidoItensLegenda: TIntegerField;
    TblPedidoItensQtd2: TFloatField;
    TblPedidoItensQtd3: TFloatField;
    TblPedidoItensQtd4: TFloatField;
    TblPedidoItensQtd5: TFloatField;
    TblPedidoItensQtd6: TFloatField;
    TblPedidoItensQtd7: TFloatField;
    TblPedidoItensQtd8: TFloatField;
    TblPedidoItensQtd9: TFloatField;
    TblPedidoItensQtd10: TFloatField;
    TblPedidoItensQtd11: TFloatField;
    TblPedidoItensQtd12: TFloatField;
    TblPedidoItensQtd13: TFloatField;
    TblPedidoItensQtd14: TFloatField;
    TblPedidoItensQtd15: TFloatField;
    TblPedidoFinanPedICod: TStringField;
    TblPedidoFinanVencimento: TDateField;
    TblPedidoFinanValor: TFloatField;
    DSTblPedidoFinan: TDataSource;
    PipePedFin: TppBDEPipeline;
    ReportOrc: TppReport;
    DSTblPedidoCab: TDataSource;
    DSSQLPedidoVenda: TDataSource;
    ppHeaderBand1: TppHeaderBand;
    ppDetailBand1: TppDetailBand;
    ppFooterBand1: TppFooterBand;
    ppDBText1: TppDBText;
    ppDBText2: TppDBText;
    ppDBText3: TppDBText;
    ppDBText4: TppDBText;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppLabel1: TppLabel;
    ppLabel2: TppLabel;
    ppLabel3: TppLabel;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    ppLabel6: TppLabel;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppDBText18: TppDBText;
    ppLabel16: TppLabel;
    ppLabel17: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppDBText19: TppDBText;
    ppSummaryBand1: TppSummaryBand;
    ppLabel21: TppLabel;
    ppDBText20: TppDBText;
    ppLabel22: TppLabel;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppDBMemo1: TppDBMemo;
    ppLabel25: TppLabel;
    ppLabel26: TppLabel;
    ppLabel27: TppLabel;
    ppLine1: TppLine;
    ppLine2: TppLine;
    ppLine3: TppLine;
    TblPedidoCabTotalGeral: TFloatField;
    ppDBText23: TppDBText;
    ppLabel28: TppLabel;
    ppDBText24: TppDBText;
    SQLTerminalAtivoTERMA60IMPAUTORIZCOM: TStringField;
    SQLConfigVendaCFVECFINDPRODPORDESCR: TStringField;
    TblCupomCabCliente_Fone: TStringField;
    TblCupomCabCliente_Codigo: TStringField;
    SQLConfigVendaOPESICODCANCPED: TIntegerField;
    SQLConfigVendaCFVECMOVESTOQUENF: TStringField;
    SQLConfigVendaCFVECMOVESTOQUEPED: TStringField;
    SQLConfigVendaCFVEICMSFRETECOD: TIntegerField;
    SQLConfigVendaOPESICODPED: TIntegerField;
    SQLConfigVendaCFVEINROITENSNF: TIntegerField;
    SQLConfigVendaTPDCICOD: TIntegerField;
    SQLConfigVendaPORTICOD: TIntegerField;
    TblCupomCabConsignada: TStringField;
    SQLConfigVendaCFVECPEDEVLRPRODUTO: TStringField;
    SQLConfigVendaCFVECTESTALIMTCRED: TStringField;
    SQLConfigVendaCFVECSUBDEBNOLIMITE: TStringField;
    SQLParcelas: TRxQuery;
    SQLCliente: TRxQuery;
    SQLConfigVendaCFVETOBSPADRAONF: TStringField;
    SQLConfigVendaCFVETOBSPADRAOPED: TStringField;
    SQLTerminalAtivoTERMCMOSTRAIDCUPOM: TStringField;
    SQLCupomCUPOV254OBS: TStringField;
    SQLFechamentoCaixa: TRxQuery;
    SQLNumerario: TRxQuery;
    SQLFechamentoCaixaFECXDDATAMOV: TDateTimeField;
    SQLFechamentoCaixaEMPRICOD: TIntegerField;
    SQLFechamentoCaixaTERMICOD: TIntegerField;
    SQLFechamentoCaixaNUMEICOD: TIntegerField;
    SQLFechamentoCaixaFECXN2VALOR: TBCDField;
    SQLFechamentoCaixaUSUAICOD: TIntegerField;
    SQLNumerarioNUMEICOD: TIntegerField;
    SQLNumerarioNUMEA30DESCR: TStringField;
    SQLNumerarioNUMECVISTAPRAZO: TStringField;
    SQLNumerarioNUMECATIVO: TStringField;
    SQLNumerarioNUMEA5TIPO: TStringField;
    SQLNumerarioOPCXICOD: TIntegerField;
    SQLNumerarioPENDENTE: TStringField;
    SQLNumerarioREGISTRO: TDateTimeField;
    SQLFechamentoCaixaNUMEA30DESCR: TStringField;
    SQLCupomUSUAICODCANC: TIntegerField;
    SQLCupomCUPOA30DATACARTAO: TStringField;
    SQLCupomCUPOA30HORACARTAO: TStringField;
    SQLCupomCUPOA30NSUPROVEDOR: TStringField;
    SQLCupomCUPOA30NSUINSTITUICAO: TStringField;
    SQLTerminalAtivoEMPRICOD: TIntegerField;
    SQLTerminalAtivoTERMCECFIMPRCLIE: TStringField;
    SQLTerminalAtivoTERMCECFIMPRVEND: TStringField;
    SQLTerminalAtivoPENDENTE: TStringField;
    SQLTerminalAtivoREGISTRO: TDateTimeField;
    SQLTerminalAtivoTERMA60NOMECOMPUT: TStringField;
    SQLTerminalAtivoTERMA60IMPFICHACLI: TStringField;
    SQLTerminalAtivoTERMITMPLIMITESERV: TIntegerField;
    SQLTerminalAtivoTERMIINTERVALOSERV: TIntegerField;
    SQLTerminalAtivoTERMINUMERECCRED: TIntegerField;
    SQLCupomCUPON2DESCITENS: TBCDField;
    SQLCupomItemCPITN2VLRDESCSOBTOT: TBCDField;
    SQLConfigGeralCFGECESTOQUEPORLOTE: TStringField;
    SQLConfigCrediarioCFCRA254PATHMALADIRETA: TStringField;
    SQLConfigCompra: TRxQuery;
    SQLConfigCompraCFCOCTOTPRCVENPROD: TStringField;
    SQLPedidoOrcamento: TRxQuery;
    SQLPedidoOrcamentoPDVDA13ID: TStringField;
    SQLPedidoOrcamentoCLIEA13ID: TStringField;
    SQLPedidoOrcamentoVENDICOD: TIntegerField;
    SQLPedidoOrcamentoPLRCICOD: TIntegerField;
    SQLPedidoOrcamentoPDVDN2TOTPROD: TBCDField;
    SQLPedidoOrcamentoCLIEA60RAZAOSOC: TStringField;
    SQLPedidoOrcamentoVENDA60NOME: TStringField;
    SQLPedidoOrcamentoPLRCA60DESCR: TStringField;
    SQLPedidoOrcamentoItem: TRxQuery;
    SQLPedidoOrcamentoItemPDVDA13ID: TStringField;
    SQLPedidoOrcamentoItemPVITIITEM: TIntegerField;
    SQLPedidoOrcamentoItemPRODICOD: TIntegerField;
    SQLPedidoOrcamentoItemPVITN3QUANT: TBCDField;
    SQLPedidoOrcamentoItemPVITN2VLRUNIT: TBCDField;
    SQLPedidoOrcamentoItemPVITN2PERCDESC: TBCDField;
    SQLPedidoOrcamentoItemPVITN2VLRDESC: TBCDField;
    SQLPedidoOrcamentoItemREGISTRO: TDateTimeField;
    SQLPedidoOrcamentoItemPENDENTE: TStringField;
    SQLPedidoOrcamentoItemPVITN3QUANTVEND: TBCDField;
    SQLPedidoOrcamentoItemPDVDA60OBS: TStringField;
    SQLPedidoOrcamentoItemPVITN2PERCCOMIS: TBCDField;
    SQLPedidoOrcamentoItemPDVDA255OBS1: TStringField;
    SQLPedidoOrcamentoItemLOTEA30NRO: TStringField;
    SQLFechamentoCaixaPENDENTE: TStringField;
    SQLFechamentoCaixaREGISTRO: TDateTimeField;
    SQLFechamentoCaixaFECXA13ID: TStringField;
    SQLFechamentoCaixaFECXICOD: TIntegerField;
    SQLPedidoVendaItemPDVDA255OBS1: TStringField;
    SQLTerminalAtivoTERMINROVIASTEF: TIntegerField;
    SQLNumerarioPRCAA13ID: TStringField;
    SQLProvedorCartao: TRxQuery;
    SQLConfigVendaCFVECQUITAPARCONV: TStringField;
    SQLConfigGeralCFGECUSASALDODIARIO: TStringField;
    SQLConfigVendaCFVECFARREDVLRVEND: TStringField;
    SQLConfigVendaCFVEINROCASASDEC: TIntegerField;
    SQLConfigGeralEmpresaPadraoCalcField: TStringField;
    SQLCupomCATCA13ID: TStringField;
    SQLEmpresaEMPRICOD: TIntegerField;
    SQLEmpresaEMPRA60RAZAOSOC: TStringField;
    SQLEmpresaEMPRA60NOMEFANT: TStringField;
    SQLEmpresaEMPRCMATRIZFILIAL: TStringField;
    SQLEmpresaEMPRA20FONE: TStringField;
    SQLEmpresaEMPRA20FAX: TStringField;
    SQLEmpresaEMPRA60END: TStringField;
    SQLEmpresaEMPRA60BAI: TStringField;
    SQLEmpresaEMPRA60CID: TStringField;
    SQLEmpresaEMPRA2UF: TStringField;
    SQLEmpresaEMPRA8CEP: TStringField;
    SQLEmpresaEMPRCFISJURID: TStringField;
    SQLEmpresaEMPRA14CGC: TStringField;
    SQLEmpresaEMPRA20IE: TStringField;
    SQLEmpresaEMPRA11CPF: TStringField;
    SQLEmpresaEMPRA10RG: TStringField;
    SQLEmpresaEMPRA60EMAIL: TStringField;
    SQLEmpresaEMPRA60URL: TStringField;
    SQLEmpresaPENDENTE: TStringField;
    SQLEmpresaREGISTRO: TDateTimeField;
    SQLEmpresaEMPRA100INFSPC: TStringField;
    SQLConfigVendaCFVECUSALIBERCRED: TStringField;
    SQLTerminalAtivoTERMCAUTENTIMPMATRI: TStringField;
    SQLPedidoOrcamentoPDVDN2VLRDESC: TBCDField;
    SQLPedidoOrcamentoPDVDN2VLRDESCPROM: TBCDField;
    SQLPedidoOrcamentoPDVDN2VLRFRETE: TBCDField;
    SQLPedidoOrcamentoPDVDTOBS: TStringField;
    SQLUsuarioUSUACUSERMASTER: TStringField;
    SQLCupomOPESICOD: TIntegerField;
    SQLUsuarioUSUACCANCVENDA: TStringField;
    SQLUsuarioUSUACEXCLCLI: TStringField;
    SQLUsuarioUSUACCANCPREVENDA: TStringField;
    SQLUsuarioUSUCALTERASLDINVENTARIO: TStringField;
    SQLUsuarioUSUACLIBERACREDITO: TStringField;
    SQLTerminalAtivoTERMACTIPOIMPPEDORC: TStringField;
    SQLTerminalAtivoTERMTPATHPEDORC: TStringField;
    TblPedidoCabEmitente_Email: TStringField;
    TblPedidoCabEmitente_URL: TStringField;
    TblPedidoItensReferencia: TStringField;
    SQLPedidoOrcamentoPDVDCTIPO: TStringField;
    SQLPedidoOrcamentoPDVDDEMISSAO: TDateTimeField;
    SQLConfigGeralCFGECTESTEANPROD: TStringField;
    SQLConfigGeralCFGECTESTREFPROD: TStringField;
    SQLTerminalAtivoTERMA30MODIMPNFISC: TStringField;
    SQLTerminalAtivoTERMCIMPENTCARNE: TStringField;
    SQLCupomPLCTA15CODCRED: TStringField;
    SQLCupomPLCTA15CODDEB: TStringField;
    SQLContasReceberPLCTA15CODDEBITO: TStringField;
    SQLTerminalAtivoTPDCICOD: TIntegerField;
    SQLConfigVendaCFVECEXCLUIPEDFAT: TStringField;
    SQLConfigVendaCFVECALTPEDIMPORT: TStringField;
    SQLConfigVendaOPESICODIMPCUPOM: TIntegerField;
    SQLConfigVendaOPESICODVENDCONSIG: TIntegerField;
    SQLConfigVendaCFVEN2PERCCOFINS: TBCDField;
    SQLConfigVendaCFVEN2PERCENCARG: TBCDField;
    SQLConfigVendaCFVEN2PERCICMS: TBCDField;
    SQLConfigVendaCFVEN2PERCPIS: TBCDField;
    SQLConfigVendaCFVECSOLSENHAALTVLR: TStringField;
    SQLUsuarioPENDENTE: TStringField;
    SQLUsuarioREGISTRO: TDateTimeField;
    SQLUsuarioUSUACEXCLDADOSTESO: TStringField;
    SQLUsuarioUSUACALTCAIXATES: TStringField;
    SQLUsuarioUSUACEXCMOVBCO: TStringField;
    SQLUsuarioUSUACALTVLRVENDA: TStringField;
    TblPedidoCabEmitenteLogo: TBlobField;
    SQLEmpresaEMPRA15CODEAN: TStringField;
    SQLEmpresaEMPRBLOGOTIPO: TBlobField;
    TblPedidoItensCodItem: TIntegerField;
    SQLCupomCUPON2BASEICMS: TBCDField;
    SQLCupomCUPON2VLRICMS: TBCDField;
    SQLCupomItemCPITN2BASEICMS: TBCDField;
    SQLCupomItemCPITN2VLRICMS: TBCDField;
    SQLPedidoOrcamentoEMPRICOD: TIntegerField;
    SQLPedidoOrcamentoPDVDICOD: TIntegerField;
    SQLPedidoOrcamentoTRANICOD: TIntegerField;
    SQLPedidoOrcamentoPDVDA30NROPEDCOMP: TStringField;
    SQLPedidoOrcamentoPDVDA30COMPRADOR: TStringField;
    SQLPedidoOrcamentoPDVDCSTATUS: TStringField;
    SQLPedidoOrcamentoPDVDN2TOTPED: TBCDField;
    SQLPedidoOrcamentoREGISTRO: TDateTimeField;
    SQLPedidoOrcamentoPENDENTE: TStringField;
    SQLPedidoOrcamentoPDVDCTIPOFRETE: TStringField;
    SQLPedidoOrcamentoPDVDDENTREGA: TDateTimeField;
    SQLPedidoOrcamentoPDVDINROTALAO: TIntegerField;
    SQLPedidoOrcamentoPDVDCIMPORTADO: TStringField;
    SQLPedidoOrcamentoPDVDN2PERCFAT: TBCDField;
    SQLPedidoOrcamentoPDVDN2PERCOMIS: TBCDField;
    SQLConfigCrediarioCFCRIPRZMINCARTAO: TStringField;
    MemCtRecParcCUPODEMIS: TDateTimeField;
    MemCtRecParcCUPON2TOTITENS: TBCDField;
    MemCtRecParcCUPON2DESC: TBCDField;
    MemCtRecParcCUPON2ACRESC: TBCDField;
    MemCtRecParcCLIEA13ID: TStringField;
    MemCtRecParcBaixar: TBooleanField;
    MemCtRecParcCTRCN2VLRJURO: TFloatField;
    MemCtRecParcCTRCN2VLRMULTA: TFloatField;
    MemCtRecParcCTRCN2VLRDESC: TFloatField;
    MemCtRecParcCTRCN2VLRTXCOBR: TFloatField;
    SQLConfigVendaCFVECIMPDESCRPRINF: TStringField;
    SQLConfigVendaCFVECCONTPEDVDAUSU: TStringField;
    SQLTerminalAtivoTERMCIMPCOMPTOTREC: TStringField;
    SQLTerminalAtivoTERMCNAOAUTRCTOCRD: TStringField;
    MemCtRecParcCTRCDULTREC: TDateField;
    SQLCupomCUPOA13IDCUPNEG: TStringField;
    SQLCupomCFOPA5COD: TStringField;
    SQLCupomAVALA13ID: TStringField;
    SQLCupomCUPODQUITACAO: TDateTimeField;
    SQLConfigVendaCFVECINFPRODSUBTRI: TStringField;
    TblPedidoCabDestinatario_Fone2: TStringField;
    SQLConfigVendaCFVECQUITAPARCRT: TStringField;
    SQLPreVendaItem2PRODA60NROSERIE: TStringField;
    SQLPreVendaItem1PRODA60NROSERIE: TStringField;
    MemCtRecParcValorOrigem: TFloatField;
    SQLECF: TRxQuery;
    SQLECFECFA30MODELO: TStringField;
    SQLConfigVendaCFVECFRETEPADRAO: TStringField;
    TblPedidoCabValorEntrada: TFloatField;
    TblPedidoFinanPortador: TStringField;
    SQLUsuarioUSUACBLOQCTRLG: TStringField;
    SQLConfigFinanceiro: TRxQuery;
    SQLConfigFinanceiroOPTEICODPAGAR: TIntegerField;
    SQLConfigFinanceiroOPBCICODPAGAR: TIntegerField;
    SQLConfigFinanceiroNUMEICODPAGAR: TIntegerField;
    SQLConfigFinanceiroCTCRICODPAGAR: TIntegerField;
    SQLConfigFinanceiroALINICODPAGAR: TIntegerField;
    SQLConfigFinanceiroCGFIA254HISTPAGAR: TStringField;
    SQLConfigFinanceiroOPTEICODRECEBER: TIntegerField;
    SQLConfigFinanceiroOPBCICODRECEBER: TIntegerField;
    SQLConfigFinanceiroNUMEICODRECEBER: TIntegerField;
    SQLConfigFinanceiroCGFIA254HISTRECEBE: TStringField;
    SQLConfigFinanceiroALINICODRECEBER: TIntegerField;
    SQLConfigFinanceiroPORTICODRECEBER: TIntegerField;
    SQLConfigFinanceiroCGFIUSATESOURARIA: TStringField;
    SQLConfigFinanceiroCGFICINFPLCTBXSIMP: TStringField;
    SQLConfigGeralCFGEA255EXEDUPLICATA: TStringField;
    SQLConfigGeralCFGECALCPRECOAUTOM: TStringField;
    SQLConfigGeralCFGECTIPOMARGLUCRO: TStringField;
    SQLConfigGeralCFGECUSAMARGLIQ: TStringField;
    TblPedidoCabRota: TStringField;
    SQLTerminalAtivoTERMCSQLORDENADO: TStringField;
    SQLTerminalAtivoCFGIICOD: TIntegerField;
    SQLTerminalAtivoTERMTPATHNF: TStringField;
    SQLTerminalAtivoTERMA5LEITPORTACOM: TStringField;
    SQLTerminalAtivoTERMA60MODLEITOR: TStringField;
    SQLTerminalAtivoTERMCDISPOENTRADA: TStringField;
    SQLTerminalAtivoTERMA60MENSAGEMPDV: TStringField;
    SQLTerminalAtivoTERMCINFDADOCARTAO: TStringField;
    SQLConfigVendaCFVECINFVLRDEVCVEN: TStringField;
    SQLCupomItemCPITN2VLRQDEVERIAVENDER: TBCDField;
    SQLTerminalAtivoTERMA30MODIMPCHQ: TStringField;
    SQLTerminalAtivoTERMA5IMPCHQPORTA: TStringField;
    DSTblCheques: TDataSource;
    TblCheques: TMemoryTable;
    TblChequesDtDep: TDateTimeField;
    TblChequesNroCheque: TFloatField;
    TblChequesValor: TFloatField;
    TblChequesHistorico: TStringField;
    TblChequesPORTICOD: TIntegerField;
    TblChequesBANCA5COD: TStringField;
    TblChequesAGENCIA: TStringField;
    TblChequesCONTA: TStringField;
    TblChequesDATAABERT: TDateField;
    TblChequesTITULAR: TStringField;
    TblChequesCGCCPF: TStringField;
    TblChequesALINICOD: TIntegerField;
    TblChequesDataVecto: TDateField;
    SQLConfigGeralOPESICODTRANSFENTR: TIntegerField;
    SQLConfigGeralOPESICODTRANSFSAID: TIntegerField;
    SQLTerminalAtivoTERMCMOSTRATROCOCUP: TStringField;
    SQLPreVendaItem2PVITN3QTDTROCA: TBCDField;
    SQLPreVendaItem1PVITN3QTDTROCA: TBCDField;
    SQLPreVendaTERMICOD: TIntegerField;
    SQLPreVendaPRVDICOD: TIntegerField;
    SQLPreVendaCONVICOD: TIntegerField;
    SQLPreVendaCLIEA13ID: TStringField;
    SQLPreVendaPLRCICOD: TIntegerField;
    SQLPreVendaPRVDCMARCADO: TStringField;
    SQLPreVendaPRVDN2TOTITENS: TBCDField;
    SQLPreVendaPRVDN2DESC: TBCDField;
    SQLPreVendaVENDICOD: TIntegerField;
    SQLPreVendaPRVDCIMPORT: TStringField;
    SQLPreVendaCLIEA60RAZAOSOC: TStringField;
    SQLPreVendaCLIEA60ENDRES: TStringField;
    SQLPreVendaCLIEA60BAIRES: TStringField;
    SQLPreVendaCLIEA60CIDRES: TStringField;
    SQLPreVendaCLIEDCAD: TDateTimeField;
    SQLPreVendaCLIEDPRICOMPRA: TDateTimeField;
    SQLPreVendaCLIEDULTCOMPRA: TDateTimeField;
    SQLPreVendaTPCLICOD: TIntegerField;
    SQLPreVendaMTBLICOD: TIntegerField;
    SQLPreVendaVENDA60NOME: TStringField;
    SQLPreVendaTERMA60DESCR: TStringField;
    SQLPreVendaCLIENTENOME: TStringField;
    SQLPreVendaCLIENTEENDE: TStringField;
    SQLPreVendaCLIENTECIDA: TStringField;
    SQLPreVendaCLIENTEOBS: TStringField;
    SQLPedidoOrcamentoUSUAA60LOGIN: TStringField;
    SQLPedidoOrcamentoROTAICOD: TIntegerField;
    SQLPedidoOrcamentoSERIA5COD: TStringField;
    SQLPedidoOrcamentoVEICA13ID: TStringField;
    SQLPedidoOrcamentoPDVDA15NROPEDPALM: TStringField;
    SQLPedidoOrcamentoNOFIAOBSCORPONF: TStringField;
    SQLPedidoOrcamentoPDVD8PLACAVEIC: TStringField;
    SQLPedidoOrcamentoOPESICOD: TIntegerField;
    SQLContasReceberPDVDA13ID: TStringField;
    SQLContasReceberCTRCDESTORNO: TDateTimeField;
    SQLContasReceberFRETA13ID: TStringField;
    SQLContasReceberCTRCCTEMREGRECEBER: TStringField;
    SQLContasReceberCOBRA13ID: TStringField;
    SQLContasReceberCTRCDENVIOCOBRANCA: TDateTimeField;
    SQLContasReceberCTRCA254HIST: TStringField;
    SQLContasReceberDUPLA13ID: TStringField;
    SQLContasReceberAVALA13ID: TStringField;
    SQLContasReceberCTRCCTIPOREGISTRO: TStringField;
    SQLContasReceberHTPDICOD: TIntegerField;
    SQLContasReceberCONTA13ID: TStringField;
    SQLContasReceberCTRCA13CTRCAIDCHQ: TStringField;
    SQLContasReceberCTRCCEMITIDOBOLETO: TStringField;
    SQLPreVendaCLIENTECNPJ: TStringField;
    SQLPreVendaCLIEDNASC: TDateTimeField;
    SQLPreVendaCLIEN2RENDA: TBCDField;
    SQLPreVendaCLIEN2CONJUGERENDA: TBCDField;
    SQLPreVendaCLIEN2LIMITECRED: TBCDField;
    TblCupomCabVlrEntrada: TFloatField;
    SQLCupomCLIENTENOME: TStringField;
    SQLCupomCLIENTECNPJ: TStringField;
    SQLCupomCLIENTEENDE: TStringField;
    SQLCupomCLIENTECIDA: TStringField;
    SQLBomba: TRxQuery;
    SQLTanque: TRxQuery;
    DSSQLBomba: TDataSource;
    DSSQLTanque: TDataSource;
    SQLPreVendaPDVDDHVENDA: TDateTimeField;
    TblTicketPreVendaCabVlrEntrada: TFloatField;
    TblTicketPreVendaCabNomeClienteVenda: TStringField;
    TblTicketPreVendaCabDocumentoClienteVenda: TStringField;
    TblTicketPreVendaCabEnderecoClienteVenda: TStringField;
    TblTicketPreVendaCabCidadeClienteVenda: TStringField;
    TblTicketPreVendaCabOBSImpressaoCupom: TStringField;
    SQLTerminalAtivoTERMCSOLCODVEND: TStringField;
    TblTicketPreVendaItemTroca: TStringField;
    SQLConfigGeralCFGECBLOQ: TStringField;
    SQLUsuarioUSUACVISULUCVEND: TStringField;
    SQLConfigCompraCFCOITIPMOVNFE: TIntegerField;
    SQLConfigCompraCFCOITIPMOVCANCNFE: TIntegerField;
    SQLConfigCompraCFCOCALTPRCPRODENT: TStringField;
    SQLConfigCompraCFCOCTESTAITENSNFE: TStringField;
    SQLConfigCompraCFCOCNUMSERPRODENT: TStringField;
    SQLConfigCompraCFCOCIMPLEGORDCOMP: TStringField;
    SQLConfigCompraCFCOCALTPERCIPI: TStringField;
    SQLConfigCompraCFCOCALTVLRCOMPRA: TStringField;
    SQLConfigCompraCFCOCALTVLRCUSTO: TStringField;
    SQLConfigCompraPORTICOD: TIntegerField;
    SQLConfigCompraTPDCICOD: TIntegerField;
    SQLConfigCompraCFCOCEXCLUIPEDENT: TStringField;
    SQLConfigCompraCFCOCTESTPRODFORN: TStringField;
    SQLConfigCompraCFCOCVERIFICAVLRMENOR: TStringField;
    SQLConfigCompraCFCOCINFDADOSFRETE: TStringField;
    SQLTerminalAtivoTERMCIMPPREVENDASIM: TStringField;
    SQLEmpresaEMPRCLUCROREAL: TStringField;
    SQLCupomNumerarioPLCTA15COD: TStringField;
    SQLUsuarioUSUCDESTRIMPFISC: TStringField;
    SQLUsuarioUSUAA60EMAIL: TStringField;
    SQLUsuarioUSUACVERTODASEMPR: TStringField;
    SQLUsuarioUSUACBXCPAGFIN: TStringField;
    SQLUsuarioUSUACBXCRECFIN: TStringField;
    SQLUsuarioUSUCENCERRAMVTODVS: TStringField;
    SQLUsuarioUSUACLIBERASALDNEG: TStringField;
    SQLTerminalAtivoTERMCBXESTFECHCX: TStringField;
    SQLPreVendaPDVCPRECONCLU: TStringField;
    SQLUsuarioUSUACVRESFINFORN: TStringField;
    TblTicketPreVendaCabTERMICOD: TIntegerField;
    TblTicketPreVendaCabPRVDICOD: TIntegerField;
    TblTicketPreVendaCabDataEmissao: TDateTimeField;
    TblPedidoFinanParcela: TStringField;
    TblPedidoFinanNumerario: TStringField;
    SQLCupomItemBOMBICOD: TIntegerField;
    SQLCupomCLIENTEFONE: TStringField;
    SQLPreVendaCLIENTEFONE: TStringField;
    TblTicketPreVendaCabFoneClienteVenda: TStringField;
    SQLPreVendaCLIEA15FONE1: TStringField;
    SQLCupomUSUAICODVENDA: TIntegerField;
    TblTicketPreVendaCabUsuarioVendaSTR: TStringField;
    SQLPedidoVendaPDVDCIMPORTADO: TStringField;
    SQLPedidoVendaItemPVITN3TOTVENDITEM: TBCDField;
    SQLCupomCLDPICOD: TIntegerField;
    SQLContasReceberCTRCA2MESCOMP: TStringField;
    SQLContasReceberCTRCA4ANOCOMP: TStringField;
    SQLContasReceberCLDPICOD: TIntegerField;
    SQLPreVendaCLDPICOD: TIntegerField;
    SQLUsuarioUSUACPERMVMOVCX: TStringField;
    SQLUsuarioUSUACPERMVVENDAS: TStringField;
    SQLUsuarioUSUACPERMLEITX: TStringField;
    SQLUsuarioUSUACPERMREDZ: TStringField;
    SQLUsuarioUSUACPERMSANGRIA: TStringField;
    SQLUsuarioUSUACPERMSUPRI: TStringField;
    SQLConfigCrediarioCFCRA255PATHCARTPE: TStringField;
    SQLCupomCUPOA8PLACAVEIC: TStringField;
    TblTicketPreVendaCabPlacaVeiculo: TStringField;
    TblPedidoCabPlacaVeiculo: TStringField;
    SQLConfigGeralCFGEDBLOQ: TDateTimeField;
    SQLConfigVendaCFVEA20ORDIMPVEND: TStringField;
    SQLUsuarioUSUACPERMRESUCX: TStringField;
    SQLUsuarioUSUACVENDCLIBLOQCHQ: TStringField;
    SQLUsuarioUSUACVENDCLIBLOQMOTIV: TStringField;
    TblTicketPreVendaCabTroco: TFloatField;
    TblPedidoCabTroco: TFloatField;
    SQLCupomTROCO: TBCDField;
    SQLUsuarioUSUACPVERCLICASH: TStringField;
    TblChequesNroDias: TIntegerField;
    SQLCupomItemEMPRICOD: TIntegerField;
    SQLBombaEMPRICOD: TIntegerField;
    SQLBombaBOMBICOD: TIntegerField;
    SQLBombaTANQICOD: TIntegerField;
    SQLBombaBOMBN2CONT: TBCDField;
    SQLBombaBOMBA30DESCR: TStringField;
    SQLBombaBOMBN3VLRVISTA: TBCDField;
    SQLBombaPENDENTE: TStringField;
    SQLBombaREGISTRO: TDateTimeField;
    SQLBombaCONVERTER: TStringField;
    SQLBombaSTATUS: TStringField;
    SQLBombaPOINT: TIntegerField;
    SQLTanqueEMPRICOD: TIntegerField;
    SQLTanqueTANQICOD: TIntegerField;
    SQLTanqueTANQA30DESCR: TStringField;
    SQLTanquePRODICOD: TIntegerField;
    SQLTanqueTANQN2CAPACID: TBCDField;
    SQLTanqueTANQN2SALDO: TBCDField;
    SQLTanqueTANQN2ESTMIN: TBCDField;
    SQLCupomItemENCERRANTE: TIntegerField;
    SQLTerminalAtivoTERMIQTDEPADRAO: TIntegerField;
    SQLPopUP: TQuery;
    SQLPopUPPOPTEMPO: TStringField;
    SQLPopUPCFGCCEXIBIRPOPTARE: TStringField;
    SQLTerminalAtivoTERMCTECLREDUZ: TStringField;
    SQLConfigInventario: TRxQuery;
    SQLConfigInventarioOPESICODENTRADA: TIntegerField;
    SQLConfigInventarioOPESICODSAIDA: TIntegerField;
    SQLTerminalAtivoTERMCMPATACADO: TStringField;
    SQLPreVendaCLIETOBS1: TBlobField;
    SQLTerminalAtivoTERMIPROXCODCTRC: TIntegerField;
    SQLTerminalAtivoTERMA60IMPNF: TStringField;
    SQLTerminalAtivoTERMCIMPNFPRT: TStringField;
    SQLTerminalAtivoTERMCIMPPEDPRT: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIVIMPFAT: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIVIMPITENS: TStringField;
    SQLTerminalAtivoTERMCECFIMPRCONFDIVPERGUNTA: TStringField;
    SQLUsuarioUSUACPERMITECASH: TStringField;
    SQLUsuarioUSUACPRODNOTFOUND: TStringField;
    SQLConfigCrediarioCFCRINRODIACARTA1A: TIntegerField;
    TblTicketPreVendaCabPEDIDOORCAMENTO: TStringField;
    SQLCupomNumerarioEMPRICOD: TIntegerField;
    TblTicketPreVendaCabDisplayNumero: TIntegerField;
    TblTicketPreVendaCabMesaCodigo: TIntegerField;
    TblTicketPreVendaCabContaCodigo: TIntegerField;
    TblTicketPreVendaCabLevarCasa: TStringField;
    TblTicketPreVendaCabBairroClienteVenda: TStringField;
    TblTicketPreVendaItemComplemento: TStringField;
    TblTicketPreVendaItemImpCozinha: TStringField;
    TblTicketPreVendaItemImpVale: TStringField;
    SQLCupomItemCPITTOBS: TStringField;
    TblTicketPreVendaFin: TTable;
    TblTicketPreVendaFinPedICod: TStringField;
    TblTicketPreVendaFinParcela: TStringField;
    TblTicketPreVendaFinVencimento: TDateField;
    TblTicketPreVendaFinValor: TFloatField;
    TblTicketPreVendaFinPortador: TStringField;
    TblTicketPreVendaFinNumerario: TStringField;
    TblTicketPreVendaFinTipopadrao: TStringField;
    TblAutenticacao: TTable;
    TblAutenticacaoEmpresaNome: TStringField;
    TblAutenticacaoOperacao: TStringField;
    TblAutenticacaoUsuarioNome: TStringField;
    TblAutenticacaoValor: TFloatField;
    TblAutenticacaoHistorico: TStringField;
    TblTicketPreVendaCabKM: TStringField;
    TblAutenticacaoTerminalNome: TStringField;
    TblAutenticacaoForma: TStringField;
    TblTicketPreVendaCabClienteDependente: TStringField;
    TblTicketPreVendaItemUnidade: TStringField;
    SQLCupomItemADICIONAIS: TStringField;
    SQLEmpresaEMPRA3CRT: TStringField;
    SQLCupomItADICIONAIS: TStringField;
    SQLCupomItCPITN2VLRDESCSOBTOT: TBCDField;
    SQLTerminalAtivoTERMINRODECVALORUNIT: TIntegerField;
    SQLConfigVendaCFVECVENDEDOREXIGE: TStringField;
    SQLUsuarioUSUACPLANOCOMSENHA: TStringField;
    SQLUsuarioUSUACPERMITETROCA: TStringField;
    SQLTerminalAtivoTERMCMOVTRANSF: TStringField;
    SQLCupomDISPICOD: TIntegerField;
    SQLCupomItemCPITN2IMPOSTOMED: TBCDField;
    SQLUsuarioUSUACTROCAQTDE: TStringField;
    SQLPedidoVendaItemUNIDICOD: TIntegerField;
    SQLPedidoVendaItemPRODCMIX: TStringField;
    SQLPedidoVendaItemPRODN3PESOBRUTO: TBCDField;
    TblTicketPreVendaCabEmpresaEmit: TStringField;
    TblTicketPreVendaCabEmpresaEmit_Ender: TStringField;
    TblTicketPreVendaCabEmpresaEmit_Bairro: TStringField;
    TblTicketPreVendaCabEmpresaEmit_Cidade: TStringField;
    TblTicketPreVendaCabEmpresaEmit_Fone: TStringField;
    sqlConsulta: TRxQuery;
    SQLEmpresaEMPRA100CERTIFSERIE: TStringField;
    SQLEmpresaEMPRA35CERTIFSENHA: TStringField;
    SQLEmpresaEMPRIFORMAEMISDANFE: TIntegerField;
    SQLEmpresaEMPRIFORMAEMISNFE: TIntegerField;
    SQLEmpresaEMPRA100CAMINHOLOGO: TStringField;
    SQLEmpresaEMPRA100CAMINHOXML: TStringField;
    SQLEmpresaEMPRA100CAMINHODANFES: TStringField;
    SQLEmpresaEMPRA2WSUF: TStringField;
    SQLEmpresaEMPRIWSAMBIENTE: TIntegerField;
    SQLEmpresaEMPRA1VISUALIZAMSG: TStringField;
    SQLEmpresaEMPRA100PROXYHOST: TStringField;
    SQLEmpresaEMPRIPROXYPORTA: TIntegerField;
    SQLEmpresaEMPRA50PROXYUSUARIO: TStringField;
    SQLEmpresaEMPRA50PROXYSENHA: TStringField;
    SQLEmpresaEMPRA50EMAILHOST: TStringField;
    SQLEmpresaEMPRIEMAILPORTA: TIntegerField;
    SQLEmpresaEMPRA50EMAILSENHA: TStringField;
    SQLEmpresaEMPRA1SSL: TStringField;
    SQLEmpresaEMPRA60EMAILCOPIA: TStringField;
    SQLTerminalAtivoECF_VELOC: TIntegerField;
    procedure DataModuleCreate(Sender: TObject);
    procedure SQLCupomNewRecord(DataSet: TDataSet);
    procedure SQLCupomBeforePost(DataSet: TDataSet);
    procedure SQLCupomItemNewRecord(DataSet: TDataSet);
    procedure SQLContasReceberBeforePost(DataSet: TDataSet);
    procedure SQLContasReceberNewRecord(DataSet: TDataSet);
    procedure SQLCupomNumerarioNewRecord(DataSet: TDataSet);
    procedure SQLContasReceberPostError(DataSet: TDataSet;
      E: EDatabaseError; var Action: TDataAction);
    procedure SQLPedidoVendaBeforePost(DataSet: TDataSet);
    procedure SQLPedidoVendaPostError(DataSet: TDataSet; E: EDatabaseError;
      var Action: TDataAction);
    procedure TblPedidoCabCalcFields(DataSet: TDataSet);
    procedure SQLFechamentoCaixaBeforePost(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
    CodTarefa,
    CodNextOrc,
    CodNextCupom,
    ConfigEtiqueta, NumerarioCartao, SubTotal_ECF : string ;
    InserindoItemPV,
    GerandoPedidoVenda,
    ImportandoColetor, AceitaMotivoNaoAtend : boolean ;
    TotalCartao : Double;
    // Adilson p/uso na tela de pedidos
    TrocarStatusPedidoParaFaturado : boolean;
    DataEntregaPedidos, DataEmissaoPedidos : TDate;
    SerieAtualPedidos, VeiculoAtualPedidos, LinhaTXT, FretePorConta, PedidoVolume, PedidoEspecie, PedidoMarca,
    PedidoPesoB, PedidoPesoL, PedidoOBS : String;
    VendedorAtualPedidos, RotaAtualPedidos, TranspAtualPedidos : Integer;
    Texto : TextFile;
    function ConectaServidor : boolean ;
    function BloquearTerminal(Usuario, Terminal : string ) : boolean ;
    procedure DesbloquearTerminal(Terminal : string) ;
  end;

var
  DM: TDM;

implementation

uses TelaSplash;

{$R *.DFM}

function TDM.ConectaServidor : boolean ;
begin
  {Tenta conectar pra ver se o servidor esta Online se estiver inicia a transmissao!}
  if FileExists('c:\unit\gestao\online.txt') then
    result := true
  else
    result := false;
end;

function TDM.BloquearTerminal(Usuario, Terminal : string ) : boolean ;
begin
{
*** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **
* Esta rotina para bloquear o terminal da seguinte forma, quando se edita e    *
* grava * um dados de uma registro e se deixa a transação pendente o banco não *
* deixa editar * e gravar novamente o mesmo registro, portanto sai na rotina   *
* abaixo por except * e aasim podemos saber que em outro micro alguém já abriu *
* este terminal.                                                               *
*** * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * **
}
  {try
    DM.DatabaseTerm.StartTransaction ;
    DM.SQLTerminalAtivo.Edit ;
    DM.SQLTerminalAtivoTERMA255MSGCARNE.Value := DM.SQLTerminalAtivoTERMA255MSGCARNE.Value + '.' ;
    DM.SQLTerminalAtivo.Post ;
    BloquearTerminal := true ;
  except
    BloquearTerminal := false ;
  end ;}
  BloquearTerminal := true ;

  DM.SQLTemplate.Close ;
  DM.SQLTemplate.SQL.Clear ;
  DM.SQLTemplate.SQL.Add('update TERMINAL') ;
  DM.SQLTemplate.SQL.Add('set') ;
  DM.SQLTemplate.SQL.Add('TERMCATIVO = "S", ') ;
  DM.SQLTemplate.SQL.Add('USUAICODATIVO = ' + Usuario) ;
  DM.SQLTemplate.SQL.Add('where TERMICOD = ' + Terminal) ;
  try
    DM.SQLTemplate.ExecSQL ;
  except
    on E: Exception do
    begin
      ShowMessage('Problemas ao bloquear terminal: ' + #13 + E.Message) ;
    end ;
  end ;
end ;

procedure TDM.DesbloquearTerminal(Terminal : string) ;
begin
  {if DatabaseTerm.InTransaction then
    DatabaseTerm.Rollback ;}

  DM.SQLTemplate.Close ;
  DM.SQLTemplate.SQL.Clear ;
  DM.SQLTemplate.SQL.Add('update TERMINAL') ;
  DM.SQLTemplate.SQL.Add('set') ;
  DM.SQLTemplate.SQL.Add('TERMCATIVO = "N", ') ;
  DM.SQLTemplate.SQL.Add('USUAICODATIVO = Null') ;
  DM.SQLTemplate.SQL.Add('where TERMICOD = ' + Terminal) ;
  try
    DM.SQLTemplate.ExecSQL ;
  except
    on E: Exception do
    begin
      ShowMessage('Problemas ao desbloquear terminal: ' + #13 + E.Message) ;
    end ;
  end ;
end ;

procedure TDM.DataModuleCreate(Sender: TObject);
var IniFile: Tinifile;
var DiaSemana : string;
begin
  inherited;
  FormSplash.lbDados.Caption := 'Abrindo Tabela de Filiais...'; FormSplash.lbDados.Update;
  SQLEmpresa.Open ;
  FormSplash.lbDados.Caption := 'Abrindo Tabela de Terminais...'; FormSplash.lbDados.Update;
  SQLTerminalAtivo.Open ;
  FormSplash.lbDados.Caption := 'Abrindo Tabela de Usuarios...'; FormSplash.lbDados.Update;
  SQLUsuario.Open ;
  FormSplash.lbDados.Caption := 'Abrindo Tabela de Parametros...'; FormSplash.lbDados.Update;
  SQLConfigGeral.Open ;
  SQLConfigCrediario.Open ;
  SQLConfigVenda.Open ;
  SQLConfigCompra.Open;
  SQLOperacaoCaixa.Open ;
  SQLPopUP.Open;

  DBRel.Connected := True ;

  FormSplash.lbDados.Caption := 'Verificando Licença de uso...'; FormSplash.lbDados.Update;
  if FileExists('Licenca.dll') and (SQLConfigGeralCFGEDBLOQ.AsString = '') then
    begin
      SQLConfigGeral.Edit;
      SQLConfigGeralCFGEDBLOQ.AsString := FormatDateTime('dd/mm/yyyy',Now+90);
      SQLConfigGeral.Post;
    end;

  DiaSemana := FormatDateTime('ddd',now);
  if FileExists('Licenca.dll') and (SQLConfigGeralCFGECBLOQ.AsString <> 'S') and (SQLConfigGeralCFGEDBLOQ.Value < Now) and (DiaSemana <> 'sáb') and (DiaSemana <> 'dom') then
    begin
      SQLConfigGeral.Edit;
      SQLConfigGeralCFGECBLOQ.AsString := 'S';
      SQLConfigGeral.Post;
    end;
  FormSplash.lbDados.Caption := 'Licença de uso Válida até => '+FormatDateTime('dd/mm/yyyy',SQLConfigGeralCFGEDBLOQ.Value) ; FormSplash.lbDados.Update;
  Sleep(1000);
  FormSplash.close;
end;

procedure TDM.SQLCupomNewRecord(DataSet: TDataSet);
begin
  inherited;
  SQLCupomCUPON2TOTITENS.Value    := 0 ;
  SQLCupomCUPON2DESC.Value        := 0 ;
  SQLCupomCUPON2ACRESC.Value      := 0 ;
  SQLCupomCUPON2TOTITENSRET.Value := 0 ;
  SQLCupomCUPON2CONVTAXA.Value    := 0 ;
  SQLCupomCUPOINROORDCOMPRA.Value := 0 ;
  SQLCupomCUPON2VLRCOMISSAO.Value := 0 ;
  SQLCupomCUPON2JUROATRAS.Value   := 0 ;
  SQLCupomCUPON2MULTAATRAS.Value  := 0 ;
  SQLCupomCUPON3CREDTAXA.Value    := 0 ;
  SQLCupomCUPOCCONSIG.Value       := 'N';
end;

procedure TDM.SQLCupomBeforePost(DataSet: TDataSet);
begin
  inherited;
  Case DataSet.State Of
    DsInsert: CodigoAutomatico('CUPOM', DSSQLCupom, DataSet, 3, 0);
  end ;
  CodNextCupom := DataSet.FIelds[0].AsString ;
end;

procedure TDM.SQLCupomItemNewRecord(DataSet: TDataSet);
begin
  inherited;
  SQLCupomItemCPITCSTATUS.Value       := 'A' ;
  SQLCupomItemCPITN3QTD.Value         := 0 ;
  SQLCupomItemCPITN3QTDTROCA.Value    := 0 ;
  SQLCupomItemCPITN3VLRUNIT.Value     := 0 ;
  SQLCupomItemCPITN3VLRCUSTUNIT.Value := 0 ;
  SQLCupomItemCPITN2DESC.Value        := 0 ;
  SQLCupomItemCPITN3VLRUNITLUCR.Value := 0 ;
  SQLCupomItemCOITN2ICMSALIQ.Value    := 0 ;
end ;

procedure TDM.SQLContasReceberBeforePost(DataSet: TDataSet);
begin
  inherited;
  {Case DataSet.State Of
    DsInsert: if (DataSet.Tag in [1,2,3]) Then
                CodigoAutomatico('CONTASRECEBER', DSSQLContasReceber, DataSet, 3, 0);
  end ;}
end;

procedure TDM.SQLContasReceberNewRecord(DataSet: TDataSet);
begin
  inherited;
  SQLContasReceberCTRCN2VLR.Value          := 0 ;
  SQLContasReceberCTRCN2DESCFIN.Value      := 0 ;
  SQLContasReceberCTRCN2TXJURO.Value       := 0 ;
  SQLContasReceberCTRCN2TXMULTA.Value      := 0 ;
  SQLContasReceberCTRCN2TOTREC.Value       := 0 ;
  SQLContasReceberCTRCN2TOTJUROREC.Value   := 0 ;
  SQLContasReceberCTRCN2TOTMULTAREC.Value  := 0 ;
  SQLContasReceberCTRCN2TOTDESCREC.Value   := 0 ;
  SQLContasReceberCTRCN2TOTMULTACOBR.Value := 0 ;
end;

procedure TDM.SQLCupomNumerarioNewRecord(DataSet: TDataSet);
begin
  inherited;
  SQLCupomNumerarioCONMCSTATUS.Value := 'A' ;
end;

procedure TDM.SQLContasReceberPostError(DataSet: TDataSet;
  E: EDatabaseError; var Action: TDataAction);
begin
  inherited;
  {if (E is EDatabaseError) then
  begin
    if (E is EDBEngineError) then
    begin
      with E as EDBEngineError do
      begin
        case Errors[0].ErrorCode of
          dbierr_keyviol: if (DataSet.Tag in [1,2,3]) then
                            begin
                              DM.CodigoAutomatico('CONTASRECEBER', DSSQLContasReceber, DataSet, 3, 0);
                              CodNextCupom := DataSet.FIelds[0].AsString ;
                              Action       := DaRetry ;
                            end ;
        end ;
      end ;
    end ;
  end ;}
end;

procedure TDM.SQLPedidoVendaBeforePost(DataSet: TDataSet);
begin
  inherited;
  Case DataSet.State Of
    DsInsert: if (DataSet.Tag in [1,2,3]) Then
                CodigoAutomatico('PEDIDOVENDA', DSSQLPedidoVenda, DataSet, 2, 0);
  end ;
  CodNextOrc := DataSet.FIelds[0].AsString ;
end;

procedure TDM.SQLPedidoVendaPostError(DataSet: TDataSet; E: EDatabaseError;
  var Action: TDataAction);
begin
  inherited;
  if (E is EDatabaseError) then
  begin
    if (E is EDBEngineError) then
    begin
      with E as EDBEngineError do
      begin
        if Errors[0].ErrorCode = DBIERR_KEYVIOL then
        begin
          if (DataSet.Tag in [1,2,3]) then
          begin
            DM.CodigoAutomatico('PEDIDOVENDA', DSSQLPedidoVenda, DataSet, 2, 0);
            CodNextOrc := DataSet.FIelds[0].AsString ;
            Action       := DaRetry ;
          end ;
       end
       else ShowMessage('Problemas ao gravar o Cabecalho do Orçamento :' + #13 + Errors[0].Message) ;
      end ;
    end ;
  end ;
end;

procedure TDM.TblPedidoCabCalcFields(DataSet: TDataSet);
begin
  inherited;
  TblPedidoCabTotalGeral.Value := TblPedidoCabTotal.Value -
                                  TblPedidoCabTotalDesconto.Value +
                                  TblPedidoCabValorFrete.Value ;
end;

procedure TDM.SQLFechamentoCaixaBeforePost(DataSet: TDataSet);
begin
  inherited;
  DataSet.FieldByName('PENDENTE').AsString   := 'S';
  DataSet.FieldByName('REGISTRO').AsDateTime := Now;
  Dm.CodigoAutomatico('FECHAMENTOCAIXA',Nil,DataSet,5,0);
end;

end.

