ALTER TABLE CLIENTE ALTER CLIECTPPRCVENDA TO CLIECTPPRCVENDA2;
commit work;
ALTER TABLE CLIENTE ADD CLIECTPPRCVENDA CHAR(02);
cOMMIT WORK;
update CLIENTE SET CLIECTPPRCVENDA = CLIECTPPRCVENDA2;
COMMIT WORK;
ALTER TABLE CLIENTE DROP CLIECTPPRCVENDA2;
COMMIT WORK;

