CREATE TABLE RESERVA (
  RESEICOD INTEGER NOT NULL,
  RESEDDATAHORA TIMESTAMP,
  RESEA60NOME VARCHAR(60),
  RESEA15FONE VARCHAR(60),
  RESEINROPESSOAS INTEGER,
  RESECFUMANTE VARCHAR(1),
  RESECCADEIRACRIA VARCHAR(1),
  RESECCADEIRADEFI VARCHAR(1),
  RESETOBS VARCHAR(255),
  PRIMARY KEY (RESEICOD));