create table KMDIA(
KMDIA13ID char(13) NOT NULL,
EMPRICOD INTEGER NOT NULL,
KMDIICOD INTEGER NOT NULL,
KMDIDDATA DATE,
KMDICSTATUS CHAR(01),
FUNCA13ID CHAR(13),
KMDIIINICIAL INTEGER,
KMDIIFINAL INTEGER,
REGISTRO DATE,
PENDENTE CHAR(01),
primary key (KMDIA13ID)
)