CREATE TABLE MESA (
  MESAICOD        INTEGER NOT NULL,
  MESAICAPAC      INTEGER,
  MESACSTATUS     CHAR(01),
  MESADABERTURA   DATE,
  MESADULTPED     DATE,
  MESADFECHAMENTO DATE,
  MESAN3VLRTOTAL  NUMERIC(15,3),
  PRIMARY KEY (MESAICOD));