program Loja;

uses
  VarSYS,
  Forms,
  Windows,
  SysUtils,
  Variants,
  DataModuloTemplate in '..\..\Template\DataModuloTemplate.pas' {DMTemplate: TDataModule},
  CadastroTEMPLATE in '..\..\Template\CadastroTEMPLATE.pas' {FormCadastroTemplate},
  PrincipalTemplate in '..\..\Template\PrincipalTemplate.pas' {FormPrincipalTemplate},
  FormResources in '..\..\Template\FormResources.pas',
  TelaGeralTEMPLATE in '..\..\Template\TelaGeralTEMPLATE.pas' {FormTelaGeralTEMPLATE},
  CadastroGrade in '..\ArquivosComuns\CadastroGrade.pas' {FormCadastroGrade},
  CadastroMarca in '..\ArquivosComuns\CadastroMarca.pas' {FormCadastroMarca},
  CadastroICMS in '..\ArquivosComuns\CadastroICMS.pas' {FormCadastroICMS},
  CadastroGrupo in '..\ArquivosComuns\CadastroGrupo.pas' {FormCadastroGrupo},
  CadastroCliente in '..\ArquivosComuns\CadastroCliente.pas' {FormCadastroCliente},
  Principal in 'Principal.pas' {FormPrincipal},
  TelaLogin in 'TelaLogin.pas' {FormTelaLogin},
  CadastroIcmsUf in '..\ArquivosComuns\CadastroIcmsUf.pas' {FormCadastroIcmsUF},
  CadastroClassificacaoFiscal in '..\ArquivosComuns\CadastroClassificacaoFiscal.pas' {FormCadastroClassificacaoFiscal},
  CadastroUsuario in '..\ArquivosComuns\CadastroUsuario.pas' {FormCadastroUsuario},
  CadastroTamanho in '..\ArquivosComuns\CadastroTamanho.pas' {FormCadastroTamanho},
  CadastroCor in '..\ArquivosComuns\CadastroCor.pas' {FormCadastroCor},
  CadastroVariacao in '..\ArquivosComuns\CadastroVariacao.pas' {FormCadastroVariacao},
  ComCtrls in 'ComCtrls.pas',
  CadastroSubgrupo in '..\ArquivosComuns\CadastroSubgrupo.pas' {FormCadastroSubgrupo},
  CadastroUnidade in '..\ArquivosComuns\CadastroUnidade.pas' {FormCadastroUnidade},
  CadastroTipoCliente in '..\ArquivosComuns\CadastroTipoCliente.pas' {FormCadastroTipoCliente},
  RelatorioTemplate in '..\..\Template\RelatorioTemplate.pas' {FormRelatorioTEMPLATE},
  RelatorioVendasPeriodo in '..\ArquivosComuns\RelatorioVendasPeriodo.pas' {FormRelatorioVendasPeriodo},
  RelatorioMovimentacaoCaixa in 'RelatorioMovimentacaoCaixa.pas' {FormRelatorioMovimentacaoCaixa},
  RelatorioBoletimCaixa in 'RelatorioBoletimCaixa.pas' {FormRelatorioBoletimCaixa},
  RelatorioProdutosVendidos in '..\ArquivosComuns\RelatorioProdutosVendidos.pas' {FormRelatorioProdutosVendidos},
  RelatorioVendasPorPlano in '..\ArquivosComuns\RelatorioVendasPorPlano.pas' {FormRelatorioVendasPorPlano},
  RelatorioInventarioEstoque in '..\ArquivosComuns\RelatorioInventarioEstoque.pas' {FormRelatorioInventarioEstoque},
  CadastroMovimentosDiversosEstoque in '..\ArquivosComuns\CadastroMovimentosDiversosEstoque.pas' {FormCadastroMovimentosDiversosEstoque},
  DataModulo in 'DataModulo.pas' {DM: TDataModule},
  RelatorioComissao in 'RelatorioComissao.pas' {FormRelatorioComissao},
  CadastroProfissional in '..\SISCON\CadastroProfissional.pas' {FormCadastroProfissional},
  TelaCalculoComissao in 'TelaCalculoComissao.pas' {FormTelaCalculoComissao},
  CadastroProfissao in '..\ArquivosComuns\CadastroProfissao.pas' {FormCadastroProfissao},
  CadastroMotivoBloqueio in '..\ArquivosComuns\CadastroMotivoBloqueio.pas' {FormCadastroMotivoBloqueio},
  CadastroClienteDependente in '..\ArquivosComuns\CadastroClienteDependente.pas' {FormCadastroClienteDependente},
  CadastroClienteReferencia in '..\ArquivosComuns\CadastroClienteReferencia.pas' {FormCadastroClienteReferencia},
  CadastroProdutoFornecedor in '..\ArquivosComuns\CadastroProdutoFornecedor.pas' {FormCadastroProdutoFornecedor},
  CadastroClienteContato in '..\ArquivosComuns\CadastroClienteContato.pas' {FormCadastroClienteContato},
  UnitLibrary in '..\ArquivosComuns\UnitLibrary.pas',
  CadastroCupom in '..\ArquivosComuns\CadastroCupom.pas' {FormCadastroCupom},
  TelaGeralExecutarSQL in '..\ArquivosComuns\TelaGeralExecutarSQL.pas' {FormTelaGeralExecutarSQL},
  TelaCriacaoGrade in '..\ArquivosComuns\TelaCriacaoGrade.pas' {FormTelaCriacaoGrade},
  CadastroMovimentosDiversosEstoqueItem in '..\ArquivosComuns\CadastroMovimentosDiversosEstoqueItem.pas' {FormCadastroMovimentosDiversosEstoqueItem},
  CadastroTipoVenda in 'CadastroTipoVenda.pas' {FormCadastroTipoVenda},
  CadastroClasse in '..\ArquivosComuns\CadastroClasse.pas' {FormCadastroClasse},
  CadastroClasseUsuario in '..\ArquivosComuns\CadastroClasseUsuario.pas' {FormCadastroClasseUsuario},
  RelatorioListagemProduto in '..\ArquivosComuns\RelatorioListagemProduto.pas' {FormRelatorioListagemProduto},
  TelaDadosVersaoLoja in 'TelaDadosVersaoLoja.pas' {FormTelaDadosVersaoLoja},
  CadastroManutencaoCupom in '..\ArquivosComuns\CadastroManutencaoCupom.pas' {FormCadastroManutencaoCupom},
  CadastroManutencaoContasReceber in '..\ArquivosComuns\CadastroManutencaoContasReceber.pas' {FormCadastroManutencaoContasReceber},
  CadastroConsulta in '..\ArquivosComuns\CadastroConsulta.pas' {FormCadastroConsulta},
  TelaRecalcularTotalizador in 'TelaRecalcularTotalizador.pas' {FormTelaRecalcularTotalizador},
  TelaConsultaTemplate in '..\..\Template\TelaConsultaTemplate.pas' {FormTelaConsultaTemplate},
  TelaConsultaTabelaPreco in '..\ArquivosComuns\TelaConsultaTabelaPreco.pas' {FormTelaConsultaTabelaPreco},
  CadastroProdutoTabelaPreco in '..\ArquivosComuns\CadastroProdutoTabelaPreco.pas' {FormCadastroProdutoTabelaPreco},
  TelaAtualizarSaldoDiarioProduto in '..\ArquivosComuns\TelaAtualizarSaldoDiarioProduto.pas' {FormTelaAtualizarSaldoDiarioProduto},
  CadastroProdutoComposicao in '..\ArquivosComuns\CadastroProdutoComposicao.pas' {FormCadastroProdutoComposicao},
  TelaConsultaProduto in '..\ArquivosComuns\TelaConsultaProduto.pas' {FormTelaConsultaProduto},
  RelatorioVendasConsignadas in '..\ArquivosComuns\RelatorioVendasConsignadas.pas' {FormRelatorioVendasConsignadas},
  RelatorioClienteCadastrado in '..\ArquivosComuns\RelatorioClienteCadastrado.pas' {FormRelatorioClienteCadastrado},
  RelatorioVendasPeriodoApuracaoMargem in '..\ArquivosComuns\RelatorioVendasPeriodoApuracaoMargem.pas' {FormRelatorioVendasPeriodoApuracaoMargem},
  CadastroContaCorrente in '..\UnitFinanceiro\CadastroContaCorrente.pas' {FormCadastroContaCorrente},
  TelaConsultaNumerario in '..\ArquivosComuns\TelaConsultaNumerario.pas' {FormTelaConsultaNumerario},
  TelaConsultaConsignacoesPendentes in '..\ArquivosComuns\TelaConsultaConsignacoesPendentes.pas' {FormTelaConsultaConsignacoesPendentes},
  RelatorioExtratoMovimentoBanco in '..\UnitFinanceiro\RelatorioExtratoMovimentoBanco.pas' {FormRelatorioExtratoMovimentoBanco},
  TelaReabilitacaoCredito in '..\UnitCrediario\TelaReabilitacaoCredito.pas' {FormTelaReabilitacaoCredito},
  TelaDadosVersaoCrediario in '..\UnitCrediario\TelaDadosVersaoCrediario.pas' {FormTelaDadosVersaoCrediario},
  TelaEnvioCartasAviso in '..\UnitCrediario\TelaEnvioCartasAviso.pas' {FormTelaEnvioCartasAviso},
  RelatorioReabilitacaoSPC in '..\UnitCrediario\RelatorioReabilitacaoSPC.pas' {FormRelatorioReabilitacaoSPC},
  TelaEnvioEmail in '..\ArquivosComuns\TelaEnvioEmail.pas' {FormTelaEnvioGeracaoEmail},
  ExtensoLib in '..\ArquivosComuns\ExtensoLib.pas',
  TelaEnvioEmailGeral in '..\ArquivosComuns\TelaEnvioEmailGeral.pas' {FormTelaEnvioEmailGeral},
  TelaEmissaoEtiquetasCodigoBarras in '..\ArquivosComuns\TelaEmissaoEtiquetasCodigoBarras.pas' {FormTelaEmissaoEtiquetasCodigoBarras},
  TelaConsultaPedidoCompra in '..\ArquivosComuns\TelaConsultaPedidoCompra.pas' {FormTelaConsultaPedidoCompra},
  TelaConsultaNotaCompra in '..\ArquivosComuns\TelaConsultaNotaCompra.pas' {FormTelaConsultaNotaCompra},
  TelaConsultaPedidoVenda in '..\ArquivosComuns\TelaConsultaPedidoVenda.pas' {FormTelaConsultaPedidoVenda},
  TelaConsultaNotaFiscal in '..\ArquivosComuns\TelaConsultaNotaFiscal.pas' {FormTelaConsultaNotaFiscal},
  CadastroCep in '..\ArquivosComuns\CadastroCep.pas' {FormCadastroCep},
  TelaReajustePreco in '..\UnitCompras\TelaReajustePreco.pas' {FormTelaReajustePreco},
  TelaManutencaoProdutos in '..\ArquivosComuns\TelaManutencaoProdutos.pas' {FormTelaManutencaoProdutos},
  RelatorioProdutosPorFornecedor in '..\ArquivosComuns\RelatorioProdutosPorFornecedor.pas' {FormRelatorioProdutosPorFornecedor},
  TelaManutencaoFechamentoCaixa in '..\UnitCheckout\TelaManutencaoFechamentoCaixa.pas' {FormTelaManutencaoFechamentoCaixa},
  TelaZerarSaldoEstoque in 'TelaZerarSaldoEstoque.pas' {FormTelaZeraSaldoEstoque},
  RelatorioClientesSPC in 'RelatorioClientesSPC.pas' {FormRelatorioClientesSPC},
  TelaImpressaoTermicaCodBar in '..\ArquivosComuns\TelaImpressaoTermicaCodBar.pas' {FormTelaImpressaoTermicaCodBar},
  TelaContagemManual in 'TelaContagemManual.pas' {FormTelaContagemManual},
  RelatorioDivergenciaInventario in 'RelatorioDivergenciaInventario.pas' {FormRelatorioDivergenciaInventario},
  RelatorioCurvaABC in 'RelatorioCurvaABC.pas' {FormRelatorioCurvaABC},
  SWEDA7000 in '..\UnitCheckout\SWEDA7000.pas',
  TelaMapaResumo in 'TelaMapaResumo.pas' {FormTelaGeracaoMapaResumo},
  RelatorioFisicoFinanceiroEstoque in 'RelatorioFisicoFinanceiroEstoque.pas' {FormRelatorioFisicoFinanceiroEstoque},
  TelaAtualizacaoCEP in '..\ArquivosComuns\TelaAtualizacaoCEP.pas' {FormTelaAtualizacaoCEP},
  RelatorioVendasPorGrade in 'RelatorioVendasPorGrade.pas' {FormRelatorioVendasPorGrade},
  RelatorioReceitasDespesasPlanoContas in '..\UnitFinanceiro\RelatorioReceitasDespesasPlanoContas.pas' {FormRelatorioReceitasDespesasPlanoContas},
  RelatorioRegistroInventario in 'RelatorioRegistroInventario.pas' {FormRelatorioRegistroInventario},
  RelatorioExtratoProdutos in 'RelatorioExtratoProdutos.pas' {FormRelatorioExtratoProdutos},
  RelatorioEstoquePorGrade in 'RelatorioEstoquePorGrade.pas' {FormRelatorioEstoquePorGrade},
  WindowsLibrary in '..\ArquivosComuns\WindowsLibrary.pas',
  CadastroLote in 'CadastroLote.pas' {FormCadastroLote: Unit1},
  RelatorioEstoquePorLote in 'RelatorioEstoquePorLote.pas' {FormRelatorioEstoquePorLote},
  RelatorioConsignacaoVendaConsignacao in '..\UnitFaturamento\RelatorioConsignacaoVendaConsignacao.pas' {FormRelatorioConsignacaoVendaConsignacao},
  RelatorioLotePorProduto in 'RelatorioLotePorProduto.pas' {FormRelatorioLotePorProduto},
  RelatorioFluxoCaixa in '..\UnitFinanceiro\RelatorioFluxoCaixa.pas' {FormRelatorioFluxoCaixa},
  RelatorioClienteBloqueado in '..\ArquivosComuns\RelatorioClienteBloqueado.pas' {FormRelatorioClienteBloqueado},
  RelatorioVendasGrupo in '..\ArquivosComuns\RelatorioVendasGrupo.pas' {FormRelatorioVendasGrupo},
  PertoCheque in '..\ArquivosComuns\PertoCheque.pas',
  TelaImportaItens in '..\ArquivosComuns\TelaImportaItens.pas' {FormTelaImportaItens},
  WaitWindow in '..\ArquivosComuns\WaitWindow.pas',
  RelatorioTotalNumerarioCaixa in 'RelatorioTotalNumerarioCaixa.pas' {FormRelatorioTotalNumerarioCaixa},
  TelaAtualizaPrecoProduto in '..\ArquivosComuns\TelaAtualizaPrecoProduto.pas' {FormTelaAtualizaPrecoProduto},
  CadastroImportaDados in '..\ArquivosComuns\CadastroImportaDados.pas' {FormCadastroImportaDados},
  CadastroImportaDadosCampos in '..\ArquivosComuns\CadastroImportaDadosCampos.pas' {FormCadastroImportaDadosCampos},
  TelaEmissaoEtiquetaGrade in 'TelaEmissaoEtiquetaGrade.pas' {FormTelaEmissaoEtiquetaGrade},
  TelaConsultaOperacaoEstoque in '..\ArquivosComuns\TelaConsultaOperacaoEstoque.pas' {FormTelaConsultaOperacaoEstoque},
  TelaConsultaEmpresa in '..\ArquivosComuns\TelaConsultaEmpresa.pas' {FormTelaConsultaEmpresa},
  TelaConsultaPlanoRecebimento in '..\ArquivosComuns\TelaConsultaPlanoRecebimento.pas' {FormTelaConsultaPlanoRecebimento},
  RelatorioClientesPorCidade in 'RelatorioClientesPorCidade.pas' {FormRelatorioClienteporCidade},
  RelatorioPosicaoDiariaEstoque in 'RelatorioPosicaoDiariaEstoque.pas' {FormRelatorioPosicaoDiariaEstoque},
  ECF_AFRAC in '..\UnitCheckout\ECF_AFRAC.pas',
  TelaConsultaPlanoContas in '..\ArquivosComuns\TelaConsultaPlanoContas.pas' {FormTelaConsultaPlanoContas},
  TelaImpressaoDuplicatas in '..\UnitFinanceiro\TelaImpressaoDuplicatas.pas' {FormTelaImpressaoDuplicata},
  CadastroBanco in '..\ArquivosComuns\CadastroBanco.pas' {FormCadastroBanco},
  CadastroTipoFornecedor in '..\ArquivosComuns\CadastroTipoFornecedor.pas' {FormCadastroTipoFornecedor},
  CadastroTipoCusto in '..\ArquivosComuns\CadastroTipoCusto.pas' {FormCadastroTipoCusto},
  RelatorioPlanilhaVendasExternas in 'RelatorioPlanilhaVendasExternas.pas' {FormRelatorioPlanilhaMensalVendas},
  CadastroClienteHistorico in 'CadastroClienteHistorico.pas' {FormCadastroClienteHistorico},
  TelaAgendaCobranca in 'TelaAgendaCobranca.pas' {FormTelaAgendamentoCobranca},
  TelaClienteHistorico in '..\ArquivosComuns\TelaClienteHistorico.pas' {FormTelaClienteHistorico},
  CadastroCobrador in 'CadastroCobrador.pas' {FormCadastroCobrador},
  TelaAnaliseCobranca in 'TelaAnaliseCobranca.pas' {FormTelaAnaliseCobranca},
  TelaConsultaCobrador in 'TelaConsultaCobrador.pas' {FormTelaConsultaCobrador},
  RelatorioComissaoCobrador in 'RelatorioComissaoCobrador.pas' {FormRelatorioComissaoCobranca},
  TelaDadosTeleEntrega in '..\UnitCheckout\TelaDadosTeleEntrega.pas' {FormTelaDadosTeleEntrega},
  TelaLancamentoGradeMovto in '..\ArquivosComuns\TelaLancamentoGradeMovto.pas' {FormTelaLancamentoGradeMovto},
  RelatorioEstoquePorMarcaPorGrupo in '..\Config\RelatorioEstoquePorMarcaPorGrupo.pas' {FormRelatorioEstoquePorMarcaPorGrupo},
  RelatorioEstoqueMarcaReferencia in 'RelatorioEstoqueMarcaReferencia.pas' {FormRelatorioEstoqueMarcaReferencia},
  RelatorioCupomEmitido in 'RelatorioCupomEmitido.pas' {FormRelatorioCupomEmitido},
  RelatorioResumoOperacaoDiaria in 'RelatorioResumoOperacaoDiaria.pas' {FormRelatorioResumoOperacaoDiaria},
  RelatorioProdutoCadastrado in 'RelatorioProdutoCadastrado.pas' {FormRelatorioProdutoCadastrado},
  RelatorioEstoquePorMarca in 'RelatorioEstoquePorMarca.pas' {FormRelatorioEstoquePorMarca},
  CadastroVendedorComissao in '..\ArquivosComuns\CadastroVendedorComissao.pas' {FormCadastroVendedorComissao},
  TelaAtualizacaoMoeda in 'TelaAtualizacaoMoeda.pas' {FormTelaAtualizacaoMoeda},
  RelatorioComissaoDetalhado in 'RelatorioComissaoDetalhado.pas' {FormRelatorioComissaoDetalhado},
  RelatorioListagemParaInventarioPorGradePorProduto in 'RelatorioListagemParaInventarioPorGradePorProduto.pas' {FormRelatorioListagemParaInventarioPorGradePorProduto},
  TelaImpressaoDadosVenda in '..\UnitCheckout\TelaImpressaoDadosVenda.pas' {FormTelaImpressaoDadosVenda},
  TelaNegociacaoDivida in '..\ArquivosComuns\TelaNegociacaoDivida.pas' {FormTelaNegociacaoDivida},
  RelatorioApuracaoICMS in 'RelatorioApuracaoICMS.pas' {FormRelatorioApuracaoICMS},
  RelatorioTeleEntrega in 'RelatorioTeleEntrega.pas' {FormRelatorioTeleEntrega},
  RelatorioVendaPorCliente in 'RelatorioVendaPorCliente.pas' {FormRelatorioVendaPorCliente},
  RelatorioCupomQuitado in 'RelatorioCupomQuitado.pas' {FormRelatorioCupomQuitado},
  CadastroFuncionario in '..\ArquivosComuns\CadastroFuncionario.pas' {FormCadastroFuncionario},
  CadastroFuncionarioContaCorrente in '..\ArquivosComuns\CadastroFuncionarioContaCorrente.pas' {FormCadastroFuncionarioContaCorrente},
  CadastroOperacaoFuncionario in '..\ArquivosComuns\CadastroOperacaoFuncionario.pas' {FormCadastroOperacaoFuncionario},
  CadastroVeiculo in '..\ArquivosComuns\CadastroVeiculo.pas' {FormCadastroVeiculo},
  RelatorioNotaFiscalCupomEmitidoPorCFOP in 'RelatorioNotaFiscalCupomEmitidoPorCFOP.pas' {FormRelatorioNotaFiscalEmitidaPorCFOP},
  RelatorioProdutoEmPromocao in 'RelatorioProdutoEmPromocao.pas' {FormRelatorioProdutoEmPromocao},
  RelatorioPontoDeEquilibrio in 'RelatorioPontoDeEquilibrio.pas' {FormRelatorioPontoDeEquilibrio},
  RelatorioEstoquePorGradePorProduto in 'RelatorioEstoquePorGradePorProduto.pas' {FormRelatorioEstoquePorGradePorProduto},
  TelaConfigControle in '..\ArquivosComuns\TelaConfigControle.pas' {FormTelaConfigControle},
  TelaProdutoNumeroSerieTEMP in '..\ArquivosComuns\TelaProdutoNumeroSerieTEMP.pas' {FormTelaGeralModalCadastroProdutoNumeroSerieTEMP},
  TelaConsultaNumeroSerie in '..\ArquivosComuns\TelaConsultaNumeroSerie.pas' {FormTelaConsultaNumeroSerie},
  CadastroProdutoSerie in 'CadastroProdutoSerie.pas' {FormCadastroProdutoSerie},
  TelaSelecaoProduto in '..\ArquivosComuns\TelaSelecaoProduto.pas' {FormTelaSelecaoProduto},
  TelaTransferenciaMercadoria in '..\ArquivosComuns\TelaTransferenciaMercadoria.pas' {FormTelaTransferencia},
  TelaTransferenciaMercadoriaReceberProduto in '..\ArquivosComuns\TelaTransferenciaMercadoriaReceberProduto.pas' {FormTelaTransferenciaMercadoriaReceberProduto},
  RelatorioTransferencia in 'RelatorioTransferencia.pas' {FormRelatorioTransferencia},
  RelatorioCartasAviso in 'RelatorioCartasAviso.pas' {FormRelatorioCartasAviso},
  CadastroTabelaPreco in '..\UnitCompras\CadastroTabelaPreco.pas' {FormCadastroTabelaPreco},
  CadastroTabelaPrecoProduto in '..\UnitCompras\CadastroTabelaPrecoProduto.pas' {FormCadastroTabelaPrecoProduto},
  TelaManutencaoTabelaPreco in '..\UnitCompras\TelaManutencaoTabelaPreco.pas' {FormTelaManutencaoTabelaPreco},
  RelatorioResumoCaixa in 'RelatorioResumoCaixa.pas' {FormRelatorioResumoCaixa},
  TelaQuitacaoComissoes in 'TelaQuitacaoComissoes.pas' {FormTelaQuitacaoComissoes},
  CadastroDecreto in '..\Config\CadastroDecreto.pas' {FormCadastroDecreto},
  RelatorioFornecedoresCadastrados in 'RelatorioFornecedoresCadastrados.pas' {FormRelatorioFornecedoresCadastrados},
  TelaRelGerConsultaPorPeriodo in '..\SISCON\TelaRelGerConsultaPorPeriodo.pas' {FormTelaRelGerConsultasPorPeriodo},
  TelaRelConsultaPeriodo in '..\SISCON\TelaRelConsultaPeriodo.pas' {FormTelaRelListConsultaPeriodo},
  TelaRelConsultaPeriodoAtendente in '..\SISCON\TelaRelConsultaPeriodoAtendente.pas' {FormTelaRelConsultaPeriodoAtendente},
  TelaGerenciamentoAcesso in '..\..\Template\TelaGerenciamentoAcesso.pas' {FormTelaGerenciamentoAcesso},
  RelatorioExtratoCliente in '..\ArquivosComuns\RelatorioExtratoCliente.pas' {FormRelatorioExtratoCliente},
  RelatorioIndiceInadimplenciaCrediario in '..\ArquivosComuns\RelatorioIndiceInadimplenciaCrediario.pas' {FormRelatorioIndiceInadimplenciaCrediario},
  CadastroColecao in '..\ArquivosComuns\CadastroColecao.pas' {FormCadastroColecao},
  TelaGeracaoMalaDireta in '..\ArquivosComuns\TelaGeracaoMalaDireta.pas' {FormTelaGeracaoMalaDireta},
  TelaConsultaSaldoPorEmpresa in 'TelaConsultaSaldoPorEmpresa.pas' {FormTelaConsultaSaldoPorEmpresa},
  RelatorioVendasMarca in '..\ArquivosComuns\RelatorioVendasMarca.pas' {FormRelatorioVendasMarca},
  RelatorioResumoVendasportipo in 'RelatorioResumoVendasportipo.pas' {FormRelatorioResumoVendasportipo},
  RelatorioResumoVendasporAliquota in 'RelatorioResumoVendasporAliquota.pas' {FormRelatorioResumoVendasporAliquota},
  RelatorioVendaPeriodoMenosRetorno in 'RelatorioVendaPeriodoMenosRetorno.pas' {FormRelatorioVendaPeriodoMenosRetorno},
  CadastroTanque in 'CadastroTanque.pas' {FormCadastroTanque},
  CadastroBomba in 'CadastroBomba.pas' {FormCadastroBomba},
  CadastroLivroLMC in 'CadastroLivroLMC.pas' {FormCadastroLivroLMC},
  CadastroLMC in 'CadastroLMC.pas' {FormCadastroLMC},
  RelatorioVendasColecao in '..\ArquivosComuns\RelatorioVendasColecao.pas' {FormRelatorioVendasColecao},
  TelaEmissaoMalaDiretaFornecedores in '..\ArquivosComuns\TelaEmissaoMalaDiretaFornecedores.pas' {FormTelaEmissaoMalaDiretaFornecedores},
  CadastroPedidoCompra in '..\UnitCompras\CadastroPedidoCompra.pas' {FormCadastroPedidoCompra},
  TelaLancamentoGradeNota in '..\UnitCompras\TelaLancamentoGradeNota.pas' {FormTelaLancamentoGradeNota},
  CadastroNotaCompra in '..\UnitCompras\CadastroNotaCompra.pas' {FormCadastroNotaCompra},
  CadastroNotaCompraFinanceiro in '..\UnitCompras\CadastroNotaCompraFinanceiro.pas' {FormCadastroNotaCompraFinanceiro},
  CadastroNotaCompraItem in '..\UnitCompras\CadastroNotaCompraItem.pas' {FormCadastroNotaCompraItem},
  CadastroPedidoCompraFinanceiro in '..\UnitCompras\CadastroPedidoCompraFinanceiro.pas' {FormCadastroPedidoCompraFinanceiro},
  CadastroPedidoCompraItem in '..\UnitCompras\CadastroPedidoCompraItem.pas' {FormCadastroPedidoCompraItem},
  TelaImportacaoPedidoCompra in '..\UnitCompras\TelaImportacaoPedidoCompra.pas' {FormTelaImportacaoPedidoCompra},
  TelaLancamentoGrade in '..\UnitCompras\TelaLancamentoGrade.pas' {FormTelaLancamentoGrade},
  CadastroTipoDocumento in '..\UnitFinanceiro\CadastroTipoDocumento.pas' {FormCadastroTipoDocumento},
  CadastroPortador in '..\UnitFinanceiro\CadastroPortador.pas' {FormCadastroPortador},
  RelatorioNotasCompra in '..\UnitCompras\RelatorioNotasCompra.pas' {FormRelatorioNotasCompra},
  RelatorioVendasComprasPorGrupo in '..\ArquivosComuns\RelatorioVendasComprasPorGrupo.pas' {FormRelatorioVendasComprasPorGrupo},
  CadastroRamo in '..\ArquivosComuns\CadastroRamo.pas' {FormCadastroRamo},
  CadastroSubRamo in '..\ArquivosComuns\CadastroSubRamo.pas' {FormCadastroSubRamo},
  CadastroFornecedorContato in '..\ArquivosComuns\CadastroFornecedorContato.pas' {FormCadastroFornecedorContato},
  CadastroContasPagar in '..\UnitFinanceiro\CadastroContasPagar.pas' {FormCadastroContasPagar},
  TelaBaixarDocumentosPagarPagamento in '..\UnitFinanceiro\TelaBaixarDocumentosPagarPagamento.pas' {FormTelaBaixaDocumentosPagarPagamento},
  TelaBaixarDocumentosPagar in '..\UnitFinanceiro\TelaBaixarDocumentosPagar.pas' {FormTelaBaixarDocumentosPagar},
  CadastroPlanodeContas in '..\UnitFinanceiro\CadastroPlanodeContas.pas' {FormCadastroPlanodeContas},
  TelaConsultaPagamento in '..\UnitFinanceiro\TelaConsultaPagamento.pas' {FormTelaConsultaPagamento},
  CadastroRecibo in '..\UnitFinanceiro\CadastroRecibo.pas' {FormCadastroRecibo},
  TelaBaixarDocumentosPlanoConta in '..\UnitFinanceiro\TelaBaixarDocumentosPlanoConta.pas' {FormTelaBaixarDocumentosPlanoConta},
  CadastroProfExterno in '..\ArquivosComuns\CadastroProfExterno.pas' {FormCadastroProfExterno},
  CadastroMateriais in '..\ArquivosComuns\CadastroMateriais.pas' {FormCadastroMateriais},
  CadastroMovimentosDiversosRapido in 'CadastroMovimentosDiversosRapido.pas' {FormTelaRapidaMovimentoDiverso},
  TelaEntradaRapidaEstoque in '..\ArquivosComuns\TelaEntradaRapidaEstoque.pas' {FormTelaEntradaRapidaEstoque},
  TelaFotoExpandida in '..\UnitCheckout\TelaFotoExpandida.pas' {FormTelaFotoExpandida},
  CadastroBarras in '..\ArquivosComuns\CadastroBarras.pas' {FormCadastroBarras},
  TelaGeralModalTemplate in '..\..\Template\TelaGeralModalTemplate.pas' {FormTelaGeralModalTemplate},
  CadastroReducaoZDia in 'CadastroReducaoZDia.pas' {FormCadastroReducaoZ},
  RelatorioMediaComprasPeriodo in 'RelatorioMediaComprasPeriodo.pas' {FormRelatorioMediaComprasPeriodo},
  TelaConsultaProdutoGeral in '..\ArquivosComuns\TelaConsultaProdutoGeral.pas' {FormTelaConsultaProdutoGeral},
  TelaEmissaoBonusCliente in '..\UnitAcesso\TelaEmissaoBonusCliente.pas' {FormTelaEmissaoBonusCliente},
  RelatorioComparativoICMS in 'RelatorioComparativoICMS.pas' {FormRelatorioComparativoICMSCompraVEnda},
  TelaExportacaoBalanca in '..\UnitIntegrador\TelaExportacaoBalanca.pas' {FormTelaExportacaoBalanca},
  CadastroRepresentante in '..\ArquivosComuns\CadastroRepresentante.pas' {FormCadastroRepresentante},
  TelaBaixaContasReceberAVista in '..\UnitFinanceiro\TelaBaixaContasReceberAVista.pas' {FormTelaBaixaContasReceberAVista},
  TelaBaixaContasPagarAVista in '..\UnitFinanceiro\TelaBaixaContasPagarAVista.pas' {FormTelaBaixaContasPagarAVista},
  CadastroTrocasItem in 'CadastroTrocasItem.pas' {FormCadastroTrocasItem},
  CadastroTrocas in 'CadastroTrocas.pas' {FormCadastroTrocas},
  TelaPedidoCompraHistoricoComprasVendasProduto in 'TelaPedidoCompraHistoricoComprasVendasProduto.pas' {FormTelaPedidoCompraHistoricoComprasVendasProduto},
  TelaAtualizaEstoquePDVs in '..\UnitAcesso\TelaAtualizaEstoquePDVs.pas' {FormTelaAtualizaEstoquePDVs},
  CadastroMotivoAfastamento in '..\Ponto\CadastroMotivoAfastamento.pas' {FormCadastroMotivoAfastamento},
  RelatorioCurvaABCEstoque in 'RelatorioCurvaABCEstoque.pas' {FormRelatorioCurvaABCEstoque},
  CadastroRota in '..\ArquivosComuns\CadastroRota.pas' {FormCadastroRota},
  CadastroCotacaoCompra in '..\UnitCompras\CadastroCotacaoCompra.pas' {FormCadastroCotacaoCompra},
  TelaCotacaoCompraItemFiltro in '..\UnitCompras\TelaCotacaoCompraItemFiltro.pas' {FormTelaCotacaoCompraItemFiltro},
  TelaCotacaoCompraItemFiltroDigForn in '..\UnitCompras\TelaCotacaoCompraItemFiltroDigForn.pas' {FormTelaCotacaoCompraItemFiltroDigForn},
  CadastroPrevenda in 'CadastroPrevenda.pas' {FormCadastroPrevenda},
  RelatorioContasaReceber in '..\UnitFinanceiro\RelatorioContasaReceber.pas' {FormRelatorioContasaReceber},
  RelatorioMovtoDiversos in 'RelatorioMovtoDiversos.pas' {FormRelatorioMotvoDiversos},
  TelaAutenticaUsuario in '..\UnitCheckout\TelaAutenticaUsuario.pas' {FormTelaAutenticaUsuario},
  RelatorioRegVendaAgrotoxico in 'RelatorioRegVendaAgrotoxico.pas' {FormRelatorioRegVendaAgrotoxico},
  CadastroMesa in 'CadastroMesa.pas' {FormCadastroMesa},
  RelatorioReducoesZ in 'RelatorioReducoesZ.pas' {FormRelatorioReducaoZ},
  RelatorioCaixasDigitados in 'RelatorioCaixasDigitados.pas' {FormRelatorioCaixasDigitados},
  CadastroReservaMesa in 'CadastroReservaMesa.pas' {FormCadastroReservaMesa},
  Cadastroagendatelefonica in '..\ArquivosComuns\CadastroAgendaTelefonica.pas' {formcadastroagendatelefonica},
  RelatorioComprasMarca in 'RelatorioComprasMarca.pas' {FormRelatorioComprasMarca},
  RelatorioComprasGrupo in 'RelatorioComprasGrupo.pas' {FormRelatorioComprasGrupo},
  RelatorioComprasColecao in 'RelatorioComprasColecao.pas' {FormRelatorioComprasColecao},
  RelatorioProdutosComprados in 'RelatorioProdutosComprados.pas' {FormRelatorioProdutosComprados},
  CadastroProdutos in '..\ArquivosComuns\CadastroProdutos.pas' {FormCadastroProduto},
  CadastroFornecedor in '..\ArquivosComuns\CadastroFornecedor.pas' {FormCadastroFornecedor},
  RelatorioCurvaABCCliente in 'RelatorioCurvaABCCliente.pas' {FormRelatorioCurvaABCCliente},
  TelaCadastroTarefa in '..\UnitTarefa\TelaCadastroTarefa.pas' {FormTelaCadastroTarefa},
  TelaConsultaTarefa in '..\UnitTarefa\TelaConsultaTarefa.pas' {FormTelaConsultaTarefa},
  TelaLembreteTarefa2 in '..\UnitTarefa\TelaLembreteTarefa2.pas' {FormTelaLembreteTarefa2},
  ConfigPopUp in '..\UnitTarefa\ConfigPopUp.pas' {FormConfigPopUp},
  TelaResumoFinanceiro in '..\ArquivosComuns\TelaResumoFinanceiro.pas' {FormTelaResumoFinanceiro},
  TelaConsultaRastreabilidade in 'TelaConsultaRastreabilidade.pas' {FormTelaConsultaRastreabilidade},
  RelatorioProdutosPedidosCompra in 'RelatorioProdutosPedidosCompra.pas' {FormRelatorioProdutosPedidosCompra},
  CadastroEncerranteDiario in 'CadastroEncerranteDiario.pas' {FormCadastroEncerranteDiario},
  TelaGerarSaldoProduto in '..\UnitCompras\TelaGerarSaldoProduto.pas' {FormTelaGerarSaldoProduto},
  TelaLembreteTarefa in '..\UnitTarefa\TelaLembreteTarefa.pas' {FormTelaLembreteTarefa},
  RelatorioClienteLimiteCreditoExcedido in 'RelatorioClienteLimiteCreditoExcedido.pas' {FormRelatorioClienteLimiteCreditoExcedido},
  CadastroClienteProduto in '..\ArquivosComuns\CadastroClienteProduto.pas' {FormCadastroClienteProduto},
  CadastroCurriculum in '..\ArquivosComuns\CadastroCurriculum.pas' {FormCadastroCurriculum},
  CadastroFeriado in '..\Ponto\CadastroFeriado.pas' {FormCadastroFeriado},
  CadastroHorario in '..\Ponto\CadastroHorario.pas' {FormCadastroHorario},
  CadastroManutPonto in '..\Ponto\CadastroManutPonto.pas' {FormCadastroManutPonto},
  CadastroNCM in '..\ArquivosComuns\CadastroNCM.pas' {FormCadastroNCM},
  RelatorioPontoFuncionario in 'RelatorioPontoFuncionario.pas' {FormRelatorioPontoFuncionario},
  CadastroClienteVeiculos in '..\ArquivosComuns\CadastroClienteVeiculos.pas' {FormCadastroClienteVeiculos},
  TelaSaidaRapidaEstoque in '..\ArquivosComuns\TelaSaidaRapidaEstoque.pas' {FormTelaSaidaRapidaEstoque},
  RelatorioApuracaoMargemPorProduto in 'RelatorioApuracaoMargemPorProduto.pas' {FormRelatorioApuracaoMargemPorProduto},
  CadastroConvenio in '..\Config\CadastroConvenio.pas' {FormCadastroConvenio},
  CadastroSerie in '..\Config\CadastroSerie.pas' {FormCadastroSerie},
  RelatorioContasReceberVencidas in '..\UnitFinanceiro\RelatorioContasReceberVencidas.pas' {FormRelatorioContasReceberVencidas},
  CadastroTipoRetorno in 'CadastroTipoRetorno.pas' {FormCadastroTipoRetorno},
  CadastroTipoContato in 'CadastroTipoContato.pas' {FormCadastroTipoContatoCobranca},
  TelaEnquadramentoClientes in 'TelaEnquadramentoClientes.pas' {FormTelaEnquadramentoClientes},
  TelaAgendaContatos in 'TelaAgendaContatos.pas' {FormTelaAgendaContatos},
  TelaHistoricoContato in 'TelaHistoricoContato.pas' {FormTelaHistoricoContato},
  TelaObservacaoProvisoria in 'TelaObservacaoProvisoria.pas' {FormTelaObservacaoProvisoria},
  ExportacaoProdutosGruposXML in 'ExportacaoProdutosGruposXML.pas' {FormExportacaoProdutosGruposXML},
  CadastroCSTConverte in '..\UnitFaturamento\CadastroCSTConverte.pas' {CadastroCSTConverter},
  CadastroCSTPisCofinsConverter in '..\UnitFaturamento\CadastroCSTPisCofinsConverter.pas' {CadastroCSTPisCofinsConverte},
  CadastroAnimaisRaca in '..\UnitPetShop\CadastroAnimaisRaca.pas' {FormCadastroAnimaisRaca},
  CadastroAnimaisEspecie in '..\UnitPetShop\CadastroAnimaisEspecie.pas' {FormCadastroAnimais_especie},
  CadastroAnimaisVacinacao in '..\UnitPetShop\CadastroAnimaisVacinacao.pas' {FormCadastroAnimaisVacinas},
  CadastroAnimaisAgenda in '..\UnitPetShop\CadastroAnimaisAgenda.pas' {FormCadastroAnimaisAgenda},
  CadastroAnimais in '..\UnitPetShop\CadastroAnimais.pas' {FormCadastroAnimais},
  TelaAvisoDebito in '..\UnitCheckout\TelaAvisoDebito.pas' {FormTelaAvisoDebito},
  TelaListaPreco in 'TelaListaPreco.pas' {FormTelaListaPreco},
  CadastroDisplay in '..\UnitCheckoutRest\CadastroDisplay.pas' {FormCadastroDisplay},
  CadastroMotoboy in '..\UnitCheckoutRest\CadastroMotoboy.pas' {FormCadastroMotoboy},
  TelaImportadorXML in 'TelaImportadorXML.pas' {FormTelaImportadorXML},
  RelatorioProdutosSemMovto in 'RelatorioProdutosSemMovto.pas' {FormRelatorioProdutosSemMovto},
  RelatorioApuracaoPISCOFINS in 'RelatorioApuracaoPISCOFINS.pas' {FormRelatorioApuracaoPisCofins},
  VinculoCfopOperacaoEstoque in 'VinculoCfopOperacaoEstoque.pas' {FormVinculoCfopOperacaoEstoque},
  RelatorioProdutosAbaixoMinimo in 'RelatorioProdutosAbaixoMinimo.pas' {FormRelatorioProdutosAbaixoMinimo},
  TelaPedidoCompraItemFiltro in 'TelaPedidoCompraItemFiltro.pas' {FormTelaPedidoCompraItemFiltro},
  PedidoCompraHistoricoCompra in 'PedidoCompraHistoricoCompra.pas' {FormPedidoCompraHistoricoCompra},
  RelatorioPrevendas in 'RelatorioPrevendas.pas' {FormRelatorioPrevendas},
  TelaAtivacao in '..\Ativador\TelaAtivacao.pas' {FormTelaAtivacao},
  CadastroClienteExtintor in '..\ArquivosComuns\CadastroClienteExtintor.pas' {FormCadastroClienteExtintor},
  TelaTransferenciaGrade in 'TelaTransferenciaGrade.pas' {FormTelaTransferenciaGrade},
  RelatorioContasRecebidas in '..\UnitFinanceiro\RelatorioContasRecebidas.pas' {FormRelatorioContasRecebidas},
  CadastroObsProdutoRest in '..\UnitCheckoutRest\CadastroObsProdutoRest.pas' {FormCadastroObsProdutoRest},
  TelaLancamentoGradeXML in '..\ArquivosComuns\TelaLancamentoGradeXML.pas' {FormTelaLancamentoGradeXML},
  TelaProdutosSemMovimento in 'TelaProdutosSemMovimento.pas' {FormTelaProdutosSemMov},
  CadastroProdutoRapido in 'CadastroProdutoRapido.pas' {FormCadastroProdutoRapido},
  TelaSplash in '..\ArquivosComuns\TelaSplash.pas' {FormSplash},
  RelatorioInadimplenciaAnual in 'RelatorioInadimplenciaAnual.pas' {FormRelatorioInadimplenciaAnual},
  RelatorioCupomEmitidoPorEmpresa in 'RelatorioCupomEmitidoPorEmpresa.pas' {FormRelatorioCupomEmitidoPorEmpresa},
  telaResumoLoja in 'telaResumoLoja.pas' {FormTelaResumoLoja},
  CadastroCidade in '..\ArquivosComuns\CadastroCidade.pas' {FormCadastroCidade},
  CadastroEmpresa in '..\Config\CadastroEmpresa.pas' {FormCadastroEmpresa},
  CadastroTabCest in '..\ArquivosComuns\CadastroTabCest.pas' {FormCadastroTabCEST},
  RelatorioVendasComprasPorProduto in '..\ArquivosComuns\RelatorioVendasComprasPorProduto.pas' {FormRelatorioVendasComprasPorProduto};

{$R *.RES}

var
  hMapping : hwnd ;
begin
  //Este código foi testado no arquivo dpr do projeto
  hMapping := CreateFileMapping(HWND($FFFFFFFF),
                                nil,
                                PAGE_READONLY,
                                0,
                                32,
                                PChar(ExtractFileName(Application.ExeName))) ;

  if (hMapping <> Null)  and (GetLastError <> 0) then
  begin
    // Informa('Gestão Empresarial - Módulo Administrativo já está sendo executado!') ;
    // if not Pergunta('NAO', 'O Módulo Administrativo já está sendo executado, deseja abrir outra cópia?') then
    // Halt ;
  end ;

  Application.Initialize;
  VersaoSistema := '3.2';
  Retaguarda := true;
  Enter := VK_Return;
  Application.Title := 'Módulo Administrativo';

  Application.CreateForm(TDM, DM);
  if dm.SQLConfigGeralCFGECBLOQ.AsString = 'S' then
    begin
      FormTelaAtivacao := TFormTelaAtivacao.Create(Application);
      FormTelaAtivacao.ShowModal;
      dm.Zdb.Connected := False;
      application.terminate;
    end;

  FormTelaLogin := TFormTelaLogin.Create(Application);
  FormTelaLogin.Caption := 'Bem Vindo ao Módulo Adminstrativo' ;
  if FormTelaLogin.ShowModal <> idOk then
    begin
      dm.Zdb.Connected := False;
      application.terminate;
    end;

  Application.CreateForm(TFormPrincipal, FormPrincipal);
  FormPrincipal.RodapePrincipal.Panels[0].Text := 'Empresa: '  +DM.SQLConfigGeralEmpresaPadraoCalcField.Value;
  FormPrincipal.RodapePrincipal.Panels[1].Text := 'Terminal: ' +Dm.SQLTerminalAtivoTERMA60DESCR.AsString;
  FormPrincipal.RodapePrincipal.Panels[2].Text := 'Usuário: '  +DM.SQLUsuarioUSUAA60LOGIN.Value;
  FormPrincipal.RodapePrincipal.Panels[4].Text := 'Validade da Licença: ' +DM.SQLConfigGeralCFGEDBLOQ.AsString;
  Application.Run ;
end.
