program UnitLoja;

uses
  VarSYS,
  Forms,
  Windows,
  DataModuloTemplate in '..\..\Template\DataModuloTemplate.pas' {DMTemplate: TDataModule},
  CadastroTEMPLATE in '..\..\Template\CadastroTEMPLATE.pas' {FormCadastroTemplate},
  PrincipalTemplate in '..\..\Template\PrincipalTemplate.pas' {FormPrincipalTemplate},
  FormResources in '..\..\Template\FormResources.pas',
  TelaGeralTEMPLATE in '..\..\Template\TelaGeralTEMPLATE.pas' {FormTelaGeralTEMPLATE},
  CadastroEmpresa in '..\ArquivosComuns\CadastroEmpresa.pas' {FormCadastroEmpresa},
  CadastroProdutos in '..\ArquivosComuns\CadastroProdutos.pas' {FormCadastroProduto},
  CadastroGrade in '..\ArquivosComuns\CadastroGrade.pas' {FormCadastroGrade},
  CadastroMarca in '..\ArquivosComuns\CadastroMarca.pas' {FormCadastroMarca},
  CadastroICMS in '..\ArquivosComuns\CadastroICMS.pas' {FormCadastroICMS},
  CadastroGrupo in '..\ArquivosComuns\CadastroGrupo.pas' {FormCadastroGrupo},
  CadastroCliente in '..\ArquivosComuns\CadastroCliente.pas' {FormCadastroCliente},
  Principal in 'Principal.pas' {FormPrincipal},
  TELALOGIN in '..\ArquivosComuns\TelaLogin.pas' {FormTelaLogin},
  CadastroIcmsUf in '..\ArquivosComuns\CadastroIcmsUf.pas' {FormCadastroIcmsUF},
  CadastroClassificacaoFiscal in '..\ArquivosComuns\CadastroClassificacaoFiscal.pas' {FormCadastroClassificacaoFiscal},
  CadastroTerminal in '..\ArquivosComuns\CadastroTerminal.pas' {FormCadastroTerminais},
  CadastroUsuario in '..\ArquivosComuns\CadastroUsuario.pas' {FormCadastroUsuario},
  CadastroEcf in 'CadastroEcf.pas' {FormCadastroEcf},
  CadastroFornecedor in '..\ArquivosComuns\CadastroFornecedor.pas' {FormCadastroFornecedor},
  CadastroTamanho in '..\ArquivosComuns\CadastroTamanho.pas' {FormCadastroTamanho},
  CadastroCor in '..\ArquivosComuns\CadastroCor.pas' {FormCadastroCor},
  CadastroVariacao in '..\ArquivosComuns\CadastroVariacao.pas' {FormCadastroVariacao},
  ComCtrls in 'ComCtrls.pas',
  CadastroSubgrupo in '..\ArquivosComuns\CadastroSubgrupo.pas' {FormCadastroSubgrupo},
  CadastroPlanoRecebimento in '..\ArquivosComuns\CadastroPlanoRecebimento.pas' {FormCadastroPlanoRecebimento},
  CadastroPlanoRecebimentoParcela in '..\ArquivosComuns\CadastroPlanoRecebimentoParcela.pas' {FormCadastroPlanoRecebimentoParcela},
  CadastroUnidade in '..\ArquivosComuns\CadastroUnidade.pas' {FormCadastroUnidade},
  CadastroTipoCliente in '..\ArquivosComuns\CadastroTipoCliente.pas' {FormCadastroTipoCliente},
  CadastroNumerario in 'CadastroNumerario.pas' {FormCadastroNumerario},
  CadastroTransportadora in '..\ArquivosComuns\CadastroTransportadora.pas' {FormCadastroTransportadora},
  CadastroOperacaoCaixa in 'CadastroOperacaoCaixa.pas' {FormCadastroOperacaoCaixa},
  CadastroTotalizadorCaixa in 'CadastroTotalizadorCaixa.pas' {FormCadastroTotalizadorCaixa},
  CadastroDecreto in '..\ArquivosComuns\CadastroDecreto.pas' {FormCadastroDecreto},
  TelaConfiguracaoGeral in 'TelaConfiguracaoGeral.pas' {FormTelaConfiguracaoGeral},
  RelatorioTemplate in '..\..\Template\RelatorioTemplate.pas' {FormRelatorioTEMPLATE},
  RelatorioVendasPeriodo in '..\ArquivosComuns\RelatorioVendasPeriodo.pas' {FormRelatorioVendasPeriodo},
  TelaConfiguracaoVenda in 'TelaConfiguracaoVenda.pas' {FormTelaConfiguracaoVenda},
  CadastroOperacoesEstoque in '..\ArquivosComuns\CadastroOperacoesEstoque.pas' {FormCadastroOperacoesEstoque},
  RelatorioMovimentacaoCaixa in 'RelatorioMovimentacaoCaixa.pas' {FormRelatorioMovimentacaoCaixa},
  RelatorioBoletimCaixa in 'RelatorioBoletimCaixa.pas' {FormRelatorioBoletimCaixa},
  RelatorioProdutosVendidos in '..\ArquivosComuns\RelatorioProdutosVendidos.pas' {FormRelatorioProdutosVendidos},
  RelatorioVendasPorPlano in '..\ArquivosComuns\RelatorioVendasPorPlano.pas' {FormRelatorioVendasPorPlano},
  RelatorioContasaReceber in '..\ArquivosComuns\RelatorioContasaReceber.pas' {FormRelatorioContasaReceber},
  RelatorioInventarioEstoque in '..\ArquivosComuns\RelatorioInventarioEstoque.pas' {FormRelatorioInventarioEstoque},
  CadastroECFAliquota in 'CadastroECFAliquota.pas' {FormCadastroECFAliquota},
  CadastroNumerarioTotalizadorECF in 'CadastroNumerarioTotalizadorECF.pas' {FormCadastroNumerarioTotalizadorECF},
  CadastroNumerarioTotalizadorCaixa in 'CadastroNumerarioTotalizadorCaixa.pas' {FormCadastroNumerarioTotalizadorCaixa},
  CadastroOperacaoCaixaTotalizadorCaixa in 'CadastroOperacaoCaixaTotalizadorCaixa.pas' {FormCadastroOperacaoCaixaTotalizadorCaixa},
  CadastroMovimentosDiversosEstoque in '..\ArquivosComuns\CadastroMovimentosDiversosEstoque.pas' {FormCadastroMovimentosDiversosEstoque},
  DataModulo in 'DataModulo.pas' {DM: TDataModule},
  CadastroBanco in '..\ArquivosComuns\CadastroBanco.pas' {FormCadastroBanco},
  RelatorioContasRecebidas in '..\ArquivosComuns\RelatorioContasRecebidas.pas' {FormRelatorioContasRecebidas},
  RelatorioContasReceberVencidas in '..\ArquivosComuns\RelatorioContasReceberVencidas.pas' {FormRelatorioContasReceberVencidas},
  RelatorioComissao in 'RelatorioComissao.pas' {FormRelatorioComissao},
  CadastroVendedor in '..\ArquivosComuns\CadastroVendedor.pas' {FormCadastroVendedor},
  TelaCalculoComissao in 'TelaCalculoComissao.pas' {FormTelaCalculoComissao},
  CadastroProfissao in '..\ArquivosComuns\CadastroProfissao.pas' {FormCadastroProfissao},
  CadastroMotivoBloqueio in '..\ArquivosComuns\CadastroMotivoBloqueio.pas' {FormCadastroMotivoBloqueio},
  CadastroClienteDependente in '..\ArquivosComuns\CadastroClienteDependente.pas' {FormCadastroClienteDependente},
  CadastroClienteReferencia in '..\ArquivosComuns\CadastroClienteReferencia.pas' {FormCadastroClienteReferencia},
  CadastroTipoFornecedor in '..\ArquivosComuns\CadastroTipoFornecedor.pas' {FormCadastroTipoFornecedor},
  CadastroTipoCusto in '..\ArquivosComuns\CadastroTipoCusto.pas' {FormCadastroTipoCusto},
  CadastroProdutoFornecedor in '..\ArquivosComuns\CadastroProdutoFornecedor.pas' {FormCadastroProdutoFornecedor},
  CadastroClienteContato in '..\ArquivosComuns\CadastroClienteContato.pas' {FormCadastroClienteContato},
  UnitLibrary in '..\ArquivosComuns\UnitLibrary.pas',
  CadastroCupom in '..\ArquivosComuns\CadastroCupom.pas' {FormCadastroCupom},
  CadastroEtiquetaCodigoBarras in '..\ArquivosComuns\CadastroEtiquetaCodigoBarras.pas' {FormCadastroEtiquetaCodigoBarras},
  TelaGeralExecutarSQL in '..\ArquivosComuns\TelaGeralExecutarSQL.pas' {FormTelaGeralExecutarSQL},
  TelaCriacaoGrade in '..\ArquivosComuns\TelaCriacaoGrade.pas' {FormTelaCriacaoGrade},
  CadastroPlanoPagamentoParcela in '..\ArquivosComuns\CadastroPlanoPagamentoParcela.pas' {FormCadastroPlanoPagamentoParcela},
  CadastroPlanoPagamento in '..\ArquivosComuns\CadastroPlanoPagamento.pas' {FormCadastroPlanoPagamento},
  CadastroMovimentosDiversosEstoqueItem in '..\ArquivosComuns\CadastroMovimentosDiversosEstoqueItem.pas' {FormCadastroMovimentosDiversosEstoqueItem},
  CadastroTipoVenda in 'CadastroTipoVenda.pas' {FormCadastroTipoVenda},
  CadastroClasse in '..\ArquivosComuns\CadastroClasse.pas' {FormCadastroClasse},
  CadastroClasseUsuario in '..\ArquivosComuns\CadastroClasseUsuario.pas' {FormCadastroClasseUsuario},
  RelatorioListagemProduto in '..\ArquivosComuns\RelatorioListagemProduto.pas' {FormRelatorioListagemProduto},
  TelaDadosVersaoLoja in 'TelaDadosVersaoLoja.pas' {FormTelaDadosVersaoLoja},
  CadastroManutencaoCupom in '..\ArquivosComuns\CadastroManutencaoCupom.pas' {FormCadastroManutencaoCupom},
  CadastroManutencaoContasReceber in '..\ArquivosComuns\CadastroManutencaoContasReceber.pas' {FormCadastroManutencaoContasReceber},
  CadastroConsulta in '..\ArquivosComuns\CadastroConsulta.pas' {FormCadastroConsulta},
  TelaRecalcularTotalizador in 'TelaRecalcularTotalizador.pas' {FormTelaRecalcularTotalizador},
  TelaConsultaTemplate in '..\..\Template\TelaConsultaTemplate.pas' {FormTelaConsultaTemplate},
  TelaConsultaTabelaPreco in '..\ArquivosComuns\TelaConsultaTabelaPreco.pas' {FormTelaConsultaTabelaPreco},
  CadastroProdutoTabelaPreco in '..\ArquivosComuns\CadastroProdutoTabelaPreco.pas' {FormCadastroProdutoTabelaPreco},
  TelaAtualizarSaldoDiarioProduto in '..\ArquivosComuns\TelaAtualizarSaldoDiarioProduto.pas' {FormTelaAtualizarSaldoDiarioProduto},
  CadastroProdutoComposicao in '..\ArquivosComuns\CadastroProdutoComposicao.pas' {FormCadastroProdutoComposicao},
  TelaConsultaProduto in '..\ArquivosComuns\TelaConsultaProduto.pas' {FormTelaConsultaProduto},
  RelatorioVendasConsignadas in '..\ArquivosComuns\RelatorioVendasConsignadas.pas' {FormRelatorioVendasConsignadas},
  RelatorioClienteCadastrado in '..\ArquivosComuns\RelatorioClienteCadastrado.pas' {FormRelatorioClienteCadastrado},
  CadastroProdutoOrdemPesquisa in '..\ArquivosComuns\CadastroProdutoOrdemPesquisa.pas' {FormCadastroProdutoOrdemPesquisa},
  RelatorioVendasPeriodoApuracaoMargem in '..\ArquivosComuns\RelatorioVendasPeriodoApuracaoMargem.pas' {FormRelatorioVendasPeriodoApuracaoMargem},
  CadastroTipoDocumento in '..\UnitFinanceiro\CadastroTipoDocumento.pas' {FormCadastroTipoDocumento},
  CadastroChequesRecebidos in '..\UnitFinanceiro\CadastroChequesRecebidos.pas' {FormCadastroChequesRecebidos},
  CadastroContaCorrente in '..\UnitFinanceiro\CadastroContaCorrente.pas' {FormCadastroContaCorrente},
  CadastroContasPagar in '..\UnitFinanceiro\CadastroContasPagar.pas' {FormCadastroContasPagar},
  CadastroContasReceber in '..\UnitFinanceiro\CadastroContasReceber.pas' {FormCadastroContasReceber},
  CadastroMovimentoBanco in '..\UnitFinanceiro\CadastroMovimentoBanco.pas' {FormCadastroMovimentoBanco},
  CadastroOperacaoBanco in '..\UnitFinanceiro\CadastroOperacaoBanco.pas' {FormCadastroOperacaoBanco},
  CadastroPlanodeContas in '..\UnitFinanceiro\CadastroPlanodeContas.pas' {FormCadastroPlanodeContas},
  CadastroPortador in '..\UnitFinanceiro\CadastroPortador.pas' {FormCadastroPortador},
  CadastroSituacaoCheque in '..\UnitFinanceiro\CadastroSituacaoCheque.pas' {FormCadastroSituacaoCheque},
  CadastroChequesHistorico in '..\UnitFinanceiro\CadastroChequesHistorico.pas' {FormCadastroChequesHistorico},
  TelaBaixarDocumentosReceber in '..\UnitFinanceiro\TelaBaixarDocumentosReceber.pas' {FormTelaBaixarDocumentosReceber},
  TelaBaixarDocumentosPagar in '..\UnitFinanceiro\TelaBaixarDocumentosPagar.pas' {FormTelaBaixarDocumentosPagar},
  TelaBaixarChequesRecebidos in '..\UnitFinanceiro\TelaBaixarChequesRecebidos.pas' {FormTelaBaixarChequesRecebidos},
  TelaConsultaNumerario in '..\ArquivosComuns\TelaConsultaNumerario.pas' {FormTelaConsultaNumerario},
  TelaConsultaConsignacoesPendentes in '..\ArquivosComuns\TelaConsultaConsignacoesPendentes.pas' {FormTelaConsultaConsignacoesPendentes},
  RelatorioContasPagarVencidas in '..\UnitFinanceiro\RelatorioContasPagarVENCIDAS.pas' {FormRelatorioContasPagarVENCIDAS},
  RelatorioContasPagarPAGAS in '..\UnitFinanceiro\RelatorioContasPagarPAGAS.pas' {FormRelatorioContasPagarPAGAS},
  RelatorioContasPagarAPAGAR in '..\UnitFinanceiro\RelatorioContasPagarAPAGAR.pas' {FormRelatorioContasPagarAPAGAR},
  RelatorioChequesRecebidos in '..\UnitFinanceiro\RelatorioChequesRecebidos.pas' {FormRelatorioChequeRecebidos},
  RelatorioExtratoMovimentoBanco in '..\UnitFinanceiro\RelatorioExtratoMovimentoBanco.pas' {FormRelatorioExtratoMovimentoBanco},
  TelaReabilitacaoCredito in '..\UnitCrediario\TelaReabilitacaoCredito.pas' {FormTelaReabilitacaoCredito},
  TelaConfiguracaoCrediario in '..\UnitCrediario\TelaConfiguracaoCrediario.pas' {FormTelaConfiguracaoCrediario},
  TelaDadosVersaoCrediario in '..\UnitCrediario\TelaDadosVersaoCrediario.pas' {FormTelaDadosVersaoCrediario},
  TelaEnvioCartasAviso in '..\UnitCrediario\TelaEnvioCartasAviso.pas' {FormTelaEnvioCartasAviso},
  RelatorioReabilitacaoSPC in '..\UnitCrediario\RelatorioReabilitacaoSPC.pas' {FormRelatorioReabilitacaoSPC},
  RelatorioExtratoCliente in '..\ArquivosComuns\RelatorioExtratoCliente.pas' {FormRelatorioExtratoCliente},
  TelaEnvioEmail in '..\ArquivosComuns\TelaEnvioEmail.pas' {FormTelaEnvioGeracaoEmail},
  TelaConfiguracaoEmail in '..\ArquivosComuns\TelaConfiguracaoEmail.pas' {FormTelaConfiguracaoEmail},
  CadastroConvenio in 'CadastroConvenio.pas' {FormCadastroConvenio},
  AssistenteListagemTEMPLATE in '..\..\Template\AssistenteListagemTEMPLATE.pas' {FormAssistenteListagem},
  TelaImpressaoDuplicatas in '..\ArquivosComuns\TelaImpressaoDuplicatas.pas' {FormTelaImpressaoDuplicata},
  ExtensoLib in '..\ArquivosComuns\ExtensoLib.pas',
  TelaEnvioEmailGeral in '..\ArquivosComuns\TelaEnvioEmailGeral.pas' {FormTelaEnvioEmailGeral},
  TelaEmissaoEtiquetasCodigoBarras in '..\ArquivosComuns\TelaEmissaoEtiquetasCodigoBarras.pas' {FormTelaEmissaoEtiquetasCodigoBarras},
  TelaConsultaPedidoCompra in '..\ArquivosComuns\TelaConsultaPedidoCompra.pas' {FormTelaConsultaPedidoCompra},
  TelaConsultaNotaCompra in '..\ArquivosComuns\TelaConsultaNotaCompra.pas' {FormTelaConsultaNotaCompra},
  TelaConsultaPedidoVenda in '..\ArquivosComuns\TelaConsultaPedidoVenda.pas' {FormTelaConsultaPedidoVenda},
  TelaConsultaNotaFiscal in '..\ArquivosComuns\TelaConsultaNotaFiscal.pas' {FormTelaConsultaNotaFiscal},
  CadastroCep in '..\ArquivosComuns\CadastroCep.pas' {FormCadastroCep},
  TelaReajustePreco in '..\UnitCompras\TelaReajustePreco.pas' {FormTelaReajustePreco},
  RelatorioContasReceberEmitidas in '..\ArquivosComuns\RelatorioContasReceberEmitidas.pas' {FormRelatorioContasReceberEmitidas},
  RelatorioContasPagarEMITIDAS in '..\UnitFinanceiro\RelatorioContasPagarEMITIDAS.pas' {FormRelatorioContasPagarEmitidas},
  TelaManutencaoProdutos in '..\ArquivosComuns\TelaManutencaoProdutos.pas' {FormTelaManutencaoProdutos},
  RelatorioProdutosPorFornecedor in '..\ArquivosComuns\RelatorioProdutosPorFornecedor.pas' {FormRelatorioProdutosPorFornecedor},
  TelaManutencaoFechamentoCaixa in '..\UnitCheckout\TelaManutencaoFechamentoCaixa.pas' {FormTelaManutencaoFechamentoCaixa},
  TelaZerarSaldoEstoque in 'TelaZerarSaldoEstoque.pas' {FormTelaZeraSaldoEstoque},
  RelatorioClientesSPC in 'RelatorioClientesSPC.pas' {FormRelatorioClientesSPC},
  TelaImpressaoTermicaCodBar in '..\ArquivosComuns\TelaImpressaoTermicaCodBar.pas' {FormTelaImpressaoTermicaCodBar},
  TelaConfiguracaoInventario in 'TelaConfiguracaoInventario.pas' {FormTelaConfiguracaoInventario},
  TelaContagemManual in 'TelaContagemManual.pas' {FormTelaContagemManual},
  TelaPlanoContas in '..\UnitFinanceiro\TelaPlanoContas.pas' {FormTelaPlanoContas},
  RelatorioDivergenciaInventario in 'RelatorioDivergenciaInventario.pas' {FormRelatorioDivergenciaInventario},
  RelatorioCurvaABC in 'RelatorioCurvaABC.pas' {FormRelatorioCurvaABC},
  SWEDA7000 in '..\UnitCheckout\SWEDA7000.pas',
  TelaMapaResumo in 'TelaMapaResumo.pas' {FormTelaGeracaoMapaResumo},
  RelatorioFisicoFinanceiroEstoque in 'RelatorioFisicoFinanceiroEstoque.pas' {FormRelatorioFisicoFinanceiroEstoque},
  TelaAtualizacaoCEP in '..\ArquivosComuns\TelaAtualizacaoCEP.pas' {FormTelaAtualizacaoCEP},
  RelatorioVendasPorGrade in 'RelatorioVendasPorGrade.pas' {FormRelatorioVendasPorGrade},
  RelatorioReceitasDespesasPlanoContas in '..\UnitFinanceiro\RelatorioReceitasDespesasPlanoContas.pas' {FormRelatorioReceitasDespesasPlanoContas},
  CadastroRemessaBancosContasReceber in '..\..\UnitGestao Oficial UNIT\UnitFinanceiro\CadastroRemessaBancosContasReceber.pas' {FormCadastroRemessaBancosContasReceber},
  CadastroRemessaBancos in '..\..\UnitGestao Oficial UNIT\UnitFinanceiro\CadastroRemessaBancos.pas' {FormCadastroRemessaBancos},
  TelaRemessaDocumentosReceber in '..\UnitFinanceiro\TelaRemessaDocumentosReceber.pas' {FormTelaRemessaDocumentosReceber},
  RelatorioRegistroInventario in 'RelatorioRegistroInventario.pas' {FormRelatorioRegistroInventario},
  RelatorioExtratoProdutos in 'RelatorioExtratoProdutos.pas' {FormRelatorioExtratoProdutos};

{$R *.RES}

begin
  Application.Initialize ;
  VersaoSistema := '1.76h' ;

  Retaguarda := true ;
  Application.Title := 'Gestão Loja';
  Application.CreateForm(TDM, DM);
  FormTelaLogin := TFormTelaLogin.Create(Application) ;
  if FormTelaLogin.ShowModal <> idOk then
    exit ;

  Application.CreateForm(TFormPrincipal, FormPrincipal);
  FormPrincipal.RodapePrincipal.Panels[1].Text := DM.SQLUsuariosUSUAA60LOGIN.Value ;
  FormPrincipal.RodapePrincipal.Panels[2].Text := DM.SQLConfigGeralEmpresaPadraoCalcField.Value ;
  FormPrincipal.RodapePrincipal.Panels[3].Text := 'Versão ' + VersaoSistema ;
  Application.Run ;
end.
