ALTER TABLE ORDEMSERVICOPRODUTO ADD teste NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICOPRODUTO SET teste = ORSPN3VALORUNIT;
commit work;
ALTER TABLE ORDEMSERVICOPRODUTO DROP ORSPN3VALORUNIT;
commit work;
ALTER TABLE ORDEMSERVICOPRODUTO ADD ORSPN3VALORUNIT NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICOPRODUTO SET ORSPN3VALORUNIT = teste;
commit work;
ALTER TABLE ORDEMSERVICOPRODUTO DROP teste;
commit work;



