
ALTER TABLE ORDEMSERVICO ADD teste NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICO SET teste = ORSEN3COMBUSTUVEL;
commit work;
ALTER TABLE ORDEMSERVICO DROP ORSEN3COMBUSTUVEL;
commit work;
ALTER TABLE ORDEMSERVICO ADD ORSEN3COMBUSTUVEL NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICO SET ORSEN3COMBUSTUVEL = teste;
commit work;
ALTER TABLE ORDEMSERVICO DROP teste;
commit work;