ALTER TABLE ORDEMSERVICO ADD teste NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICO SET teste = ORSEN3PESOFINAL;
commit work;
ALTER TABLE ORDEMSERVICO DROP ORSEN3PESOFINAL;
commit work;
ALTER TABLE ORDEMSERVICO ADD ORSEN3PESOFINAL NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICO SET ORSEN3PESOFINAL = teste;
commit work;
ALTER TABLE ORDEMSERVICO DROP teste;
commit work;





