ALTER TABLE ORDEMSERVICOPRODUTO ADD teste NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICOPRODUTO SET teste = ORSPN3VALORTOTAL;
commit work;
ALTER TABLE ORDEMSERVICOPRODUTO DROP ORSPN3VALORTOTAL;
commit work;
ALTER TABLE ORDEMSERVICOPRODUTO ADD ORSPN3VALORTOTAL NUMERIC(15,3);
commit work;
UPDATE ORDEMSERVICOPRODUTO SET ORSPN3VALORTOTAL = teste;
commit work;
ALTER TABLE ORDEMSERVICOPRODUTO DROP teste;
commit work;


