ALTER TABLE ORDEMSERVICO ADD teste NUMERIC(15,2);
commit work;
UPDATE ORDEMSERVICO SET teste = ORSEN2LIQUIDOFORNEC;
commit work;
ALTER TABLE ORDEMSERVICO DROP ORSEN2LIQUIDOFORNEC;
commit work;
ALTER TABLE ORDEMSERVICO ADD ORSEN2LIQUIDOFORNEC NUMERIC(15,2);
commit work;
UPDATE ORDEMSERVICO SET ORSEN2LIQUIDOFORNEC = teste;
commit work;
ALTER TABLE ORDEMSERVICO DROP teste;
commit work;




