CREATE TABLE EQUIPAMENTO (
    EQUIICOD          INTEGER NOT NULL,
    CLIEA13ID         CHAR(13) NOT NULL,
    EQUIA50DESCRICAO  CHAR(50),
    EQUIA40MODELO     CHAR(40),
    EQUIA20NUMSERIE   CHAR(20),
    MARCICOD          INTEGER
);

