CREATE TABLE ORDEMSERVICOPRODUTO (
    ORSEA13ID         CHAR(13) NOT NULL,
    PRODICOD          INTEGER NOT NULL,
    TECNICOD          INTEGER,
    ORSPN3QUANTIDADE  NUMERIC(3,1),
    ORSPN3VALORUNIT   NUMERIC(3,1),
    ORSPN3VALORTOTAL  NUMERIC(3,1)
);
