CREATE TABLE TECNICO (
    TECNICOD              INTEGER NOT NULL,
    TECNA60NOME           CHAR(60),
    TECNA80ESPECIALIDADE  CHAR(80),
    TECNA40NUMREGISTRO    CHAR(40),
    TECNA40CONSELHO       CHAR(40),
    TECNA2UF              CHAR(2)
);