CREATE TABLE OSITEMPRODUTO (
       OSA13ID              CHAR(13) NOT NULL,
       OSITICOD             INTEGER NOT NULL,
       OSIPICOD             INTEGER NOT NULL,
       PRODICOD             INTEGER,
       OSIPN3QTDE           NUMERIC(15,3) DEFAULT 0,
       OSIPN2VLRCUSTO       NUMERIC(15,2) DEFAULT 0,
       OSIPN2VLRTOTPROD     NUMERIC(15,2) DEFAULT 0,
       USUA60LOGIN          CHAR(60),
       PENDENTE             CHAR(1),
       REGISTRO             DATE,
       PRIMARY KEY (OSA13ID, OSITICOD, OSIPICOD)
);

CREATE UNIQUE INDEX XPKOSITEMPRODUTO ON OSITEMPRODUTO
(
       OSA13ID,
       OSITICOD,
       OSIPICOD
);

CREATE INDEX XIF253OSITEMPRODUTO ON OSITEMPRODUTO
(
       OSA13ID,
       OSITICOD
);

CREATE INDEX XIF254OSITEMPRODUTO ON OSITEMPRODUTO
(
       PRODICOD
);