CREATE TABLE HELPDESK 
(
  HELPA13ID	CHAR(13) NOT NULL,
  EMPRICOD	INTEGER,
  TERMICOD	INTEGER,
  HELPICOD	INTEGER NOT NULL,
  CLIEA13ID	CHAR(13),
  HELPCCONTATO	CHAR(60),
  HELPDINICIO	TIMESTAMP,
  HELPTSOLICITACAO	VARCHAR(1000),
  HELPTSOLUCAO	VARCHAR(1000),
  HELPCTIPO	CHAR(1),
  TPHPICOD	INTEGER,
  HELPCNIVEL	CHAR(1),
  HELPDTERMINO	TIMESTAMP,
  HELPCPERGUNTACHAVE	CHAR(100),
  PRODICOD	INTEGER,
  PENDENTE	CHAR(1),
  REGISTRO	TIMESTAMP,
 PRIMARY KEY (HELPA13ID)
);
