
CREATE TABLE CLIENTEHELPDESKPRODUTO 
(
  PRODICOD	INTEGER NOT NULL,
  CLIEA13ID	CHAR(13) NOT NULL,
  CLPOCTEMHELP	CHAR(1),
  PENDENTE	CHAR(1),
  REGISTRO	TIMESTAMP,
 PRIMARY KEY (PRODICOD, CLIEA13ID)
);
