CREATE TABLE PRESTACONTAS (
  EMPRICOD INTEGER NOT NULL,
  PRECODATA TIMESTAMP NOT NULL,
  USUAICOD INTEGER NOT NULL,
  VLRMOEDA NUMERIC(15, 2),
  VLRCHVISTA NUMERIC(15, 2),
  VLRCHPRAZO NUMERIC(15, 2),
  VLRNTPRAZO NUMERIC(15, 2),
  VLRNTAVULSO NUMERIC(15, 2),
  VLRCARCREDITO NUMERIC(15, 2),
  VLRVALES NUMERIC(15, 2),
  VLRORFRE NUMERIC(15, 2),
  VLROUTSAIDA NUMERIC(15, 2),
  REGISTRO TIMESTAMP,
  PENDENTE CHAR(1)
)