CREATE TABLE TIPOHELPDESK 
(
  TPHPICOD	INTEGER NOT NULL,
  TPHPA60DESCR	CHAR(60),
  TPHPCGERAPENDENCIA	CHAR(1),
  TPHPCGERATAREFA	CHAR(1),
  PENDENTE	CHAR(1),
  REGISTRO	TIMESTAMP,
 PRIMARY KEY (TPHPICOD)
);
