CREATE TABLE COTACAOVENDAITEM 
(
  CTVDA13ID	 CHAR(13) NOT NULL,
  CTVIICOD	 INTEGER NOT NULL,
  PRODICOD	 INTEGER,
  CTVIA60PRODDESCR	 CHAR(60),
  CTVIN3PRODVLR	 DECIMAL(15,3),
  CTVIN3PRODQTDE	 DECIMAL(15,3),
  CTVIN2PERCDESC	 DECIMAL(15,3),
  CTVIN3VLRDESCONTO	 DECIMAL(15,3),
  CTVIN3VLRCUSTO	 DECIMAL(15,3),
  CTVIN3TOTAL	 DECIMAL(15,3),
  CTVIN3ESTOQPRODUTO	 DECIMAL(15,3),
  PENDENTE	 CHAR(1),
  REGISTRO	 TIMESTAMP,
 PRIMARY KEY (CTVDA13ID, CTVIICOD)
);