CREATE TABLE PRNEPRODUTO (
       PRNEA13ID            CHAR(13) NOT NULL,
       PNPRICOD             INTEGER NOT NULL,
       PNPRA30CODPROD       CHAR(30),
       PNPRA60DESCR         CHAR(60),
       PNPRN3QTDE           NUMERIC(15,3),
       PNPRA5UNIDADE        CHAR(5),
       PNPRN2VLRUNIT        NUMERIC(15,2),
       PNPRN2PERCDESC       NUMERIC(15,2),
       PNPRN2VLRDESC        NUMERIC(15,2),
       PNPRN2PERCACRES      NUMERIC(15,2),
       PNPRN2VLRACRES       NUMERIC(15,2),
       PNPRN2TOTITEM        NUMERIC(15,2),
       PNPRA15PRZENTREGA    CHAR(15),
       PNPRA254OBS          VARCHAR(254),
       REGISTRO             DATE,
       PENDENTE             CHAR(1),
       PRIMARY KEY (PRNEA13ID, PNPRICOD)
);