CREATE TABLE FRETE (
	FRETA13ID CHAR(13) NOT NULL,
	EMPRICOD INTEGER,
	TERMICOD INTEGER,
	FRETICOD INTEGER,
	CLIEA13IDREMETE CHAR(13),
	CLIEA13IDDESTINO CHAR(13),
	CLIEA13IDCONSIG CHAR(13),
	FRETCPAGO CHAR(1),
	FRETTOBS VARCHAR(255),
	FRETN2VLR NUMERIC(15,3),	
	FRETN2VLRTOTAL NUMERIC(15,3),	
	FRETN3QTDETOTAL NUMERIC(15,3),	
        FRETN2BASECALCULO NUMERIC(15,3),	
	FRETN2ICMS NUMERIC(15,3),	
	PLCTA15COD CHAR(15),
	PLRCICOD INTEGER,
        FRETCSTATUS CHAR(1),
        REGISTRO             DATE,
        PENDENTE             CHAR(1),
	PRIMARY KEY(FRETA13ID)	
);
	
CREATE TABLE FRETEITEM (	
	FRETA13ID CHAR(13) NOT NULL,
	FRITICOD INTEGER NOT NULL,
	PRODICOD INTEGER,
	FRITINOTAFISCAL INTEGER,
	PRODN2VLR NUMERIC(15,3),
        FRITN2ICMS NUMERIC(15,3),
        FRITN2VLRICMS NUMERIC(15,3),
	UNIDICOD INTEGER,
	FRITN3QTDE NUMERIC(15,3),		
	FRITA30ESPECIE CHAR(30),
	FRITA30MARCA CHAR(30),
        REGISTRO    DATE,
	PENDENTE    CHAR(1),
	PRIMARY KEY(FRETA13ID,FRITICOD)
);