CREATE TABLE BOMBA 
(
  EMPRICOD	     INTEGER NOT NULL,
  BOMBICOD	     INTEGER NOT NULL,
  TANQICOD	     INTEGER,
  BOMBA30DESCR	     CHAR(30),
  BOMBN3VLRVISTA     DECIMAL(15,3),
  BOMBN3ENCERRANTE   DECIMAL(15,3),
  PENDENTE	     CHAR(1),
  REGISTRO	     TIMESTAMP,
  CONVERTER	     CHAR(2),
  STATUS	     CHAR(1),
  POINT	             INTEGER,
  BOMBN2CONT         DECIMAL(15,2), 
 PRIMARY KEY (EMPRICOD, BOMBICOD)
);