CREATE TABLE CLIENTEHELPDESK 
(
  CLIEA13ID	CHAR(13) NOT NULL,
  EMPRICOD	INTEGER,
  TERMICOD	INTEGER,
  CLHPDCADASTRO	TIMESTAMP,
  CLHPDFIRSTHELP	TIMESTAMP,
  CLHPDLASTHELP	TIMESTAMP,
  CLHPINROHELP	INTEGER,
  CLHPDFIRSTRESET	TIMESTAMP,
  CLHPDLASTRESET	TIMESTAMP,
  CLHPINRORESETS	INTEGER,
  CLHPTDADOSTEC	VARCHAR(1000),
  PENDENTE	CHAR(1),
  REGISTRO	TIMESTAMP,
 PRIMARY KEY (CLIEA13ID)
);
