CREATE TABLE SPED_C425 (
    NUMEROSERIEECF  VARCHAR(20) NOT NULL,
    DATAREDUCAO     DATE NOT NULL,
    COD_ITEM        INTEGER NOT NULL,
    QUANTIDADE      DOUBLE PRECISION  NOT NULL,
    UND             VARCHAR(6) NOT NULL,
    VALORITEM       DOUBLE PRECISION NOT NULL,
    VALORPIS        DOUBLE PRECISION NOT NULL,
    VALORCOFINS     DOUBLE PRECISION NOT NULL
);
CREATE INDEX SPED_C425_IDX1 ON SPED_C425 (NUMEROSERIEECF, DATAREDUCAO, COD_ITEM);
