CREATE TABLE SPED_C420 (
    NUMEROSERIEECF        VARCHAR(20) NOT NULL,
    DATAREDUCAO           DATE NOT NULL,
    TOTALIZADOR           VARCHAR(7) NOT NULL,
    VALORACUMULADO        DOUBLE PRECISION NOT NULL,
    NUMEROTOTALIZADOR     INTEGER,
    DESCRICAOTOTALIZADOR  VARCHAR(60)
);
ALTER TABLE SPED_C420 ADD PRIMARY KEY (NUMEROSERIEECF, DATAREDUCAO, TOTALIZADOR);
