CREATE TABLE SPED_C405 (
    NUMEROSERIEECF  VARCHAR(20) NOT NULL,
    DATAREDUCAO     DATE NOT NULL,
    CRO             CHAR(3) NOT NULL,
    CRZ             CHAR(6) NOT NULL,
    COO_FINAL       VARCHAR(6) NOT NULL,
    GT_FIM          DOUBLE PRECISION NOT NULL,
    VLR_BRUTO       DOUBLE PRECISION NOT NULL
);
ALTER TABLE SPED_C405 ADD PRIMARY KEY (NUMEROSERIEECF, DATAREDUCAO);
