CREATE TABLE SPED_C460 (
    NUMEROSERIEECF  VARCHAR(20) NOT NULL,
    DATAREDUCAO     DATE NOT NULL,
    NUMEROCOO       VARCHAR(6) NOT NULL,
    CODMODELO       CHAR(2) NOT NULL,
    CODSITUACAO     CHAR(2) NOT NULL,
    DATAEMISSAO     DATE NOT NULL,
    VALORPIS        DOUBLE PRECISION NOT NULL,
    VALORCOFINS     DOUBLE PRECISION NOT NULL,
    CPFCNPJ         VARCHAR(14),
    NOMEADQUIRENTE  VARCHAR(60),
    VALORDOC        DOUBLE PRECISION
);
ALTER TABLE SPED_C460 ADD PRIMARY KEY (NUMEROSERIEECF, DATAREDUCAO, NUMEROCOO);
