CREATE TABLE SPED_C470 (
    NUMEROSERIEECF  VARCHAR(20) NOT NULL,
    DATAREDUCAO     DATE NOT NULL,
    NUMEROCOO       VARCHAR(6) NOT NULL,
    CODITEM         INTEGER NOT NULL,
    QUANTIDADE      DOUBLE PRECISION NOT NULL,
    QTD_CANCEL      DOUBLE PRECISION,
    UNID            VARCHAR(6) NOT NULL,
    CST_ICMS        VARCHAR(3) NOT NULL,
    CFOPITEM        VARCHAR(4) NOT NULL,
    ALIQUOTA        DOUBLE PRECISION NOT NULL,
    VALORPIS        DOUBLE PRECISION NOT NULL,
    VALORCOFINS     DOUBLE PRECISION NOT NULL,
    VALORITEM       DOUBLE PRECISION
);